MEMORY_TIC_TAC_TOE_Board Class Reference
Represents the Tic-Tac-Toe game board.
#include <Memory_Tic-Tac-Toe.h>
Public Member Functions
MEMORY_TIC_TAC_TOE_Board ()
Default constructor that initializes a 3x3 X-O board.
bool update_board (Move< char > *move)
Updates the board with a player's move.
bool is_win (Player< char > *player)
Checks if the given player has won the game.
bool is_lose (Player< char > *)
Checks if the given player has lost the game.
bool is_draw (Player< char > *player)
Checks if the game has ended in a draw.
bool game_is_over (Player< char > *player)
Determines if the game is over (win or draw).
Public Member Functions inherited from Board< char >
Board (int rows, int columns)
Construct a board with given dimensions.
virtual ~Board ()
Virtual destructor. Frees allocated board memory.
vector< vector< char > > get_board_matrix () const
Return a copy of the current board as a 2D vector.
int get_rows () const
Get number of rows.
int get_columns () const
Get number of columns.
int get_n_moves () const
Get number of moves.
char get_cell (int x, int y)
Return content of cell x, y in current board.
Private Attributes
char blank_symbol = '.'
Character used to represent an empty cell on the board.
char took = '?'
Character used to represent an empty cell on the board.
vector< vector< char > > hidden_board
Additional Inherited Members
Protected Attributes inherited from Board< char >
int rows
Number of rows.
int columns
Number of columns.
vector< vector< char > > board
2D vector for the board
int n_moves
Number of moves made.
Detailed Description
Represents the Tic-Tac-Toe game board.
This class inherits from the generic Board<char> class and implements the specific logic required for the Tic-Tac-Toe (X-O) game, including move updates, win/draw detection, and display functions.
See also
Board
Definition at line 27 of file Memory_Tic-Tac-Toe.h.
Constructor & Destructor Documentation
MEMORY_TIC_TAC_TOE_Board()
MEMORY_TIC_TAC_TOE_Board::MEMORY_TIC_TAC_TOE_Board ()
Default constructor that initializes a 3x3 X-O board.
Definition at line 9 of file Memory_Tic-Tac-Toe.cpp.
                                                    : Board(3,3) {
    hidden_board = vector<vector<char>>(3, vector<char>(3, blank_symbol));
    for (auto& row : board)
        for (auto& cell : row)
            cell = blank_symbol;
}
References blank_symbol, Board< char >::board, and hidden_board.
Member Function Documentation
game_is_over()
bool MEMORY_TIC_TAC_TOE_Board::game_is_over (Player< char > * player) [virtual]
Determines if the game is over (win or draw).
Parameters
player Pointer to the playerended, to evaluate.
Returns
true if the game has false otherwise.
Implements Board< char >.
Definition at line 64 of file Memory_Tic-Tac-Toe.cpp.
                                                                {
    return is_win(player) || is_draw(player) ;
}
References is_draw(), and is_win().
is_draw()
bool MEMORY_TIC_TAC_TOE_Board::is_draw (Player< char > * player) [virtual]
Checks if the game has ended in a draw.
Parameters
player Pointer to the player being checked.
Returns
true if all cells are filled and no player has won, false otherwise.
Implements Board< char >.
Definition at line 60 of file Memory_Tic-Tac-Toe.cpp.
                                                           {
    return (n_moves == 9 && !is_win(player));
}
References is_win(), and Board< char >::n_moves.
Referenced by game_is_over().
is_lose()
bool MEMORY_TIC_TAC_TOE_Board::is_lose (Player< char > *) [inline], [virtual]
Checks if the given player has lost the game.
Parameters
player Pointer to the player being checked.
Returns
Always returns false (not used in X-O logic).
Implements Board< char >.
Definition at line 59 of file Memory_Tic-Tac-Toe.h.
{ return false; };
is_win()
bool MEMORY_TIC_TAC_TOE_Board::is_win (Player< char > * player) [virtual]
Checks if the given player has won the game.
Parameters
player Pointer to the player being checked.
Returns
true if the player has a winning line, false otherwise.
Implements Board< char >.
Definition at line 36 of file Memory_Tic-Tac-Toe.cpp.
                                                     {
    char sym = p->get_symbol();
    auto eq = [&](char a, char b, char c){
        return a == sym && b == sym && c == sym;
    };
    // rows
    for (int i = 0; i < rows; ++i)
        if (eq(hidden_board[i][0], hidden_board[i][1], hidden_board[i][2]))
            return true;
    // columns
    for (int j = 0; j < columns; ++j)
        if (eq(hidden_board[0][j], hidden_board[1][j], hidden_board[2][j]))
            return true;
    // diagonals
    if (eq(hidden_board[0][0], hidden_board[1][1], hidden_board[2][2])) return true;
    if (eq(hidden_board[0][2], hidden_board[1][1], hidden_board[2][0])) return true;
    return false;
}
References Board< char >::columns, Player< T >::get_symbol(), hidden_board, and Board< char >::rows.
Referenced by game_is_over(), and is_draw().
update_board()
bool MEMORY_TIC_TAC_TOE_Board::update_board (Move< char > * move) [virtual]
Updates the board with a player's move.
Parameters
move Pointer to a Move<char> object containing move coordinates and symbol.
Returns
true if the move is valid and successfully applied, false otherwise.
Implements Board< char >.
Definition at line 16 of file Memory_Tic-Tac-Toe.cpp.
                                                            {
    int x = move->get_x();
    int y = move->get_y();
    char sym = move->get_symbol();
    if (x < 0 || x >= rows || y < 0 || y >= columns)
        return false;
    if (hidden_board[x][y] != blank_symbol)
        return false;
    hidden_board[x][y] = sym;
    // visible board stays always blank
    board[x][y] = sym;
    n_moves++;
    return true;
}
References blank_symbol, Board< char >::board, Board< char >::columns, Player< T >::get_symbol(), hidden_board, Board< char >::n_moves, and Board< char >::rows.
Member Data Documentation
blank_symbol
char MEMORY_TIC_TAC_TOE_Board::blank_symbol = '.' [private]
Character used to represent an empty cell on the board.
Definition at line 29 of file Memory_Tic-Tac-Toe.h.
Referenced by MEMORY_TIC_TAC_TOE_Board(), and update_board().
hidden_board
vector<vector<char> > MEMORY_TIC_TAC_TOE_Board::hidden_board [private]
Definition at line 32 of file Memory_Tic-Tac-Toe.h.
Referenced by is_win(), MEMORY_TIC_TAC_TOE_Board(), and update_board().
took
char MEMORY_TIC_TAC_TOE_Board::took = '?' [private]
Character used to represent an empty cell on the board.
Definition at line 30 of file Memory_Tic-Tac-Toe.h.
The documentation for this class was generated from the following files:
include/Memory_Tic-Tac-Toe.h
src/Memory_Tic-Tac-Toe.cpp