Diamond_Tic_Tac_Toe_Board Class Reference
#include <Diamond_Tic_Tac_Toe.h>
Public Member Functions
Diamond_Tic_Tac_Toe_Board ()
Constructor: Initializes the Diamond board in a diamond shape.
bool update_board (Move< char > *move)
Updates the board with a player's move.
bool is_win (Player< char > *player)
Checks if the given player has won the game.
bool is_lose (Player< char > *)
Checks if the given player has lost the game.
bool is_draw (Player< char > *player)
Checks if the game has ended in a draw.
bool game_is_over (Player< char > *player)
Determines if the game is over (win or draw).
virtual ~Diamond_Tic_Tac_Toe_Board ()
Public Member Functions inherited from Board< char >
Board (int rows, int columns)
Construct a board with given dimensions.
virtual ~Board ()
Virtual destructor. Frees allocated board memory.
vector< vector< char > > get_board_matrix () const
Return a copy of the current board as a 2D vector.
int get_rows () const
Get number of rows.
int get_columns () const
Get number of columns.
int get_n_moves () const
Get number of moves.
char get_cell (int x, int y)
Return content of cell x, y in current board.
Private Attributes
char blank_symbol = '.'
Character used to represent an empty cell on the board.
Additional Inherited Members
Protected Attributes inherited from Board< char >
int rows
Number of rows.
int columns
Number of columns.
vector< vector< char > > board
2D vector for the board
int n_moves
Number of moves made.
Detailed Description
Definition at line 9 of file Diamond_Tic_Tac_Toe.h.
Constructor & Destructor Documentation
Diamond_Tic_Tac_Toe_Board()
Diamond_Tic_Tac_Toe_Board::Diamond_Tic_Tac_Toe_Board ()
Constructor: Initializes the Diamond board in a diamond shape.
Definition at line 10 of file Diamond_Tic_Tac_Toe.cpp.
                                                     : Board<char>(7, 7) {
    // Logic to draw the Diamond shape on a 7x7 grid.
    // The center is at (3, 3). The Manhattan distance radius is 3.
    // Equation: abs(row - 3) + abs(col - 3) <= 3
    for (int i = 0; i < rows; i++) {
        for (int j = 0; j < columns; j++) {
            if (abs(i - 3) + abs(j - 3) <= 3) {
                board[i][j] = blank_symbol; // Inside the Diamond (Valid cell)
            } else {
                board[i][j] = '#'; // Outside the Diamond (Invalid/Decor)
            }
        }
    }
}
References blank_symbol, Board< char >::board, Board< char >::columns, and Board< char >::rows.
~Diamond_Tic_Tac_Toe_Board()
virtual Diamond_Tic_Tac_Toe_Board::~Diamond_Tic_Tac_Toe_Board () [inline], [virtual]
Definition at line 54 of file Diamond_Tic_Tac_Toe.h.
{};
Member Function Documentation
game_is_over()
bool Diamond_Tic_Tac_Toe_Board::game_is_over (Player< char > * player) [virtual]
Determines if the game is over (win or draw).
Parameters
player Pointer to the playerended, to evaluate.
Returns
true if the game has false otherwise.
Implements Board< char >.
Definition at line 122 of file Diamond_Tic_Tac_Toe.cpp.
                                                                 {
    return is_win(player) || is_draw(player);
}
References is_draw(), and is_win().
is_draw()
bool Diamond_Tic_Tac_Toe_Board::is_draw (Player< char > * player) [virtual]
Checks if the game has ended in a draw.
Parameters
player Pointer to the player being checked.
Returns
true if all cells are filled and no player has won, false otherwise.
Implements Board< char >.
Definition at line 118 of file Diamond_Tic_Tac_Toe.cpp.
                                                            {
    return (n_moves == 25 && !is_win(player));
}
References is_win(), and Board< char >::n_moves.
Referenced by game_is_over().
is_lose()
bool Diamond_Tic_Tac_Toe_Board::is_lose (Player< char > *) [inline], [virtual]
Checks if the given player has lost the game.
Parameters
player Pointer to the player being checked.
Returns
Always returns false (not used in X-O logic).
Implements Board< char >.
Definition at line 38 of file Diamond_Tic_Tac_Toe.h.
{ return false; };
is_win()
bool Diamond_Tic_Tac_Toe_Board::is_win (Player< char > * player) [virtual]
Checks if the given player has won the game.
Parameters
player Pointer to the player being checked.
Returns
true if the player has a winning line, false otherwise.
Implements Board< char >.
Definition at line 50 of file Diamond_Tic_Tac_Toe.cpp.
                                                           {
    char sym = player->get_symbol();
    // Variables to store the maximum consecutive sequence found in each direction
    int max_row = 0; // Horizontal
    int max_col = 0; // Vertical
    int max_diag1 = 0; // Main Diagonal (Top-Left to Bottom-Right)
    int max_diag2 = 0; // Anti-Diagonal (Top-Right to Bottom-Left)
    // Iterate over every cell in the board
    for (int i = 0; i < rows; i++) {
        for (int j = 0; j < columns; j++) {
            // If the cell does not belong to the current player, skip it
            if (board[i][j] != sym) continue;
            // 1. Check Horizontal (Row)
            int current_row = 0;
            for (int k = 0; k < 7; k++) {
                if (j + k < columns && board[i][j + k] == sym) current_row++;
                else break;
            }
            if (current_row > max_row) max_row = current_row;
            // 2. Check Vertical (Column)
            int current_col = 0;
            for (int k = 0; k < 7; k++) {
                if (i + k < rows && board[i + k][j] == sym) current_col++;
                else break;
            }
            if (current_col > max_col) max_col = current_col;
            // 3. Check Main Diagonal
            int current_diag1 = 0;
            for (int k = 0; k < 7; k++) {
                if (i + k < rows && j + k < columns && board[i + k][j + k] == sym) current_diag1++;
                else break;
            }
            if (current_diag1 > max_diag1) max_diag1 = current_diag1;
            // 4. Check Anti-Diagonal
            int current_diag2 = 0;
            for (int k = 0; k < 7; k++) {
                if (i + k < rows && j - k >= 0 && board[i + k][j - k] == sym) current_diag2++;
                else break;
            }
            if (current_diag2 > max_diag2) max_diag2 = current_diag2;
        }
    }
    // Win Condition: One line of length >= 4 AND another line of length >= 3
    // The two lines must be in DIFFERENT directions.
    // Case 1: Primary line (4) is Horizontal. Secondary (3) must be Vertical or Diagonal.
    if (max_row >= 4 && (max_col >= 3 || max_diag1 >= 3 || max_diag2 >= 3)) return true;
    // Case 2: Primary line (4) is Vertical. Secondary (3) must be Horizontal or Diagonal.
    if (max_col >= 4 && (max_row >= 3 || max_diag1 >= 3 || max_diag2 >= 3)) return true;
    // Case 3: Primary line (4) is Main Diagonal. Secondary (3) must be Row, Col, or Anti-Diag.
    if (max_diag1 >= 4 && (max_row >= 3 || max_col >= 3 || max_diag2 >= 3)) return true;
    // Case 4: Primary line (4) is Anti-Diagonal. Secondary (3) must be Row, Col, or Main Diag.
    if (max_diag2 >= 4 && (max_row >= 3 || max_col >= 3 || max_diag1 >= 3)) return true;
    return false;
}
References Board< char >::board, Board< char >::columns, Player< T >::get_symbol(), and Board< char >::rows.
Referenced by game_is_over(), and is_draw().
update_board()
bool Diamond_Tic_Tac_Toe_Board::update_board (Move< char > * move) [virtual]
Updates the board with a player's move.
Parameters
move Pointer to a Move<char> object containing move coordinates and symbol.
Returns
true if the move is valid and successfully applied, false otherwise.
Implements Board< char >.
Definition at line 26 of file Diamond_Tic_Tac_Toe.cpp.
                                                             {
    int x = move->get_x();
    int y = move->get_y();
    char mark = move->get_symbol();
    // 1. Check boundaries.
    // 2. Check if the cell is valid (not '#').
    // 3. Allow move if cell is empty OR if mark is 0 (Undo operation).
    if (x >= 0 && x < rows && y >= 0 && y < columns &&
        board[x][y] != '#' &&
        (board[x][y] == blank_symbol || mark == 0)) {
        if (mark == 0) { // Undo move
            n_moves--;
            board[x][y] = blank_symbol;
        } else { // Apply move
            n_moves++;
            board[x][y] = toupper(mark);
        }
        return true;
    }
    return false;
}
References blank_symbol, Board< char >::board, Board< char >::columns, Player< T >::get_symbol(), and Board< char >::n_moves.
Member Data Documentation
blank_symbol
char Diamond_Tic_Tac_Toe_Board::blank_symbol = '.' [private]
Character used to represent an empty cell on the board.
Definition at line 11 of file Diamond_Tic_Tac_Toe.h.
Referenced by Diamond_Tic_Tac_Toe_Board(), and update_board().
The documentation for this class was generated from the following files:
include/Diamond_Tic_Tac_Toe.h
src/Diamond_Tic_Tac_Toe.cpp