smartPlayer< T > Class Template Reference
#include <Smart_Player.h>
Public Member Functions
smartPlayer (string n, T s, PlayerType t)
virtual pair< int, int > calculateMove ()
virtual ~smartPlayer ()
Public Member Functions inherited from Player< T >
Player (string n, T s, PlayerType t)
Construct a player with name, symbol, and type.
virtual ~Player ()
string get_name () const
Get the player's name.
PlayerType get_type () const
Get player type (e.g., 'H' or 'C').
T get_symbol () const
Get the player's symbol.
Board< T > * get_board_ptr () const
Get a pointer to the game board.
void set_board_ptr (Board< T > *b)
Assign the board pointer for the player.
Protected Member Functions
virtual T get_opponent_symbol () const
virtual int evaluate_board (const vector< vector< T > > &b, T ai, T opp, int N=3) const
virtual bool is_win (const vector< vector< T > > &b, T symbol, int N=3) const
virtual bool is_draw (const vector< vector< T > > &b, int N=3) const
virtual int minimax (vector< vector< T > > &b, bool maximizingPlayer, T ai, T opp, int alpha, int beta, int depth, int N=3)
Additional Inherited Members
Protected Attributes inherited from Player< T >
string name
Player name.
PlayerType type
Player type (e.g., HUMAN or COMPUTER)
T symbol
Players symbol on board.
Board< T > * boardPtr
Pointer to the game board.
Detailed Description
template<typename T>
class smartPlayer< T >
Definition at line 15 of file Smart_Player.h.
Constructor & Destructor Documentation
smartPlayer()
template<typename T >
smartPlayer< T >::smartPlayer (string n, T s, PlayerType t) [inline]
Definition at line 151 of file Smart_Player.h.
: Player<T>(n, s, t) {}
~smartPlayer()
template<typename T >
virtual smartPlayer< T >::~smartPlayer () [inline], [virtual]
Definition at line 188 of file Smart_Player.h.
{}
Member Function Documentation
calculateMove()
template<typename T >
virtual pair< int, int > smartPlayer< T >::calculateMove () [inline], [virtual]
Reimplemented in smartPlayer2, DiamondSmartPlayer, and MisereSmartPlayer.
Definition at line 153 of file Smart_Player.h.
                                           {
        Board<T>* board_ptr = this->get_board_ptr();
        if (!board_ptr) throw runtime_error("Board not assigned to player!");
        auto tempBoard = board_ptr->get_board_matrix();
        int rows = tempBoard.size();
        int cols = tempBoard[0].size();
        int bestVal = numeric_limits<int>::min();
        int bestX = -1, bestY = -1;
        T ai = this->get_symbol();
        T opp = get_opponent_symbol();
        int maxDepth = 3; // tweak: higher depth = stronger AI but slower
        for (int i = 0; i < rows; i++)
            for (int j = 0; j < cols; j++)
                if (tempBoard[i][j] == '.') {
                    tempBoard[i][j] = ai;
                    int moveVal = minimax(tempBoard, false, ai, opp,
                                          numeric_limits<int>::min(),
                                          numeric_limits<int>::max(),
                                          maxDepth);
                    tempBoard[i][j] = '.';
                    if (moveVal > bestVal) {
                        bestVal = moveVal;
                        bestX = i;
                        bestY = j;
                    }
                }
        return {bestX, bestY};
    }
References Player< T >::get_board_ptr(), smartPlayer< T >::get_opponent_symbol(), Player< T >::get_symbol(), smartPlayer< T >::minimax(), and Player< T >::Player().
evaluate_board()
template<typename T >
virtual int smartPlayer< T >::evaluate_board (const vector< vector< T > > & b, T ai, T opp, int N = 3) const [inline], [protected], [virtual]
Reimplemented in DiamondSmartPlayer, SUS_SmartPlayer, wordSmartPlayer, and smartPlayer2.
Definition at line 27 of file Smart_Player.h.
                                                                                         {
        int score = 0;
        int rows = b.size();
        int cols = b[0].size();
        auto count_sequence = [&](int i, int j, int dx, int dy, T symbol) {
            int cnt = 0;
            for (int k = 0; k < N; k++) {
                int x = i + k * dx;
                int y = j + k * dy;
                if (x < 0 || x >= rows || y < 0 || y >= cols) return 0;
                if (b[x][y] == symbol) cnt++;
                else if (b[x][y] != '.') return 0; // blocked
            }
            return cnt;
        };
        for (int i = 0; i < rows; i++)
            for (int j = 0; j < cols; j++) {
                score += count_sequence(i, j, 0, 1, ai); // row
                score += count_sequence(i, j, 1, 0, ai); // column
                score += count_sequence(i, j, 1, 1, ai); // diag TL-BR
                score += count_sequence(i, j, 1, -1, ai); // diag TR-BL
                score -= count_sequence(i, j, 0, 1, opp);
                score -= count_sequence(i, j, 1, 0, opp);
                score -= count_sequence(i, j, 1, 1, opp);
                score -= count_sequence(i, j, 1, -1, opp);
            }
        return score;
    }
References Player< T >::symbol.
Referenced by smartPlayer2::evaluate_board(), and smartPlayer< T >::minimax().
get_opponent_symbol()
template<typename T >
virtual T smartPlayer< T >::get_opponent_symbol () const [inline], [protected], [virtual]
Reimplemented in DiamondSmartPlayer, and MisereSmartPlayer.
Definition at line 18 of file Smart_Player.h.
                                          {
        // This is default X-O symbols
        if constexpr (is_same<T, char>::value) {
            return (this->get_symbol() == 'X') ? 'O' : 'X';
        }
        return T();
    }
References Player< T >::get_symbol().
Referenced by smartPlayer< T >::calculateMove(), and smartPlayer< T >::is_draw().
is_draw()
template<typename T >
virtual bool smartPlayer< T >::is_draw (const vector< vector< T > > & b, int N = 3) const [inline], [protected], [virtual]
Reimplemented in smartPlayer2.
Definition at line 103 of file Smart_Player.h.
                                                                      {
        for (auto &row : b)
            for (auto &cell : row)
                if (cell == '.') return false;
        return !is_win(b, this->get_symbol(), N) && !is_win(b, get_opponent_symbol(), N);
    }
References smartPlayer< T >::get_opponent_symbol(), Player< T >::get_symbol(), and smartPlayer< T >::is_win().
Referenced by smartPlayer2::is_draw(), and smartPlayer< T >::minimax().
is_win()
template<typename T >
virtual bool smartPlayer< T >::is_win (const vector< vector< T > > & b, T symbol, int N = 3) const [inline], [protected], [virtual]
Reimplemented in SUS_SmartPlayer, wordSmartPlayer, DiamondSmartPlayer, and smartPlayer2.
Definition at line 60 of file Smart_Player.h.
                                                                               {
        int rows = b.size();
        int cols = b[0].size();
        // Rows
        for (int i = 0; i < rows; i++)
            for (int j = 0; j <= cols - N; j++) {
                bool win = true;
                for (int k = 0; k < N; k++)
                    if (b[i][j + k] != symbol) { win = false; break; }
                if (win) return true;
            }
        // Columns
        for (int j = 0; j < cols; j++)
            for (int i = 0; i <= rows - N; i++) {
                bool win = true;
                for (int k = 0; k < N; k++)
                    if (b[i + k][j] != symbol) { win = false; break; }
                if (win) return true;
            }
        // Diagonal TL-BR
        for (int i = 0; i <= rows - N; i++)
            for (int j = 0; j <= cols - N; j++) {
                bool win = true;
                for (int k = 0; k < N; k++)
                    if (b[i + k][j + k] != symbol) { win = false; break; }
                if (win) return true;
            }
        // Diagonal TR-BL
        for (int i = 0; i <= rows - N; i++)
            for (int j = N - 1; j < cols; j++) {
                bool win = true;
                for (int k = 0; k < N; k++)
                    if (b[i + k][j - k] != symbol) { win = false; break; }
                if (win) return true;
            }
        return false;
    }
References Player< T >::symbol.
Referenced by smartPlayer< T >::is_draw(), smartPlayer2::is_win(), and smartPlayer< T >::minimax().
minimax()
template<typename T >
virtual int smartPlayer< T >::minimax (vector< vector< T > > & b, bool maximizingPlayer, T ai, T opp, int alpha, int beta, int depth, int N = 3) [inline], [protected], [virtual]
Reimplemented in SUS_SmartPlayer, wordSmartPlayer, and smartPlayer2.
Definition at line 112 of file Smart_Player.h.
                                                                                                                             {
        if (is_win(b, ai, N)) return 1000 + depth; // prefer faster win
        if (is_win(b, opp, N)) return -1000 - depth; // prefer slower loss
        if (is_draw(b, N)) return 0;
        if (depth == 0) return evaluate_board(b, ai, opp, N);
        int rows = b.size();
        int cols = b[0].size();
        if (maximizingPlayer) {
            int best = numeric_limits<int>::min();
            for (int i = 0; i < rows; i++)
                for (int j = 0; j < cols; j++)
                    if (b[i][j] == '.') {
                        b[i][j] = ai;
                        int val = minimax(b, false, ai, opp, alpha, beta, depth - 1, N);
                        b[i][j] = '.';
                        best = max(best, val);
                        alpha = max(alpha, best);
                        if (beta <= alpha) return best;
                    }
            return best;
        } else {
            int best = numeric_limits<int>::max();
            for (int i = 0; i < rows; i++)
                for (int j = 0; j < cols; j++)
                    if (b[i][j] == '.') {
                        b[i][j] = opp;
                        int val = minimax(b, true, ai, opp, alpha, beta, depth - 1, N);
                        b[i][j] = '.';
                        best = min(best, val);
                        beta = min(beta, best);
                        if (beta <= alpha) return best;
                    }
            return best;
        }
    }
References smartPlayer< T >::evaluate_board(), smartPlayer< T >::is_draw(), smartPlayer< T >::is_win(), smartPlayer< T >::minimax(), and Player< T >::Player().
Referenced by smartPlayer< T >::calculateMove(), and smartPlayer< T >::minimax().
The documentation for this class was generated from the following file:
include/Smart_Player.h