X_O_5x5_UI Class Reference
#include <X_O_5x5.h>
Public Member Functions
X_O_5x5_UI ()
~X_O_5x5_UI ()
Player< char > * create_player (string &name, char symbol, PlayerType type)
virtual Move< char > * get_move (Player< char > *player)
Ask the user (or AI) to make a move.
Public Member Functions inherited from UI< char >
UI (int cell_display_width=3)
Construct the UI and display a welcome message.
UI (string message, int cell_display_width)
Construct the UI and display a welcome message.
virtual ~UI ()
virtual void display_message (string message)
Display any message to the user.
virtual Player< char > ** setup_players ()
Set up players for the game.
virtual Player< char > * create_player (string &name, char symbol, PlayerType type)
Create a player object based on input name, symbol, and type.
virtual void display_board_matrix (const vector< vector< char > > &matrix) const
Display the current board matrix in formatted form.
Additional Inherited Members
Protected Member Functions inherited from UI< char >
virtual string get_player_name (string player_label)
Ask the user for the player's name.
virtual PlayerType get_player_type_choice (string player_label, const vector< string > &options)
Ask the user to choose the player type from a list.
Protected Attributes inherited from UI< char >
int cell_width
Width of each displayed board cell.
Detailed Description
Definition at line 34 of file X_O_5x5.h.
Constructor & Destructor Documentation
X_O_5x5_UI()
X_O_5x5_UI::X_O_5x5_UI ()
Definition at line 131 of file X_O_5x5.cpp.
: UI<char>("Weclome to FCAI X-O 5X5 Game by Hazem", 3) {}
~X_O_5x5_UI()
X_O_5x5_UI::~X_O_5x5_UI () [inline]
Definition at line 37 of file X_O_5x5.h.
{};
Member Function Documentation
create_player()
Player< char > * X_O_5x5_UI::create_player (string & name, char symbol, PlayerType type)
Definition at line 133 of file X_O_5x5.cpp.
                                                                                  {
    // Create player based on type
    cout << "Creating " << (type == PlayerType::HUMAN ? "human" : "computer")
        << " player: " << name << " (" << symbol << ")\n";
    return new Player<char>(name, symbol, type);
}
References HUMAN.
get_move()
Move< char > * X_O_5x5_UI::get_move (Player< char > *) [virtual]
Ask the user (or AI) to make a move.
Implements UI< char >.
Definition at line 141 of file X_O_5x5.cpp.
                                                     {
    int x, y;
    if (player->get_type() == PlayerType::HUMAN) {
        cout << "\nPlease enter your move x and y (0 to 4): ";
        cin >> x >> y;
    }
    else if (player->get_type() == PlayerType::COMPUTER) {
        x = rand() % player->get_board_ptr()->get_rows();
        y = rand() % player->get_board_ptr()->get_columns();
    }
    return new Move<char>(x, y, player->get_symbol());
}
References COMPUTER, Player< T >::get_board_ptr(), Player< T >::get_symbol(), Player< T >::get_type(), and HUMAN.
The documentation for this class was generated from the following files:
include/X_O_5x5.h
src/X_O_5x5.cpp