Ultimate_XO_UI Class Reference
#include <Ultimate_Tic_Tac_Toe.h>
Public Member Functions
Ultimate_XO_UI ()
Constructs an XO_UI object.
virtual ~Ultimate_XO_UI ()
Destructor for XO_UI.
Player< char > ** setup_players ()
Set up players for the game.
Player< char > * create_player (string &name, char symbol, PlayerType type)
Creates a player of the specified type.
virtual Move< char > * get_move (Player< char > *player)
Retrieves the next move from a player.
Public Member Functions inherited from UI< char >
UI (int cell_display_width=3)
Construct the UI and display a welcome message.
UI (string message, int cell_display_width)
Construct the UI and display a welcome message.
virtual ~UI ()
virtual void display_message (string message)
Display any message to the user.
virtual Player< char > * create_player (string &name, char symbol, PlayerType type)
Create a player object based on input name, symbol, and type.
virtual void display_board_matrix (const vector< vector< char > > &matrix) const
Display the current board matrix in formatted form.
Additional Inherited Members
Protected Member Functions inherited from UI< char >
virtual string get_player_name (string player_label)
Ask the user for the player's name.
virtual PlayerType get_player_type_choice (string player_label, const vector< string > &options)
Ask the user to choose the player type from a list.
Protected Attributes inherited from UI< char >
int cell_width
Width of each displayed board cell.
Detailed Description
Definition at line 107 of file Ultimate_Tic_Tac_Toe.h.
Constructor & Destructor Documentation
Ultimate_XO_UI()
Ultimate_XO_UI::Ultimate_XO_UI ()
Constructs an XO_UI object.
Initializes the base UI<char> class with the welcome message "FCAI X-O".
Definition at line 125 of file Ultimate_Tic_Tac_Toe.cpp.
: UI<char>("Welcome to FCAI Ultimate Tic Tac Toe Game by Abdelhamid ElRashidy", 3) {}
~Ultimate_XO_UI()
virtual Ultimate_XO_UI::~Ultimate_XO_UI () [inline], [virtual]
Destructor for XO_UI.
Definition at line 120 of file Ultimate_Tic_Tac_Toe.h.
{};
Member Function Documentation
create_player()
Player< char > * Ultimate_XO_UI::create_player (string & name, char symbol, PlayerType type)
Creates a player of the specified type.
Parameters
name Name of the player.
symbol Character symbol ('X' or 'O') assigned to the player.
type The type of the player (Human or Computer).
Returns
Pointer to the newly created Player<char> instance.
Definition at line 142 of file Ultimate_Tic_Tac_Toe.cpp.
                                                                                      {
    cout << "Creating " << (type == PlayerType::HUMAN ? "human" : "computer")
        << " player: " << name << " (" << symbol << ")\n";
    return new Player<char>(name, symbol, type);
}
References HUMAN.
Referenced by setup_players().
get_move()
Move< char > * Ultimate_XO_UI::get_move (Player< char > * player) [virtual]
Retrieves the next move from a player.
Parameters
player Pointer to the player whose move is being requested.
Returns
A pointer to a new Move<char> object representing the player's action.
Implements UI< char >.
Definition at line 150 of file Ultimate_Tic_Tac_Toe.cpp.
                                                         {
    int x, y;
    if (player->get_type() == PlayerType::HUMAN) {
        cout << "\nPlease enter your move x and y (0 to 8): ";
        cin >> x >> y;
    }
    else if (player->get_type() == PlayerType::COMPUTER) {
        x = rand() % player->get_board_ptr()->get_rows();
        y = rand() % player->get_board_ptr()->get_columns();
    }
    return new Move<char>(x, y, player->get_symbol());
}
References COMPUTER, Player< T >::get_board_ptr(), Player< T >::get_symbol(), Player< T >::get_type(), and HUMAN.
setup_players()
Player< char > ** Ultimate_XO_UI::setup_players () [virtual]
Set up players for the game.
Default implementation of setting up two players.
Reimplemented from UI< char >.
Definition at line 127 of file Ultimate_Tic_Tac_Toe.cpp.
                                             {
    Player<char>** p = new Player<char>*[2];
    string n1, n2;
    cout << "Enter Player 1 name (X): ";
    getline(cin >> ws, n1);
    p[0] = create_player(n1, 'X', get_player_type_choice("Player1", {"Human", "Computer"}));
    cout << "Enter Player 2 name (O): ";
    getline(cin >> ws, n2);
    p[1] = create_player(n2, 'O', get_player_type_choice("Player2", {"Human", "Computer"}));
    return p;
}
References create_player(), and UI< char >::get_player_type_choice().
The documentation for this class was generated from the following files:
include/Ultimate_Tic_Tac_Toe.h
src/Ultimate_Tic_Tac_Toe.cpp