wordSmartPlayer Class Reference
Public Member Functions
wordSmartPlayer (string n, char s, PlayerType t, const string &dictFile)
pair< pair< int, int >, int > calculateMove2 ()
Public Member Functions inherited from smartPlayer< char >
smartPlayer (string n, char s, PlayerType t)
virtual pair< int, int > calculateMove ()
virtual ~smartPlayer ()
Public Member Functions inherited from Player< T >
Player (string n, T s, PlayerType t)
Construct a player with name, symbol, and type.
virtual ~Player ()
string get_name () const
Get the player's name.
PlayerType get_type () const
Get player type (e.g., 'H' or 'C').
T get_symbol () const
Get the player's symbol.
Board< T > * get_board_ptr () const
Get a pointer to the game board.
void set_board_ptr (Board< T > *b)
Assign the board pointer for the player.
Protected Member Functions
void loadDictionary (const string &filename)
virtual bool is_win (const vector< vector< char > > &b, char s, int N=3) const override
bool is_valid_word (const string &s) const
virtual int evaluate_board (const vector< vector< char > > &b, char ai, char opp, int N=3) const override
int score_line (const vector< vector< char > > &b, const string &word, char symbol) const
int minimax (vector< vector< char > > &b, bool maximizingPlayer, char ai, char opp, int alpha, int beta, int depth, int N=3)
Protected Member Functions inherited from smartPlayer< char >
virtual char get_opponent_symbol () const
virtual bool is_draw (const vector< vector< char > > &b, int N=3) const
Protected Attributes
vector< string > dictionary
vector< char > possibleLetters
unsigned long node_counter = 0
const unsigned long MAX_NODES = 10000
Protected Attributes inherited from Player< T >
string name
Player name.
PlayerType type
Player type (e.g., HUMAN or COMPUTER)
T symbol
Players symbol on board.
Board< T > * boardPtr
Pointer to the game board.
Detailed Description
Definition at line 19 of file Words_XO.cpp.
Constructor & Destructor Documentation
wordSmartPlayer()
wordSmartPlayer::wordSmartPlayer (string n, char s, PlayerType t, const string & dictFile) [inline]
Definition at line 30 of file Words_XO.cpp.
            : smartPlayer<char>(n, s, t)
    {
        loadDictionary(dictFile);
    }
References loadDictionary().
Member Function Documentation
calculateMove2()
pair< pair< int, int >, int > wordSmartPlayer::calculateMove2 () [inline]
Definition at line 207 of file Words_XO.cpp.
                                              {
        Board<char>* board_ptr = this->get_board_ptr();
        if (!board_ptr) throw runtime_error("Board not assigned to player!");
        auto tempBoard = board_ptr->get_board_matrix();
        int rows = tempBoard.size();
        int cols = tempBoard[0].size();
        int bestVal = numeric_limits<int>::min();
        int bestX = -1, bestY = -1;
        char bestc = '#';
        char ai = this->get_symbol();
        char opp = get_opponent_symbol();
        // search configuration
        int maxDepth = 1; // can drop to 1 if slow; raise if you add pruning/time limits
        node_counter = 0; // reset before search
        // If possibleLetters empty (shouldn't be), fall back
        if (possibleLetters.empty()) possibleLetters = LETTERS;
        for (int i = 0; i < rows; ++i) {
            for (int j = 0; j < cols; ++j) {
                if (tempBoard[i][j] != '.') continue;
                for (char c : possibleLetters) {
                    tempBoard[i][j] = c;
                    int moveVal = minimax(tempBoard, false, ai, opp,
                                          numeric_limits<int>::min(),
                                          numeric_limits<int>::max(),
                                          maxDepth);
                    tempBoard[i][j] = '.';
                    if (moveVal > bestVal) {
                        bestVal = moveVal;
                        bestX = i;
                        bestY = j;
                        bestc = c;
                    }
                    // optional: if node budget reached, break entirely
                    if (node_counter > MAX_NODES) break;
                }
                if (node_counter > MAX_NODES) break;
            }
            if (node_counter > MAX_NODES) break;
        }
        // Debug: print nodes visited (remove in production)
        // cerr << "AI nodes visited: " << node_counter << ", bestVal=" << bestVal << "\n";
        return {{bestX, bestY}, bestc};
    }
References Player< T >::get_board_ptr(), smartPlayer< char >::get_opponent_symbol(), Player< T >::get_symbol(), LETTERS, MAX_NODES, minimax(), node_counter, Player< T >::Player(), and possibleLetters.
evaluate_board()
virtual int wordSmartPlayer::evaluate_board (const vector< vector< char > > & b, char ai, char opp, int N = 3) const [inline], [override], [protected], [virtual]
Reimplemented from smartPlayer< char >.
Definition at line 102 of file Words_XO.cpp.
                                                                                                           {
        // Scoring: more letters forming a prefix of any word = higher score
        int score = 0;
        for (auto& w : dictionary) {
            score += score_line(b, w, ai);
            score -= score_line(b, w, opp);
        }
        return score;
    }
References dictionary, and score_line().
Referenced by minimax().
is_valid_word()
bool wordSmartPlayer::is_valid_word (const string & s) const [inline], [protected]
Definition at line 91 of file Words_XO.cpp.
                                              {
        // remove '.' (empty cells)
        string cleaned;
        for (char c : s)
            if (c != '.') cleaned += c;
        if (cleaned.size() < 3) return false;
        return find(dictionary.begin(), dictionary.end(), cleaned) != dictionary.end();
    }
References dictionary.
Referenced by is_win().
is_win()
virtual bool wordSmartPlayer::is_win (const vector< vector< char > > & b, char s, int N = 3) const [inline], [override], [protected], [virtual]
Reimplemented from smartPlayer< char >.
Definition at line 56 of file Words_XO.cpp.
                                                                                         {
        int R = b.size();
        int C = b[0].size();
        // Check all rows
        for (int i = 0; i < R; i++) {
            string row;
            for (int j = 0; j < C; j++) row += b[i][j];
            if (is_valid_word(row)) return true;
        }
        // Check all columns
        for (int j = 0; j < C; j++) {
            string col;
            for (int i = 0; i < R; i++) col += b[i][j];
            if (is_valid_word(col)) return true;
        }
        // Check TL-BR diagonal
        if (R == C) {
            string diag;
            for (int k = 0; k < R; k++) diag += b[k][k];
            if (is_valid_word(diag)) return true;
        }
        // Check TR-BL diagonal
        if (R == C) {
            string diag;
            for (int k = 0; k < R; k++) diag += b[k][C - 1 - k];
            if (is_valid_word(diag)) return true;
        }
        return false;
    }
References is_valid_word().
Referenced by minimax().
loadDictionary()
void wordSmartPlayer::loadDictionary (const string & filename) [inline], [protected]
Definition at line 37 of file Words_XO.cpp.
                                                {
        ifstream in(filename);
        string w;
        unordered_set<char> letters;
        while (in >> w) {
            // convert to uppercase and keep only alphabetic characters
            for (char &ch : w) ch = toupper(static_cast<unsigned char>(ch));
            dictionary.push_back(w);
            for (char ch : w) if (isalpha((unsigned char)ch)) letters.insert(ch);
        }
        // build possibleLetters vector from set (stable order not required)
        possibleLetters.assign(letters.begin(), letters.end());
        // if dictionary is empty for whatever reason, fall back to full alphabet
        if (possibleLetters.empty()) {
            possibleLetters = LETTERS;
        }
    }
References dictionary, LETTERS, and possibleLetters.
Referenced by wordSmartPlayer().
minimax()
int wordSmartPlayer::minimax (vector< vector< char > > & b, bool maximizingPlayer, char ai, char opp, int alpha, int beta, int depth, int N = 3) [inline], [protected], [virtual]
Reimplemented from smartPlayer< char >.
Definition at line 137 of file Words_XO.cpp.
{
    // node accounting
    ++node_counter;
    if (node_counter > MAX_NODES) {
        // abort search early: return heuristic evaluation to let caller use partial result
        return evaluate_board(b, ai, opp, N);
    }
    if (is_win(b, ai, N)) return 1000 + depth; // prefer faster win
    if (is_win(b, opp, N)) return -1000 - depth; // prefer slower loss
    if (is_draw(b, N)) return 0;
    if (depth == 0) return evaluate_board(b, ai, opp, N);
    int rows = b.size();
    int cols = b[0].size();
    if (maximizingPlayer) {
        int best = numeric_limits<int>::min();
        for (int i = 0; i < rows; ++i) {
            for (int j = 0; j < cols; ++j) {
                if (b[i][j] != '.') continue;
                for (char c : possibleLetters) {
                    b[i][j] = c;
                    int val = minimax(b, false, ai, opp, alpha, beta, depth - 1, N);
                    b[i][j] = '.';
                    if (val > best) best = val;
                    if (best > alpha) alpha = best;
                    if (beta <= alpha) {
                        // pruning - break out early
                        goto OUT_MAX_LOOP;
                    }
                    // early node budget check
                    if (node_counter > MAX_NODES) goto OUT_MAX_LOOP;
                }
            }
        }
OUT_MAX_LOOP:
        return best;
    } else {
        int best = numeric_limits<int>::max();
        for (int i = 0; i < rows; ++i) {
            for (int j = 0; j < cols; ++j) {
                if (b[i][j] != '.') continue;
                for (char c : possibleLetters) {
                    b[i][j] = c;
                    int val = minimax(b, true, ai, opp, alpha, beta, depth - 1, N);
                    b[i][j] = '.';
                    if (val < best) best = val;
                    if (best < beta) beta = best;
                    if (beta <= alpha) {
                        goto OUT_MIN_LOOP;
                    }
                    if (node_counter > MAX_NODES) goto OUT_MIN_LOOP;
                }
            }
        }
OUT_MIN_LOOP:
        return best;
    }
}
References evaluate_board(), smartPlayer< char >::is_draw(), is_win(), MAX_NODES, minimax(), node_counter, Player< T >::Player(), and possibleLetters.
Referenced by calculateMove2(), and minimax().
score_line()
int wordSmartPlayer::score_line (const vector< vector< char > > & b, const string & word, char symbol) const [inline], [protected]
Definition at line 114 of file Words_XO.cpp.
                                                                                         {
        int R = b.size();
        int C = b[0].size();
        int score = 0;
        // Example scoring: +10 for correct letter in position, +3 for empty, -5 otherwise
        for (int i = 0; i < R; i++)
            for (int j = 0; j < C; j++) {
                // Check horizontal word match possibility
                if (j + word.size() <= C) {
                    int s = 0;
                    for (int k = 0; k < word.size(); k++) {
                        if (b[i][j+k] == word[k]) s += 10;
                        else if (b[i][j+k] == '.') s += 3;
                        else { s = -50; break; }
                    }
                    score += s;
                }
            }
        return score;
    }
Referenced by evaluate_board().
Member Data Documentation
dictionary
vector<string> wordSmartPlayer::dictionary [protected]
Definition at line 23 of file Words_XO.cpp.
Referenced by evaluate_board(), is_valid_word(), and loadDictionary().
MAX_NODES
const unsigned long wordSmartPlayer::MAX_NODES = 10000 [protected]
Definition at line 26 of file Words_XO.cpp.
Referenced by calculateMove2(), and minimax().
node_counter
unsigned long wordSmartPlayer::node_counter = 0 [mutable], [protected]
Definition at line 25 of file Words_XO.cpp.
Referenced by calculateMove2(), and minimax().
possibleLetters
vector<char> wordSmartPlayer::possibleLetters [protected]
Definition at line 24 of file Words_XO.cpp.
Referenced by calculateMove2(), loadDictionary(), and minimax().
The documentation for this class was generated from the following file:
src/Words_XO.cpp