Board< T > Class Template Reference
Base template for any board used in board games.
#include <BoardGame_Classes.h>
Public Member Functions
Board (int rows, int columns)
Construct a board with given dimensions.
virtual ~Board ()
Virtual destructor. Frees allocated board memory.
virtual bool update_board (Move< T > *move)=0
Update the board with a new move.
virtual bool is_win (Player< T > *)=0
Check if a player has won.
virtual bool is_lose (Player< T > *)=0
Check if a player has lost.
virtual bool is_draw (Player< T > *)=0
Check if the game ended in a draw.
virtual bool game_is_over (Player< T > *)=0
Check if the game is over.
vector< vector< T > > get_board_matrix () const
Return a copy of the current board as a 2D vector.
int get_rows () const
Get number of rows.
int get_columns () const
Get number of columns.
int get_n_moves () const
Get number of moves.
T get_cell (int x, int y)
Return content of cell x, y in current board.
Protected Attributes
int rows
Number of rows.
int columns
Number of columns.
vector< vector< T > > board
2D vector for the board
int n_moves = 0
Number of moves made.
Detailed Description
template<typename T>
class Board< T >
Base template for any board used in board games.
Pure virtual function to undo the previous move played during backtracking algorithm. Must be implemented by derived classes.
Template Parameters
T Type of the elements stored on the board (e.g., char, int, string).
Provides core data (rows, columns, matrix) and virtual methods to be implemented by specific games like Tic-Tac-Toe, Connect4, etc.
Note
The protocol to inform the update_board function in is an undo move is to place a blank_symbol in
Constructor & Destructor Documentation
Board()
template<typename T >
Board< T >::Board (int rows, int columns) [inline]
Construct a board with given dimensions.
Definition at line 57 of file BoardGame_Classes.h.
        : rows(rows), columns(columns), board(rows, vector<T>(columns)) {}
~Board()
template<typename T >
virtual Board< T >::~Board () [inline], [virtual]
Virtual destructor. Frees allocated board memory.
Definition at line 63 of file BoardGame_Classes.h.
{}
Member Function Documentation
game_is_over()
template<typename T >
virtual bool Board< T >::game_is_over (Player< T > *) [pure virtual]
Check if the game is over.
Implemented in Four_Four_XO_Board, Diamond_Tic_Tac_Toe_Board, Four_in_a_row_Board, Infinity_X_O_Board, MEMORY_TIC_TAC_TOE_Board, Misere_Tic_Tac_Toe_board, Numerical_X_O_Board, Obstacles_XO_Board, Pyramid_XO_Board, SUS_Board, mainBoard, Ultimate_XO_Board, Word_XO_Board, and X_O_5x5_Board.
get_board_matrix()
template<typename T >
vector< vector< T > > Board< T >::get_board_matrix () const [inline]
Return a copy of the current board as a 2D vector.
Definition at line 87 of file BoardGame_Classes.h.
                                               {
        return board;
    }
References Board< T >::board.
get_cell()
template<typename T >
T Board< T >::get_cell (int x, int y) [inline]
Return content of cell x, y in current board.
Definition at line 101 of file BoardGame_Classes.h.
                             {
        return board[x][y];
    }
References Board< T >::board.
get_columns()
template<typename T >
int Board< T >::get_columns () const [inline]
Get number of columns.
Definition at line 95 of file BoardGame_Classes.h.
{ return columns; }
References Board< T >::columns.
get_n_moves()
template<typename T >
int Board< T >::get_n_moves () const [inline]
Get number of moves.
Definition at line 98 of file BoardGame_Classes.h.
{ return n_moves; }
References Board< T >::n_moves.
get_rows()
template<typename T >
int Board< T >::get_rows () const [inline]
Get number of rows.
Definition at line 92 of file BoardGame_Classes.h.
{ return rows; }
References Board< T >::rows.
is_draw()
template<typename T >
virtual bool Board< T >::is_draw (Player< T > *) [pure virtual]
Check if the game ended in a draw.
Implemented in Four_Four_XO_Board, Diamond_Tic_Tac_Toe_Board, Four_in_a_row_Board, Infinity_X_O_Board, MEMORY_TIC_TAC_TOE_Board, Misere_Tic_Tac_Toe_board, Numerical_X_O_Board, Obstacles_XO_Board, Pyramid_XO_Board, SUS_Board, mainBoard, Ultimate_XO_Board, Word_XO_Board, and X_O_5x5_Board.
Referenced by Ultimate_XO_Board::is_draw().
is_lose()
template<typename T >
virtual bool Board< T >::is_lose (Player< T > *) [pure virtual]
Check if a player has lost.
Implemented in Diamond_Tic_Tac_Toe_Board, Four_in_a_row_Board, Four_Four_XO_Board, Infinity_X_O_Board, MEMORY_TIC_TAC_TOE_Board, Numerical_X_O_Board, Obstacles_XO_Board, Pyramid_XO_Board, SUS_Board, mainBoard, Ultimate_XO_Board, Word_XO_Board, Misere_Tic_Tac_Toe_board, and X_O_5x5_Board.
is_win()
template<typename T >
virtual bool Board< T >::is_win (Player< T > *) [pure virtual]
Check if a player has won.
Implemented in Four_Four_XO_Board, Misere_Tic_Tac_Toe_board, Diamond_Tic_Tac_Toe_Board, Four_in_a_row_Board, Infinity_X_O_Board, MEMORY_TIC_TAC_TOE_Board, Numerical_X_O_Board, Obstacles_XO_Board, Pyramid_XO_Board, SUS_Board, mainBoard, Ultimate_XO_Board, Word_XO_Board, and X_O_5x5_Board.
Referenced by Ultimate_XO_Board::is_win().
update_board()
template<typename T >
virtual bool Board< T >::update_board (Move< T > * move) [pure virtual]
Update the board with a new move.
Parameters
move The move object containing position and symbol.
Returns
true if the move is valid and applied, false otherwise.
Implemented in Diamond_Tic_Tac_Toe_Board, Four_in_a_row_Board, Four_Four_XO_Board, Infinity_X_O_Board, MEMORY_TIC_TAC_TOE_Board, Misere_Tic_Tac_Toe_board, Numerical_X_O_Board, Obstacles_XO_Board, Pyramid_XO_Board, SUS_Board, mainBoard, Ultimate_XO_Board, Word_XO_Board, and X_O_5x5_Board.
Referenced by Ultimate_XO_Board::update_board().
Member Data Documentation
board
template<typename T >
vector<vector<T> > Board< T >::board [protected]
2D vector for the board
Definition at line 50 of file BoardGame_Classes.h.
Referenced by Board< T >::get_board_matrix(), and Board< T >::get_cell().
columns
template<typename T >
int Board< T >::columns [protected]
Number of columns.
Definition at line 49 of file BoardGame_Classes.h.
Referenced by Board< T >::get_columns().
n_moves
template<typename T >
int Board< T >::n_moves = 0 [protected]
Number of moves made.
Definition at line 51 of file BoardGame_Classes.h.
Referenced by Board< T >::get_n_moves().
rows
template<typename T >
int Board< T >::rows [protected]
Number of rows.
Definition at line 48 of file BoardGame_Classes.h.
Referenced by Board< T >::get_rows().
The documentation for this class was generated from the following files:
include/BoardGame_Classes.h
include/AiPlayer.h