Four_in_a_row_Board Class Reference
Represents the Tic-Tac-Toe game board.
#include <Four-in-a-row.h>
Public Member Functions
Four_in_a_row_Board ()
Default constructor that initializes a 3x3 X-O board.
bool update_board (Move< char > *move)
Updates the board with a player's move.
bool is_win (Player< char > *player)
Checks if the given player has won the game.
bool is_lose (Player< char > *)
Checks if the given player has lost the game.
bool is_draw (Player< char > *player)
Checks if the game has ended in a draw.
bool game_is_over (Player< char > *player)
Determines if the game is over (win or draw).
Public Member Functions inherited from Board< char >
Board (int rows, int columns)
Construct a board with given dimensions.
virtual ~Board ()
Virtual destructor. Frees allocated board memory.
vector< vector< char > > get_board_matrix () const
Return a copy of the current board as a 2D vector.
int get_rows () const
Get number of rows.
int get_columns () const
Get number of columns.
int get_n_moves () const
Get number of moves.
char get_cell (int x, int y)
Return content of cell x, y in current board.
Private Attributes
char blank_symbol = '.'
Character used to represent an empty cell on the board.
Additional Inherited Members
Protected Attributes inherited from Board< char >
int rows
Number of rows.
int columns
Number of columns.
vector< vector< char > > board
2D vector for the board
int n_moves
Number of moves made.
Detailed Description
Represents the Tic-Tac-Toe game board.
This class inherits from the generic Board<char> class and implements the specific logic required for the Tic-Tac-Toe (X-O) game, including move updates, win/draw detection, and display functions.
See also
Board
Definition at line 29 of file Four-in-a-row.h.
Constructor & Destructor Documentation
Four_in_a_row_Board()
Four_in_a_row_Board::Four_in_a_row_Board ()
Default constructor that initializes a 3x3 X-O board.
Definition at line 101 of file Four-in-a-row.cpp.
                                         : Board(6, 7) {
    // Initialize all cells with blank_symbol
    for (auto& row : board)
        for (auto& cell : row)
            cell = blank_symbol;
}
References blank_symbol, and Board< char >::board.
Member Function Documentation
game_is_over()
bool Four_in_a_row_Board::game_is_over (Player< char > * player) [virtual]
Determines if the game is over (win or draw).
Parameters
player Pointer to the playerended, to evaluate.
Returns
true if the game has false otherwise.
Implements Board< char >.
Definition at line 172 of file Four-in-a-row.cpp.
                                                           {
    return (is_win(player) || is_draw(player));
}
References is_draw(), and is_win().
is_draw()
bool Four_in_a_row_Board::is_draw (Player< char > * player) [virtual]
Checks if the game has ended in a draw.
Parameters
player Pointer to the player being checked.
Returns
true if all cells are filled and no player has won, false otherwise.
Implements Board< char >.
Definition at line 167 of file Four-in-a-row.cpp.
                                                      {
    return (n_moves == rows * columns && !is_win(player));
}
References Board< char >::columns, is_win(), Board< char >::n_moves, and Board< char >::rows.
Referenced by game_is_over().
is_lose()
bool Four_in_a_row_Board::is_lose (Player< char > *) [inline], [virtual]
Checks if the given player has lost the game.
Parameters
player Pointer to the player being checked.
Returns
Always returns false (not used in X-O logic).
Implements Board< char >.
Definition at line 58 of file Four-in-a-row.h.
{ return false; };
is_win()
bool Four_in_a_row_Board::is_win (Player< char > * player) [virtual]
Checks if the given player has won the game.
Parameters
player Pointer to the player being checked.
Returns
true if the player has a winning line, false otherwise.
Implements Board< char >.
Definition at line 127 of file Four-in-a-row.cpp.
                                                     {
    char sym = player->get_symbol();
    //Rows
    for (int i = 0; i < rows; i++) {
        for (int j = 0; j < columns - 3; j++) {
            if (board[i][j] == sym && board[i][j+1] == sym && board[i][j+2] == sym && board[i][j+3] == sym)
                return true;
        }
    }
    // Columns
    for (int j = 0; j < columns; j++) {
        for (int i = 0; i < rows - 3; i++) {
            if (board[i][j] == sym && board[i+1][j] == sym && board[i+2][j] == sym && board[i+3][j] == sym)
                return true;
        }
    }
    // Main diagonal
    for (int i = 0; i < rows - 3; i++) {
        for (int j = 0; j < columns - 3; j++) {
            if (board[i][j] == sym && board[i+1][j+1] == sym && board[i+2][j+2] == sym && board[i+3][j+3] == sym)
                return true;
        }
    }
    // Anti diagonal
    for (int i = 0; i < rows - 3; i++) {
        for (int j = 3; j < columns; j++) {
            if (board[i][j] == sym && board[i+1][j-1] == sym && board[i+2][j-2] == sym && board[i+3][j-3] == sym)
                return true;
        }
    }
    return false;
}
References Board< char >::board, Board< char >::columns, Player< T >::get_symbol(), and Board< char >::rows.
Referenced by game_is_over(), and is_draw().
update_board()
bool Four_in_a_row_Board::update_board (Move< char > * move) [virtual]
Updates the board with a player's move.
Parameters
move Pointer to a Move<char> object containing move coordinates and symbol.
Returns
true if the move is valid and successfully applied, false otherwise.
Implements Board< char >.
Definition at line 108 of file Four-in-a-row.cpp.
                                                       {
    int col = move->get_y();
    char sym = move->get_symbol();
    if (col < 0 || col >= columns)
        return false;
    // drop piece to low position
    for (int r = rows - 1; r >= 0; r--) {
        if (board[r][col] == blank_symbol) {
            board[r][col] = sym;
            n_moves++;
            return true;
        }
    }
    return false; // column full
}
References blank_symbol, Board< char >::board, Board< char >::columns, Player< T >::get_symbol(), Board< char >::n_moves, and Board< char >::rows.
Member Data Documentation
blank_symbol
char Four_in_a_row_Board::blank_symbol = '.' [private]
Character used to represent an empty cell on the board.
Definition at line 31 of file Four-in-a-row.h.
Referenced by Four_in_a_row_Board(), and update_board().
The documentation for this class was generated from the following files:
include/Four-in-a-row.h
src/Four-in-a-row.cpp