Obstacles_XO_Board Class Reference
#include <Obstacles_XO.h>
Public Member Functions
Obstacles_XO_Board ()
Symbol for the obstacles.
bool update_board (Move< char > *move)
Updates the board with a player's move.
bool is_win (Player< char > *player)
Checks if the given player has won the game.
bool is_lose (Player< char > *)
Checks if the given player has lost the game.
bool is_draw (Player< char > *player)
Checks if the game has ended in a draw.
bool game_is_over (Player< char > *player)
Determines if the game is over (win or draw).
virtual ~Obstacles_XO_Board ()
Public Member Functions inherited from Board< char >
Board (int rows, int columns)
Construct a board with given dimensions.
virtual ~Board ()
Virtual destructor. Frees allocated board memory.
vector< vector< char > > get_board_matrix () const
Return a copy of the current board as a 2D vector.
int get_rows () const
Get number of rows.
int get_columns () const
Get number of columns.
int get_n_moves () const
Get number of moves.
char get_cell (int x, int y)
Return content of cell x, y in current board.
Private Attributes
char obstacle_symbol = '#'
Additional Inherited Members
Protected Attributes inherited from Board< char >
int rows
Number of rows.
int columns
Number of columns.
vector< vector< char > > board
2D vector for the board
int n_moves
Number of moves made.
Detailed Description
Definition at line 11 of file Obstacles_XO.h.
Constructor & Destructor Documentation
Obstacles_XO_Board()
Obstacles_XO_Board::Obstacles_XO_Board ()
Symbol for the obstacles.
Constructor: Initializes the Diamond board in a diamond shape.
Definition at line 8 of file Obstacles_XO.cpp.
                                       : Board<char>(6, 6) {
    for (int i = 0; i < rows; i++) {
        for (int j = 0; j < columns; j++) {
            board[i][j] = '.';
        }
    }
}
References Board< char >::board, Board< char >::columns, and Board< char >::rows.
~Obstacles_XO_Board()
virtual Obstacles_XO_Board::~Obstacles_XO_Board () [inline], [virtual]
Definition at line 59 of file Obstacles_XO.h.
{};
Member Function Documentation
game_is_over()
bool Obstacles_XO_Board::game_is_over (Player< char > * player) [virtual]
Determines if the game is over (win or draw).
Parameters
player Pointer to the playerended, to evaluate.
Returns
true if the game has false otherwise.
Implements Board< char >.
Definition at line 115 of file Obstacles_XO.cpp.
                                                          {
    return is_win(player) || is_draw(player);
}
References is_draw(), and is_win().
is_draw()
bool Obstacles_XO_Board::is_draw (Player< char > * player) [virtual]
Checks if the game has ended in a draw.
Parameters
player Pointer to the player being checked.
Returns
true if all cells are filled and no player has won, false otherwise.
Implements Board< char >.
Definition at line 110 of file Obstacles_XO.cpp.
                                                     {
    // Draw if board is full (36 moves including obstacles) and no winner
    return (n_moves >= 36 && !is_win(player));
}
References is_win(), and Board< char >::n_moves.
Referenced by game_is_over().
is_lose()
bool Obstacles_XO_Board::is_lose (Player< char > *) [inline], [virtual]
Checks if the given player has lost the game.
Parameters
player Pointer to the player being checked.
Returns
Always returns false (not used in X-O logic).
Implements Board< char >.
Definition at line 42 of file Obstacles_XO.h.
{ return false; };
is_win()
bool Obstacles_XO_Board::is_win (Player< char > * player) [virtual]
Checks if the given player has won the game.
Parameters
player Pointer to the player being checked.
Returns
true if the player has a winning line, false otherwise.
Implements Board< char >.
Definition at line 62 of file Obstacles_XO.cpp.
                                                    {
    char sym = player->get_symbol();
    // Check for 4 consecutive symbols in any direction
    for (int i = 0; i < rows; i++) {
        for (int j = 0; j < columns; j++) {
            
            // Only verify if the current cell belongs to the player
            if (board[i][j] != sym) continue;
            // 1. Check Horizontal (Right)
            // Ensure we have room for 3 more cells to the right
            if (j + 3 < columns &&
                board[i][j+1] == sym &&
                board[i][j+2] == sym &&
                board[i][j+3] == sym) {
                return true;
            }
            // 2. Check Vertical (Down)
            // Ensure we have room for 3 more cells downwards
            if (i + 3 < rows &&
                board[i+1][j] == sym &&
                board[i+2][j] == sym &&
                board[i+3][j] == sym) {
                return true;
            }
            // 3. Check Diagonal (Down-Right)
            if (i + 3 < rows && j + 3 < columns &&
                board[i+1][j+1] == sym &&
                board[i+2][j+2] == sym &&
                board[i+3][j+3] == sym) {
                return true;
            }
            // 4. Check Anti-Diagonal (Down-Left)
            if (i + 3 < rows && j - 3 >= 0 &&
                board[i+1][j-1] == sym &&
                board[i+2][j-2] == sym &&
                board[i+3][j-3] == sym) {
                return true;
            }
        }
    }
    return false;
}
References Board< char >::board, Board< char >::columns, Player< T >::get_symbol(), and Board< char >::rows.
Referenced by game_is_over(), and is_draw().
update_board()
bool Obstacles_XO_Board::update_board (Move< char > * move) [virtual]
Updates the board with a player's move.
Parameters
move Pointer to a Move<char> object containing move coordinates and symbol.
Returns
true if the move is valid and successfully applied, false otherwise.
Implements Board< char >.
Definition at line 17 of file Obstacles_XO.cpp.
                                                      {
    int x = move->get_x();
    int y = move->get_y();
    char mark = move->get_symbol();
    // 1. Validate the move
    if (x >= 0 && x < rows && y >= 0 && y < columns &&
        board[x][y] == '.' && board[x][y] != obstacle_symbol) {
        
        if (mark == 0) { // Undo move
            n_moves--;
            board[x][y] = '.';
        }
        else {
            // Apply move
            n_moves++;
            board[x][y] = toupper(mark);
        }
        
        if (n_moves % 2 == 0) {
            int obstacles_added = 0;
            // Try to add 2 obstacles (unless board is full)
            // We loop until we place 2 obstacles or verify board is full
            int safety_counter = 0;
            while (obstacles_added < 2 && n_moves < 36 && safety_counter < 1000) {
                int r = rand() % 6;
                int c = rand() % 6;
                
                if (board[r][c] == '.') {
                    board[r][c] = obstacle_symbol;
                    n_moves++; // Count obstacle as a filled spot
                    obstacles_added++;
                }
                safety_counter++;
            }
        }
        return true;
    }
    return false;
}
References Board< char >::board, Board< char >::columns, Player< T >::get_symbol(), Board< char >::n_moves, and obstacle_symbol.
Member Data Documentation
obstacle_symbol
char Obstacles_XO_Board::obstacle_symbol = '#' [private]
Definition at line 13 of file Obstacles_XO.h.
Referenced by update_board().
The documentation for this class was generated from the following files:
include/Obstacles_XO.h
src/Obstacles_XO.cpp