Word_XO_Board Class Reference
Represents the Word Tic-Tac-Toe game board.
#include <Words_XO.h>
Public Member Functions
Word_XO_Board ()
Default constructor that initializes the Word X-O board.
bool update_board (Move< char > *move)
Updates the board with a player's move.
bool is_win (Player< char > *player)
Checks if the given player has won the game.
bool is_lose (Player< char > *)
Checks if the given player has lost the game.
bool is_draw (Player< char > *player)
Checks if the game has ended in a draw.
bool game_is_over (Player< char > *player)
Determines if the game is over (win or draw).
Public Member Functions inherited from Board< char >
Board (int rows, int columns)
Construct a board with given dimensions.
virtual ~Board ()
Virtual destructor. Frees allocated board memory.
vector< vector< char > > get_board_matrix () const
Return a copy of the current board as a 2D vector.
int get_rows () const
Get number of rows.
int get_columns () const
Get number of columns.
int get_n_moves () const
Get number of moves.
char get_cell (int x, int y)
Return content of cell x, y in current board.
Private Attributes
char blank_symbol = '.'
Character used to represent an empty cell on the board.
int counter
Counter to track the number of moves or game state progression.
Additional Inherited Members
Protected Attributes inherited from Board< char >
int rows
Number of rows.
int columns
Number of columns.
vector< vector< char > > board
2D vector for the board
int n_moves
Number of moves made.
Detailed Description
Represents the Word Tic-Tac-Toe game board.
This class inherits from the generic Board<char> class and implements the specific logic required for the Word Tic-Tac-Toe game, where players place characters to form words.
See also
Board
Definition at line 27 of file Words_XO.h.
Constructor & Destructor Documentation
Word_XO_Board()
Word_XO_Board::Word_XO_Board ()
Default constructor that initializes the Word X-O board.
Definition at line 295 of file Words_XO.cpp.
                             : Board(3, 3), counter(0) {
    // Initialize all cells with blank_symbol
    for (auto& row : board)
        for (auto& cell : row)
            cell = blank_symbol;
}
References blank_symbol, and Board< char >::board.
Member Function Documentation
game_is_over()
bool Word_XO_Board::game_is_over (Player< char > * player) [virtual]
Determines if the game is over (win or draw).
Parameters
player Pointer to the player to evaluate.
Returns
true if the game has ended, false otherwise.
Implements Board< char >.
Definition at line 357 of file Words_XO.cpp.
                                                     {
    return is_win(player) || is_draw(player);
}
References is_draw(), and is_win().
is_draw()
bool Word_XO_Board::is_draw (Player< char > * player) [virtual]
Checks if the game has ended in a draw.
Parameters
player Pointer to the player being checked.
Returns
true if the board is full and no winning word is formed, false otherwise.
Implements Board< char >.
Definition at line 353 of file Words_XO.cpp.
                                                {
    return (n_moves == 9 && !is_win(player));
}
References is_win(), and Board< char >::n_moves.
Referenced by game_is_over().
is_lose()
bool Word_XO_Board::is_lose (Player< char > *) [inline], [virtual]
Checks if the given player has lost the game.
Parameters
player Pointer to the player being checked.
Returns
Always returns false (standard implementation for this game type).
Implements Board< char >.
Definition at line 57 of file Words_XO.h.
{ return false; };
is_win()
bool Word_XO_Board::is_win (Player< char > * player) [virtual]
Checks if the given player has won the game.
Parameters
player Pointer to the player being checked.
Returns
true if the player has formed a winning word configuration, false otherwise.
Implements Board< char >.
Definition at line 327 of file Words_XO.cpp.
                                               {
    const char sym = player->get_symbol();
    auto valid = [&](char a, char b, char c) {
        if (a == '.' || b == '.' || c == '.') return false;
        string s;
        s.push_back(a);s.push_back(b);s.push_back(c);
        // see if the word is in the file
        return Check_word(s);
    };
    // Check rows and columns
    for (int i = 0; i < rows; ++i) {
        if ((valid(board[i][0], board[i][1], board[i][2])) ||
            (valid(board[0][i], board[1][i], board[2][i])))
            return true;
    }
    // Check diagonals
    if ((valid(board[0][0], board[1][1], board[2][2])) ||
        (valid(board[0][2], board[1][1], board[2][0])))
        return true;
    return false;
}
References Board< char >::board, Check_word(), Player< T >::get_symbol(), and Board< char >::rows.
Referenced by game_is_over(), and is_draw().
update_board()
bool Word_XO_Board::update_board (Move< char > * move) [virtual]
Updates the board with a player's move.
Parameters
move Pointer to a Move<char> object containing move coordinates and the character value.
Returns
true if the move is valid and successfully applied, false otherwise.
Implements Board< char >.
Definition at line 302 of file Words_XO.cpp.
                                                 {
    neMove* nm = dynamic_cast<neMove*>(move);
    if (!nm) return false;
    int x = nm->get_x();
    int y = nm->get_y();
    char val = nm->get_value();
    char ch = move->get_symbol();
    // Validate move and apply if valid
    if (!(x < 0 || x >= rows || y < 0 || y >= columns) && board[x][y] == blank_symbol) {
        n_moves++;
        board[x][y] = toupper(val);
        counter++;
        return true;
    }
    return false;
}
References blank_symbol, Board< char >::board, Board< char >::columns, counter, Player< T >::get_symbol(), Board< char >::n_moves, and Board< char >::rows.
Member Data Documentation
blank_symbol
char Word_XO_Board::blank_symbol = '.' [private]
Character used to represent an empty cell on the board.
Definition at line 29 of file Words_XO.h.
Referenced by update_board(), and Word_XO_Board().
counter
int Word_XO_Board::counter [private]
Counter to track the number of moves or game state progression.
Definition at line 30 of file Words_XO.h.
Referenced by update_board().
The documentation for this class was generated from the following files:
include/Words_XO.h
src/Words_XO.cpp