Menu Class Reference
#include <gamesMenu.h>
Public Member Functions
Menu ()
~Menu ()
void print_menu ()
void run ()
Private Attributes
map< int, GameLauncher * > options
Detailed Description
Definition at line 52 of file gamesMenu.h.
Constructor & Destructor Documentation
Menu()
Menu::Menu () [inline]
Definition at line 57 of file gamesMenu.h.
           {
        // Register for all games.
        options[1] = new XOGameLauncher<char, Infinit_XO_UI, Infinity_X_O_Board>("Infinity X-O");
        options[2] = new XOGameLauncher<char, Numerical_XO_UI, Numerical_X_O_Board>("Numerical X-O");
        options[3] = new XOGameLauncher<char, X_O_5x5_UI, X_O_5x5_Board>("5x5 X-O");
        options[4] = new XOGameLauncher<char, Misere_Tic_Tac_Toe_UI, Misere_Tic_Tac_Toe_board>("Misere Tic-Tac-Toe");
        options[5] = new XOGameLauncher<char, Four_Four_XO_UI, Four_Four_XO_Board>("Four Four X-O");
        options[6] = new XOGameLauncher<char, SUS_UI, SUS_Board>("SUS Game");
        options[7] = new XOGameLauncher<char, Pyramid_XO_UI, Pyramid_XO_Board>("Pyramid X-O");
        options[8] = new XOGameLauncher<char, Four_in_a_row_UI, Four_in_a_row_Board>("Four-in-a-row");
        options[9] = new XOGameLauncher<char, Diamond_Tic_Tac_Toe_UI, Diamond_Tic_Tac_Toe_Board>("Diamond Tic-Tac-Toe");
        options[10] = new XOGameLauncher<char, Obstacles_XO_UI, Obstacles_XO_Board>("Obstacles X-O");
        options[11] = new XOGameLauncher<char, Word_XO_UI, Word_XO_Board>("Word X-O");
        options[12] = new XOGameLauncher<char, MEMORY_TIC_TAC_TOE_UI, MEMORY_TIC_TAC_TOE_Board>("Memory Tic-Tac-Toe");
        options[13] = new XOGameLauncher<char, Ultimate_XO_UI, Ultimate_XO_Board>("Ultimate Tic-Tac-Toe");
    }
References options.
~Menu()
Menu::~Menu () [inline]
Definition at line 74 of file gamesMenu.h.
            {
        for (auto& p : options) delete p.second;
    }
References options.
Member Function Documentation
print_menu()
void Menu::print_menu () [inline]
Definition at line 78 of file gamesMenu.h.
                      {
        cout << "\n-- Welcome to the FCAI Board Game Collection --\n";
        cout << "------------------------------------------------\n";
        cout << "0. Exit\n";
        for (auto& item : options) {
            int id = item.first;
            GameLauncher* game = item.second;
            cout << id << ". " << game->get_name() << "\n";
        }
    }
References Player< T >::get_name(), and options.
Referenced by run().
run()
void Menu::run () [inline]
Definition at line 90 of file gamesMenu.h.
               {
        int choice;
        while (true) {
            print_menu();
            cout << "Select a game (0-13): ";
            cin >> choice;
            if (choice == 0) {
                cout << "Goodbye!\n";
                break;
            }
            if (options.count(choice)) {
                options[choice]->launch();
            } else {
                cout << "Invalid option!\n";
            }
        }
    }
References options, and print_menu().
Member Data Documentation
options
map<int, GameLauncher*> Menu::options [private]
Definition at line 54 of file gamesMenu.h.
Referenced by Menu(), print_menu(), run(), and ~Menu().
The documentation for this class was generated from the following file:
include/gamesMenu.h