FourFourAIPlayer Class Reference
AI player for Four-Four XO game using minimax algorithm.
#include <Four_Four_XO.h>
Public Member Functions
FourFourAIPlayer (string n, char s, PlayerType t)
virtual Move< char > * calculateMove () override
Override calculateMove to handle direction-based moves.
virtual Move< char > * createMove (int x, int y) override
Create a dualMove at position (x, y) with stored direction.
virtual Move< char > * createUndoMove (int x, int y) override
Create an undo move (reverse the move).
Public Member Functions inherited from AIPlayer< char >
AIPlayer (string n, char s, PlayerType t, char blank, int depth=3)
Constructor for AIPlayer.
virtual ~AIPlayer ()
virtual char get_opponent_symbol ()
Get the opponent's symbol.
Public Member Functions inherited from Player< T >
Player (string n, T s, PlayerType t)
Construct a player with name, symbol, and type.
virtual ~Player ()
string get_name () const
Get the player's name.
PlayerType get_type () const
Get player type (e.g., 'H' or 'C').
T get_symbol () const
Get the player's symbol.
Board< T > * get_board_ptr () const
Get a pointer to the game board.
void set_board_ptr (Board< T > *b)
Assign the board pointer for the player.
Protected Member Functions
virtual bool condition (int x, int y) override
Check if position has a piece belonging to the player that can be moved.
bool condition_for_symbol (int x, int y, char symbol)
Check if position has a piece belonging to a specific symbol.
Move< char > * createUndoMoveForSymbol (int x, int y, int dx, int dy, char symbol)
Helper to create undo move for any symbol.
int minimax (Board< char > *boardPtr, bool maximizingPlayer, char ai, char opp, int alpha, int beta, int depth, int N=3)
Override minimax to handle opponent pieces correctly.
virtual int evaluate_board (Board< char > *boardPtr, char ai, char opp, int N=3) override
Evaluate board position with heuristic.
Protected Member Functions inherited from AIPlayer< char >
virtual int get_max_depth () const
Get the maximum search depth for minimax algorithm.
virtual vector< char > generate_move_values (int x, int y, bool isMaximizing)
Generate possible move values for a given position.
int minimax (Board< char > *boardPtr, bool maximizingPlayer, char ai, char opp, int alpha, int beta, int depth, int N=3)
Minimax algorithm with alpha-beta pruning.
Private Attributes
vector< pair< int, int > > directions
int current_dx
int current_dy
Additional Inherited Members
Protected Attributes inherited from AIPlayer< char >
char blank_symbol
int max_depth
Protected Attributes inherited from Player< T >
string name
Player name.
PlayerType type
Player type (e.g., HUMAN or COMPUTER)
T symbol
Players symbol on board.
Board< T > * boardPtr
Pointer to the game board.
Detailed Description
AI player for Four-Four XO game using minimax algorithm.
Definition at line 86 of file Four_Four_XO.h.
Constructor & Destructor Documentation
FourFourAIPlayer()
FourFourAIPlayer::FourFourAIPlayer (string n, char s, PlayerType t) [inline]
Definition at line 298 of file Four_Four_XO.h.
        : AIPlayer<char>(n, s, t, '.', 3), current_dx(0), current_dy(0) {
        directions = {{1, 0}, {0, 1}, {-1, 0}, {0, -1}}; // Up, Right, Down, Left
    }
References directions.
Member Function Documentation
calculateMove()
virtual Move< char > * FourFourAIPlayer::calculateMove () [inline], [override], [virtual]
Override calculateMove to handle direction-based moves.
Reimplemented from AIPlayer< char >.
Definition at line 306 of file Four_Four_XO.h.
                                                 {
        Board<char>* board_ptr = this->get_board_ptr();
        if (!board_ptr) throw runtime_error("Board not assigned to player!");
        int rows = board_ptr->get_rows();
        int cols = board_ptr->get_columns();
        int bestVal = numeric_limits<int>::min();
        int bestX = -1, bestY = -1, bestDx = 0, bestDy = 0;
        char ai = this->get_symbol();
        char opp = get_opponent_symbol();
        int maxDepth = get_max_depth();
        // Iterate over all positions
        for (int i = 0; i < rows; i++) {
            for (int j = 0; j < cols; j++) {
                // Check if position has player's piece
                if (!condition(i, j)) continue;
                
                // Try each direction
                for (auto& dir : directions) {
                    int dx = dir.first;
                    int dy = dir.second;
                    
                    // Check if move is valid
                    if (i + dx < 0 || i + dx >= rows || j + dy < 0 || j + dy >= cols) continue;
                    if (board_ptr->get_cell(i + dx, j + dy) != blank_symbol) continue;
                    
                    // Try the move
                    current_dx = dx;
                    current_dy = dy;
                    Move<char>* move = createMove(i, j);
                    if (!move) continue;
                    
                    if (board_ptr->update_board(move)) {
                        int eval = minimax(board_ptr, false, ai, opp,
                                          numeric_limits<int>::min(),
                                          numeric_limits<int>::max(),
                                          maxDepth);
                        
                        // Undo the move - move piece back from (i+dx, j+dy) to (i, j)
                        Move<char>* undoMove = createUndoMoveForSymbol(i, j, dx, dy, ai);
                        if (undoMove && board_ptr->update_board(undoMove)) {
                            delete undoMove;
                        } else {
                            delete undoMove;
                        }
                        delete move;
                        
                        if (eval > bestVal) {
                            bestVal = eval;
                            bestX = i;
                            bestY = j;
                            bestDx = dx;
                            bestDy = dy;
                        }
                    } else {
                        delete move;
                    }
                }
            }
        }
        if (bestX == -1 || bestY == -1) {
            // Fallback: find first valid move
            for (int i = 0; i < rows && bestX == -1; i++) {
                for (int j = 0; j < cols && bestX == -1; j++) {
                    if (condition(i, j)) {
                        for (auto& dir : directions) {
                            int dx = dir.first;
                            int dy = dir.second;
                            if (i + dx >= 0 && i + dx < rows && j + dy >= 0 && j + dy < cols) {
                                if (board_ptr->get_cell(i + dx, j + dy) == blank_symbol) {
                                    bestX = i;
                                    bestY = j;
                                    bestDx = dx;
                                    bestDy = dy;
                                    break;
                                }
                            }
                        }
                    }
                }
            }
        }
        current_dx = bestDx;
        current_dy = bestDy;
        return createMove(bestX, bestY);
    }
References AIPlayer< char >::blank_symbol, condition(), createMove(), createUndoMoveForSymbol(), current_dx, current_dy, directions, Player< T >::get_board_ptr(), AIPlayer< char >::get_max_depth(), AIPlayer< char >::get_opponent_symbol(), Player< T >::get_symbol(), minimax(), and Player< T >::Player().
condition()
virtual bool FourFourAIPlayer::condition (int x, int y) [inline], [override], [protected], [virtual]
Check if position has a piece belonging to the player that can be moved.
Reimplemented from AIPlayer< char >.
Definition at line 96 of file Four_Four_XO.h.
                                                  {
        Board<char>* board_ptr = this->get_board_ptr();
        if (!board_ptr) return false;
        if (x < 0 || x >= board_ptr->get_rows() || y < 0 || y >= board_ptr->get_columns()) {
            return false;
        }
        char cell = board_ptr->get_cell(x, y);
        return cell == this->get_symbol();
    }
References Player< T >::get_board_ptr(), and Player< T >::get_symbol().
Referenced by calculateMove().
condition_for_symbol()
bool FourFourAIPlayer::condition_for_symbol (int x, int y, char symbol) [inline], [protected]
Check if position has a piece belonging to a specific symbol.
Definition at line 109 of file Four_Four_XO.h.
                                                         {
        Board<char>* board_ptr = this->get_board_ptr();
        if (!board_ptr) return false;
        if (x < 0 || x >= board_ptr->get_rows() || y < 0 || y >= board_ptr->get_columns()) {
            return false;
        }
        char cell = board_ptr->get_cell(x, y);
        return cell == symbol;
    }
References Player< T >::get_board_ptr(), and Player< T >::symbol.
Referenced by minimax().
createMove()
virtual Move< char > * FourFourAIPlayer::createMove (int x, int y) [inline], [override], [virtual]
Create a dualMove at position (x, y) with stored direction.
Implements AIPlayer< char >.
Definition at line 402 of file Four_Four_XO.h.
                                                          {
        return new dualMove(x, y, this->get_symbol(), current_dy, current_dx);
    }
References current_dx, and Player< T >::get_symbol().
Referenced by calculateMove().
createUndoMove()
virtual Move< char > * FourFourAIPlayer::createUndoMove (int x, int y) [inline], [override], [virtual]
Create an undo move (reverse the move).
Implements AIPlayer< char >.
Definition at line 409 of file Four_Four_XO.h.
                                                              {
        // Reverse the move: move piece back from (x+dx, y+dy) to (x, y)
        return new dualMove(x + current_dx, y + current_dy, this->get_symbol(), -current_dy, -current_dx);
    }
References current_dx, current_dy, and Player< T >::get_symbol().
createUndoMoveForSymbol()
Move< char > * FourFourAIPlayer::createUndoMoveForSymbol (int x, int y, int dx, int dy, char symbol) [inline], [protected]
Helper to create undo move for any symbol.
Definition at line 122 of file Four_Four_XO.h.
                                                                                   {
        // After move, piece is at (x+dx, y+dy). To undo, move it back to (x, y)
        // So move from (x+dx, y+dy) with direction (-dx, -dy)
        return new dualMove(x + dx, y + dy, symbol, -dy, -dx);
    }
References Player< T >::symbol.
Referenced by calculateMove(), and minimax().
evaluate_board()
virtual int FourFourAIPlayer::evaluate_board (Board< char > * boardPtr, char ai, char opp, int N = 3) [inline], [override], [protected], [virtual]
Evaluate board position with heuristic.
Reimplemented from AIPlayer< char >.
Definition at line 239 of file Four_Four_XO.h.
                                                                                             {
        if (boardPtr->is_win(this)) return 1000;
        
        Player<char>* tempOpp = new Player<char>("temp", opp, PlayerType::AI);
        tempOpp->set_board_ptr(boardPtr);
        if (boardPtr->is_win(tempOpp)) {
            delete tempOpp;
            return -1000;
        }
        delete tempOpp;
        
        // Simple heuristic: count pieces in winning positions
        // Check for 2 in a row (potential win)
        int score = 0;
        auto board = boardPtr->get_board_matrix();
        int rows = board.size();
        int cols = board[0].size();
        char blank = '.';
        
        // Check for potential winning lines
        auto count_line = [&](int x, int y, int dx, int dy, char sym) -> int {
            int count = 0;
            for (int k = 0; k < 3; k++) {
                int nx = x + k * dx;
                int ny = y + k * dy;
                if (nx >= 0 && nx < rows && ny >= 0 && ny < cols) {
                    if (board[nx][ny] == sym) count++;
                    else if (board[nx][ny] != blank) return -1; // blocked
                }
            }
            return count;
        };
        
        for (int i = 0; i < rows; i++) {
            for (int j = 0; j < cols; j++) {
                // Check horizontal
                int ai_count = count_line(i, j, 0, 1, ai);
                int opp_count = count_line(i, j, 0, 1, opp);
                if (ai_count > 0) score += ai_count * 10;
                if (opp_count > 0) score -= opp_count * 10;
                
                // Check vertical
                ai_count = count_line(i, j, 1, 0, ai);
                opp_count = count_line(i, j, 1, 0, opp);
                if (ai_count > 0) score += ai_count * 10;
                if (opp_count > 0) score -= opp_count * 10;
                
                // Check diagonal
                ai_count = count_line(i, j, 1, 1, ai);
                opp_count = count_line(i, j, 1, 1, opp);
                if (ai_count > 0) score += ai_count * 10;
                if (opp_count > 0) score -= opp_count * 10;
            }
        }
        
        return score;
    }
References AI, Player< T >::boardPtr, and Player< T >::set_board_ptr().
Referenced by minimax().
minimax()
int FourFourAIPlayer::minimax (Board< char > * boardPtr, bool maximizingPlayer, char ai, char opp, int alpha, int beta, int depth, int N = 3) [inline], [protected]
Override minimax to handle opponent pieces correctly.
Definition at line 131 of file Four_Four_XO.h.
                                                                                                                            {
        // Terminal conditions
        if (boardPtr->is_win(this)) return 1000 + depth;
        
        Player<char>* tempOpp = new Player<char>("temp", opp, PlayerType::AI);
        tempOpp->set_board_ptr(boardPtr);
        if (boardPtr->is_win(tempOpp)) {
            delete tempOpp;
            return -1000 - depth;
        }
        delete tempOpp;
        
        if (boardPtr->is_draw(this)) return 0;
        if (depth == 0) return evaluate_board(boardPtr, ai, opp, N);
        
        int rows = boardPtr->get_rows();
        int cols = boardPtr->get_columns();
        
        if (maximizingPlayer) {
            int best = numeric_limits<int>::min();
            for (int i = 0; i < rows; i++) {
                for (int j = 0; j < cols; j++) {
                    // Check for AI's pieces
                    if (!condition_for_symbol(i, j, ai)) continue;
                    
                    for (auto& dir : directions) {
                        int dx = dir.first;
                        int dy = dir.second;
                        if (i + dx < 0 || i + dx >= rows || j + dy < 0 || j + dy >= cols) continue;
                        if (boardPtr->get_cell(i + dx, j + dy) != blank_symbol) continue;
                        
                        // Try the move
                        Move<char>* move = new dualMove(i, j, ai, dy, dx);
                        if (!move) continue;
                        
                        if (boardPtr->update_board(move)) {
                            int val = minimax(boardPtr, false, ai, opp, alpha, beta, depth - 1, N);
                            
                            // Undo the move - move piece back from (i+dx, j+dy) to (i, j)
                            Move<char>* undomove = createUndoMoveForSymbol(i, j, dx, dy, ai);
                            if (undomove && boardPtr->update_board(undomove)) {
                                delete undomove;
                            } else {
                                // Undo failed - this should never happen but handle it
                                delete undomove;
                            }
                            delete move;
                            
                            best = max(best, val);
                            alpha = max(alpha, best);
                            if (beta <= alpha) {
                                return best;
                            }
                        } else {
                            delete move;
                        }
                    }
                }
            }
            return best;
        } else {
            int best = numeric_limits<int>::max();
            for (int i = 0; i < rows; i++) {
                for (int j = 0; j < cols; j++) {
                    // Check for opponent's pieces
                    if (!condition_for_symbol(i, j, opp)) continue;
                    
                    for (auto& dir : directions) {
                        int dx = dir.first;
                        int dy = dir.second;
                        if (i + dx < 0 || i + dx >= rows || j + dy < 0 || j + dy >= cols) continue;
                        if (boardPtr->get_cell(i + dx, j + dy) != blank_symbol) continue;
                        
                        // Create move with opponent's symbol
                        Move<char>* move = new dualMove(i, j, opp, dy, dx);
                        if (!move) continue;
                        
                        if (boardPtr->update_board(move)) {
                            int val = minimax(boardPtr, true, ai, opp, alpha, beta, depth - 1, N);
                            
                            // Undo the move - move piece back from (i+dx, j+dy) to (i, j)
                            Move<char>* undomove = createUndoMoveForSymbol(i, j, dx, dy, opp);
                            if (undomove && boardPtr->update_board(undomove)) {
                                delete undomove;
                            } else {
                                // Undo failed - this should never happen but handle it
                                delete undomove;
                            }
                            delete move;
                            
                            best = min(best, val);
                            beta = min(beta, best);
                            if (beta <= alpha) {
                                return best;
                            }
                        } else {
                            delete move;
                        }
                    }
                }
            }
            return best;
        }
    }
References AI, AIPlayer< char >::blank_symbol, Player< T >::boardPtr, condition_for_symbol(), createUndoMoveForSymbol(), directions, evaluate_board(), minimax(), Player< T >::Player(), and Player< T >::set_board_ptr().
Referenced by calculateMove(), and minimax().
Member Data Documentation
current_dx
int FourFourAIPlayer::current_dx [private]
Definition at line 90 of file Four_Four_XO.h.
Referenced by calculateMove(), createMove(), and createUndoMove().
current_dy
int FourFourAIPlayer::current_dy [private]
Definition at line 90 of file Four_Four_XO.h.
Referenced by calculateMove(), and createUndoMove().
directions
vector<pair<int, int> > FourFourAIPlayer::directions [private]
Definition at line 89 of file Four_Four_XO.h.
Referenced by calculateMove(), FourFourAIPlayer(), and minimax().
The documentation for this class was generated from the following file:
include/Four_Four_XO.h