Obstacles_XO_UI Class Reference
#include <Obstacles_XO.h>
Public Member Functions
Obstacles_XO_UI ()
Constructs an Obstacles_XO object.
virtual ~Obstacles_XO_UI ()
Destructor for Misere_UI.
Player< char > * create_player (string &name, char symbol, PlayerType type)
Creates a player of the specified type.
virtual Move< char > * get_move (Player< char > *player)
Retrieves the next move from a player.
Public Member Functions inherited from UI< char >
UI (int cell_display_width=3)
Construct the UI and display a welcome message.
UI (string message, int cell_display_width)
Construct the UI and display a welcome message.
virtual ~UI ()
virtual void display_message (string message)
Display any message to the user.
virtual Player< char > ** setup_players ()
Set up players for the game.
virtual Player< char > * create_player (string &name, char symbol, PlayerType type)
Create a player object based on input name, symbol, and type.
virtual void display_board_matrix (const vector< vector< char > > &matrix) const
Display the current board matrix in formatted form.
Additional Inherited Members
Protected Member Functions inherited from UI< char >
virtual string get_player_name (string player_label)
Ask the user for the player's name.
virtual PlayerType get_player_type_choice (string player_label, const vector< string > &options)
Ask the user to choose the player type from a list.
Protected Attributes inherited from UI< char >
int cell_width
Width of each displayed board cell.
Detailed Description
Definition at line 72 of file Obstacles_XO.h.
Constructor & Destructor Documentation
Obstacles_XO_UI()
Obstacles_XO_UI::Obstacles_XO_UI ()
Constructs an Obstacles_XO object.
Initializes the base UI<char> class with the welcome message "FCAI X-O".
Definition at line 122 of file Obstacles_XO.cpp.
: UI<char>("Welcome to Obstacles Tic-Tac-Toe (6x6)", 3) {}
~Obstacles_XO_UI()
virtual Obstacles_XO_UI::~Obstacles_XO_UI () [inline], [virtual]
Destructor for Misere_UI.
Definition at line 85 of file Obstacles_XO.h.
{};
Member Function Documentation
create_player()
Player< char > * Obstacles_XO_UI::create_player (string & name, char symbol, PlayerType type)
Creates a player of the specified type.
Parameters
name Name of the player.
symbol Character symbol ('X' or 'O') assigned to the player.
type The type of the player (Human or Computer).
Returns
Pointer to the newly created Player<char> instance.
Definition at line 124 of file Obstacles_XO.cpp.
                                                                                       {
    cout << "Creating " << (type == PlayerType::HUMAN ? "human" : "computer")
         << " player: " << name << " (" << symbol << ")\n";
    return new Player<char>(name, symbol, type);
}
References HUMAN.
get_move()
Move< char > * Obstacles_XO_UI::get_move (Player< char > * player) [virtual]
Retrieves the next move from a player.
Parameters
player Pointer to the player whose move is being requested.
Returns
A pointer to a new Move<char> object representing the player's action.
Implements UI< char >.
Definition at line 130 of file Obstacles_XO.cpp.
                                                          {
    int x, y;
    if (player->get_type() == PlayerType::HUMAN) {
        cout << "\nPlease enter your move x and y (0 to 5): ";
        cin >> x >> y;
    } else {
        // Random Computer Logic
        do {
            x = rand() % 6;
            y = rand() % 6;
        } while (player->get_board_ptr()->get_board_matrix()[x][y] != '.');
    }
    return new Move<char>(x, y, player->get_symbol());
}
References Player< T >::get_board_ptr(), Player< T >::get_symbol(), Player< T >::get_type(), and HUMAN.
The documentation for this class was generated from the following files:
include/Obstacles_XO.h
src/Obstacles_XO.cpp