AIPlayer< T > Class Template Reference
Base class for AI players following Open-Closed Principle (OCP).
#include <AiPlayer.h>
Public Member Functions
AIPlayer (string n, T s, PlayerType t, T blank, int depth=3)
Constructor for AIPlayer.
virtual ~AIPlayer ()
virtual Move< T > * createMove (int x, int y)=0
Pure virtual function to create a valid move depending on current game rules. Must be implemented by derived classes.
virtual Move< T > * createUndoMove (int x, int y)=0
virtual bool condition (int x, int y)
Check if a position is valid for making a move.
virtual T get_opponent_symbol ()
Get the opponent's symbol.
virtual Move< T > * calculateMove ()
Calculate and return the best move using minimax algorithm.
Public Member Functions inherited from Player< T >
Player (string n, T s, PlayerType t)
Construct a player with name, symbol, and type.
virtual ~Player ()
string get_name () const
Get the player's name.
PlayerType get_type () const
Get player type (e.g., 'H' or 'C').
T get_symbol () const
Get the player's symbol.
Board< T > * get_board_ptr () const
Get a pointer to the game board.
void set_board_ptr (Board< T > *b)
Assign the board pointer for the player.
Protected Member Functions
virtual int evaluate_board (Board< T > *boardPtr, T ai, T opp, int N=3)
Evaluate the current board position from AI's perspective.
virtual int get_max_depth () const
Get the maximum search depth for minimax algorithm.
virtual vector< T > generate_move_values (int x, int y, bool isMaximizing)
Generate possible move values for a given position.
int minimax (Board< T > *boardPtr, bool maximizingPlayer, T ai, T opp, int alpha, int beta, int depth, int N=3)
Minimax algorithm with alpha-beta pruning.
Protected Attributes
T blank_symbol
int max_depth
Protected Attributes inherited from Player< T >
string name
Player name.
PlayerType type
Player type (e.g., HUMAN or COMPUTER)
T symbol
Players symbol on board.
Board< T > * boardPtr
Pointer to the game board.
Detailed Description
template<typename T>
class AIPlayer< T >
Base class for AI players following Open-Closed Principle (OCP).
This class is open for extension but closed for modification. Derived classes only need to override:
createMove() - Create a move at given position
createUndoMove() - Create an undo move at given position
Optional overrides:
condition() - Check if position is valid for a move (default: checks if cell is blank)
get_opponent_symbol() - Get opponent's symbol (default: works for X/O games)
evaluate_board() - Evaluate board position (default: simple heuristic)
get_max_depth() - Maximum search depth (default: 3)
generate_move_values() - Generate possible move values for position (default: single move)
Definition at line 32 of file AiPlayer.h.
Constructor & Destructor Documentation
AIPlayer()
template<typename T >
AIPlayer< T >::AIPlayer (string n, T s, PlayerType t, T blank, int depth = 3) [inline]
Constructor for AIPlayer.
Parameters
n Player name
s Player symbol
t Player type
blank Blank symbol used on the board
depth Maximum search depth (default: 3)
Definition at line 180 of file AiPlayer.h.
        : Player<T>(n, s, t), blank_symbol(blank), max_depth(depth) {}
~AIPlayer()
template<typename T >
virtual AIPlayer< T >::~AIPlayer () [inline], [virtual]
Definition at line 183 of file AiPlayer.h.
{}
Member Function Documentation
calculateMove()
template<typename T >
virtual Move< T > * AIPlayer< T >::calculateMove () [inline], [virtual]
Calculate and return the best move using minimax algorithm.
Returns
Pointer to the best move. Caller is responsible for deletion.
Reimplemented in FourFourAIPlayer.
Definition at line 238 of file AiPlayer.h.
                                     {
        Board<T>* board_ptr = this->get_board_ptr();
        if (!board_ptr) throw runtime_error("Board not assigned to player!");
        int rows = board_ptr->get_rows();
        int cols = board_ptr->get_columns();
        int bestVal = numeric_limits<int>::min();
        int bestX = -1, bestY = -1;
        T ai = this->get_symbol();
        T opp = get_opponent_symbol();
        int maxDepth = get_max_depth();
        for (int i = 0; i < rows; i++) {
            for (int j = 0; j < cols; j++) {
                if (condition(i, j)) {
                    vector<T> moveValues = generate_move_values(i, j, true);
                    for (T moveValue : moveValues) {
                        Move<T>* move = createMove(i, j);
                        if (!move) continue;
                        
                        board_ptr->update_board(move);
                        int eval = minimax(board_ptr, false, ai, opp,
                                           numeric_limits<int>::min(),
                                           numeric_limits<int>::max(),
                                           maxDepth);
                        Move<T>* undoMove = createUndoMove(i, j);
                        if (undoMove) {
                            board_ptr->update_board(undoMove);
                            delete undoMove;
                        }
                        delete move;
                        
                        if (eval > bestVal) {
                            bestVal = eval;
                            bestX = i;
                            bestY = j;
                        }
                    }
                }
            }
        }
        if (bestX == -1 || bestY == -1) {
            // Fallback: find first valid move
            for (int i = 0; i < rows && bestX == -1; i++) {
                for (int j = 0; j < cols && bestX == -1; j++) {
                    if (condition(i, j)) {
                        bestX = i;
                        bestY = j;
                    }
                }
            }
        }
        return createMove(bestX, bestY);
    }
References AIPlayer< T >::condition(), AIPlayer< T >::createMove(), AIPlayer< T >::createUndoMove(), AIPlayer< T >::generate_move_values(), Player< T >::get_board_ptr(), AIPlayer< T >::get_max_depth(), AIPlayer< T >::get_opponent_symbol(), Player< T >::get_symbol(), AIPlayer< T >::minimax(), and Player< T >::Player().
condition()
template<typename T >
virtual bool AIPlayer< T >::condition (int x, int y) [inline], [virtual]
Check if a position is valid for making a move.
Parameters
x X coordinate
y Y coordinate
Returns
true if position is valid, false otherwise
Reimplemented in FourFourAIPlayer.
Definition at line 211 of file AiPlayer.h.
                                         {
        Board<T>* board_ptr = this->get_board_ptr();
        if (!board_ptr) return false;
        if (x < 0 || x >= board_ptr->get_rows() || y < 0 || y >= board_ptr->get_columns()) {
            return false;
        }
        return board_ptr->get_cell(x, y) == blank_symbol;
    }
References AIPlayer< T >::blank_symbol, and Player< T >::get_board_ptr().
Referenced by AIPlayer< T >::calculateMove(), and AIPlayer< T >::minimax().
createMove()
template<typename T >
virtual Move< T > * AIPlayer< T >::createMove (int x, int y) [pure virtual]
Pure virtual function to create a valid move depending on current game rules. Must be implemented by derived classes.
Parameters
x the x_coordinate of move within board.
y the y_coordinate of move within board.
Returns
a pointer to a Move object. Caller is responsible for deletion.
Implemented in FourFourAIPlayer.
Referenced by AIPlayer< T >::calculateMove(), and AIPlayer< T >::minimax().
createUndoMove()
template<typename T >
virtual Move< T > * AIPlayer< T >::createUndoMove (int x, int y) [pure virtual]
Implemented in FourFourAIPlayer.
Referenced by AIPlayer< T >::calculateMove(), and AIPlayer< T >::minimax().
evaluate_board()
template<typename T >
virtual int AIPlayer< T >::evaluate_board (Board< T > * boardPtr, T ai, T opp, int N = 3) [inline], [protected], [virtual]
Evaluate the current board position from AI's perspective.
Parameters
boardPtr Pointer to the board
ai AI's symbol
opp Opponent's symbol
N Sequence length to check (default: 3)
Returns
Evaluation score (positive = favorable for AI)
Reimplemented in FourFourAIPlayer.
Definition at line 45 of file AiPlayer.h.
                                                                           {
        // Default simple evaluation: check for wins/losses
        if (boardPtr->is_win(this)) return 1000;
        // Check if opponent would win - need to create a temporary check
        // For default, return 0 (neutral position)
        return 0;
    }
References Player< T >::boardPtr.
Referenced by AIPlayer< T >::minimax().
generate_move_values()
template<typename T >
virtual vector< T > AIPlayer< T >::generate_move_values (int x, int y, bool isMaximizing) [inline], [protected], [virtual]
Generate possible move values for a given position.
For simple games (like Tic-Tac-Toe), this returns a single value (AI's symbol). For complex games (like Numerical XO), this returns multiple values from search space.
Parameters
x X coordinate
y Y coordinate
isMaximizing Whether this is the maximizing player's turn
Returns
Vector of possible move values
Definition at line 72 of file AiPlayer.h.
                                                                            {
        // Default: single move with AI or opponent symbol
        return vector<T>{isMaximizing ? this->get_symbol() : get_opponent_symbol()};
    }
References AIPlayer< T >::get_opponent_symbol(), and Player< T >::get_symbol().
Referenced by AIPlayer< T >::calculateMove(), and AIPlayer< T >::minimax().
get_max_depth()
template<typename T >
virtual int AIPlayer< T >::get_max_depth () const [inline], [protected], [virtual]
Get the maximum search depth for minimax algorithm.
Returns
Maximum depth
Definition at line 57 of file AiPlayer.h.
                                      {
        return max_depth;
    }
References AIPlayer< T >::max_depth.
Referenced by AIPlayer< T >::calculateMove().
get_opponent_symbol()
template<typename T >
virtual T AIPlayer< T >::get_opponent_symbol () [inline], [virtual]
Get the opponent's symbol.
Returns
Opponent's symbol
Definition at line 224 of file AiPlayer.h.
                                    {
        // Default implementation for X/O games
        if constexpr (std::is_same_v<T, char>) {
            T sym = this->get_symbol();
            if (sym == 'X' || sym == 'x') return 'O';
            if (sym == 'O' || sym == 'o') return 'X';
        }
        return T(); // Default fallback
    }
References Player< T >::get_symbol().
Referenced by AIPlayer< T >::calculateMove(), and AIPlayer< T >::generate_move_values().
minimax()
template<typename T >
int AIPlayer< T >::minimax (Board< T > * boardPtr, bool maximizingPlayer, T ai, T opp, int alpha, int beta, int depth, int N = 3) [inline], [protected]
Minimax algorithm with alpha-beta pruning.
Parameters
boardPtr Pointer to the board
maximizingPlayer Whether it's the maximizing player's turn
ai AI's symbol
opp Opponent's symbol
alpha Alpha value for pruning
beta Beta value for pruning
depth Current depth
N Sequence length parameter
Returns
Evaluation score
Definition at line 89 of file AiPlayer.h.
                                                                                                                   {
        // Terminal conditions
        // Check if AI (this player) wins
        if (boardPtr->is_win(this)) return 1000 + depth; // Prefer faster wins
        
        // Check if opponent wins - create temporary player with opponent symbol
        Player<T>* tempOpponent = new Player<T>("temp_opp", opp, PlayerType::AI);
        tempOpponent->set_board_ptr(boardPtr);
        if (boardPtr->is_win(tempOpponent)) {
            delete tempOpponent;
            return -1000 - depth; // Prefer slower losses
        }
        delete tempOpponent;
        
        if (boardPtr->is_draw(this)) return 0;
        if (depth == 0) return evaluate_board(boardPtr, ai, opp, N);
        int rows = boardPtr->get_rows();
        int cols = boardPtr->get_columns();
        if (maximizingPlayer) {
            int best = numeric_limits<int>::min();
            for (int i = 0; i < rows; i++) {
                for (int j = 0; j < cols; j++) {
                    if (condition(i, j)) {
                        vector<T> moveValues = generate_move_values(i, j, true);
                        for (T moveVal : moveValues) {
                            Move<T>* move = createMove(i, j);
                            // Update move symbol if needed (for games with value-based moves)
                            if (move) {
                                boardPtr->update_board(move);
                                int val = minimax(boardPtr, false, ai, opp, alpha, beta, depth - 1, N);
                                Move<T>* undomove = createUndoMove(i, j);
                                if (undomove) {
                                    boardPtr->update_board(undomove);
                                }
                                delete move;
                                delete undomove;
                                
                                best = max(best, val);
                                alpha = max(alpha, best);
                                if (beta <= alpha) {
                                    return best; // Alpha-beta pruning
                                }
                            }
                        }
                    }
                }
            }
            return best;
        } else {
            int best = numeric_limits<int>::max();
            for (int i = 0; i < rows; i++) {
                for (int j = 0; j < cols; j++) {
                    if (condition(i, j)) {
                        vector<T> moveValues = generate_move_values(i, j, false);
                        for (T moveVal : moveValues) {
                            Move<T>* move = createMove(i, j);
                            if (move) {
                                boardPtr->update_board(move);
                                int val = minimax(boardPtr, true, ai, opp, alpha, beta, depth - 1, N);
                                Move<T>* undomove = createUndoMove(i, j);
                                if (undomove) {
                                    boardPtr->update_board(undomove);
                                }
                                delete move;
                                delete undomove;
                                
                                best = min(best, val);
                                beta = min(beta, best);
                                if (beta <= alpha) {
                                    return best; // Alpha-beta pruning
                                }
                            }
                        }
                    }
                }
            }
            return best;
        }
    }
References AI, Player< T >::boardPtr, AIPlayer< T >::condition(), AIPlayer< T >::createMove(), AIPlayer< T >::createUndoMove(), AIPlayer< T >::evaluate_board(), AIPlayer< T >::generate_move_values(), AIPlayer< T >::minimax(), Player< T >::Player(), and Player< T >::set_board_ptr().
Referenced by AIPlayer< T >::calculateMove(), and AIPlayer< T >::minimax().
Member Data Documentation
blank_symbol
template<typename T >
T AIPlayer< T >::blank_symbol [protected]
Definition at line 34 of file AiPlayer.h.
Referenced by AIPlayer< T >::condition().
max_depth
template<typename T >
int AIPlayer< T >::max_depth [protected]
Definition at line 35 of file AiPlayer.h.
Referenced by AIPlayer< T >::get_max_depth().
The documentation for this class was generated from the following file:
include/AiPlayer.h