Misere_Tic_Tac_Toe_UI Class Reference
User Interface class for the Misere (Tic-Tac-Toe) game.
#include <Misere_Tic_Tac_Toe.h>
Public Member Functions
Misere_Tic_Tac_Toe_UI ()
Constructs an Misere_UI object.
~Misere_Tic_Tac_Toe_UI ()
Destructor for Misere_UI.
Player< char > * create_player (string &name, char symbol, PlayerType type)
Creates a player of the specified type.
virtual Move< char > * get_move (Player< char > *player)
Retrieves the next move from a player.
virtual Player< char > ** setup_players () override
Setup smartPlayer.
Public Member Functions inherited from UI< char >
UI (int cell_display_width=3)
Construct the UI and display a welcome message.
UI (string message, int cell_display_width)
Construct the UI and display a welcome message.
virtual ~UI ()
virtual void display_message (string message)
Display any message to the user.
virtual Player< char > * create_player (string &name, char symbol, PlayerType type)
Create a player object based on input name, symbol, and type.
virtual void display_board_matrix (const vector< vector< char > > &matrix) const
Display the current board matrix in formatted form.
Additional Inherited Members
Protected Member Functions inherited from UI< char >
virtual string get_player_name (string player_label)
Ask the user for the player's name.
virtual PlayerType get_player_type_choice (string player_label, const vector< string > &options)
Ask the user to choose the player type from a list.
Protected Attributes inherited from UI< char >
int cell_width
Width of each displayed board cell.
Detailed Description
User Interface class for the Misere (Tic-Tac-Toe) game.
Inherits from the generic UI<char> base class and provides X-Ospecific functionality for player setup and move input.
See also
UI
Definition at line 90 of file Misere_Tic_Tac_Toe.h.
Constructor & Destructor Documentation
Misere_Tic_Tac_Toe_UI()
Misere_Tic_Tac_Toe_UI::Misere_Tic_Tac_Toe_UI ()
Constructs an Misere_UI object.
Initializes the base UI<char> class with the welcome message "FCAI X-O".
Definition at line 157 of file Misere_Tic_Tac_Toe.cpp.
: UI<char>("Weclome to FCAI X-O Game by Dr El-Ramly", 3) {}
~Misere_Tic_Tac_Toe_UI()
Misere_Tic_Tac_Toe_UI::~Misere_Tic_Tac_Toe_UI ()
Destructor for Misere_UI.
Definition at line 202 of file Misere_Tic_Tac_Toe.cpp.
{}
Member Function Documentation
create_player()
Player< char > * Misere_Tic_Tac_Toe_UI::create_player (string & name, char symbol, PlayerType type)
Creates a player of the specified type.
Parameters
name Name of the player.
symbol Character symbol ('X' or 'O') assigned to the player.
type The type of the player (Human or Computer).
Returns
Pointer to the newly created Player<char> instance.
Definition at line 160 of file Misere_Tic_Tac_Toe.cpp.
                                                                                             {
    cout << "Creating " << (type == PlayerType::HUMAN ? "human" : "computer")
         << " player: " << name << " (" << symbol << ")\n";
    if (type == PlayerType::COMPUTER)
        return new smartPlayer<char>(name, symbol, type); // create smartPlayer
    return new Player<char>(name, symbol, type); // human is regular player
}
References COMPUTER, and HUMAN.
Referenced by setup_players().
get_move()
Move< char > * Misere_Tic_Tac_Toe_UI::get_move (Player< char > * player) [virtual]
Retrieves the next move from a player.
Parameters
player Pointer to the player whose move is being requested.
Returns
A pointer to a new Move<char> object representing the player's action.
Implements UI< char >.
Definition at line 171 of file Misere_Tic_Tac_Toe.cpp.
                                                                {
    int x, y;
    if (player->get_type() == PlayerType::HUMAN) {
        cout << "\nPlease enter your move x and y (0 to 2): ";
        cin >> x >> y;
    }
    else if (player->get_type() == PlayerType::COMPUTER) {
        auto smart_player = dynamic_cast<smartPlayer<char>*>(player);
        auto move = smart_player->calculateMove();
        x = move.first;
        y = move.second;
    }
    return new Move<char>(x, y, player->get_symbol());
}
References COMPUTER, Player< T >::get_symbol(), Player< T >::get_type(), and HUMAN.
setup_players()
Player< char > ** Misere_Tic_Tac_Toe_UI::setup_players () [override], [virtual]
Setup smartPlayer.
Returns
A pointer to a array of smart player objects.
Reimplemented from UI< char >.
Definition at line 187 of file Misere_Tic_Tac_Toe.cpp.
                                                    {
    Player<char>** players = new Player<char>*[2];
    vector<string> type_options = { "Human", "Computer" };
    string nameX = get_player_name("Player X");
    PlayerType typeX = get_player_type_choice("Player X", type_options);
    players[0] = create_player(nameX, static_cast<char>('X'), typeX);
    string nameO = get_player_name("Player O");
    PlayerType typeO = get_player_type_choice("Player O", type_options);
    players[1] = create_player(nameO, static_cast<char>('O'), typeO);
    return players;
}
References create_player(), UI< char >::get_player_name(), and UI< char >::get_player_type_choice().
The documentation for this class was generated from the following files:
include/Misere_Tic_Tac_Toe.h
src/Misere_Tic_Tac_Toe.cpp