smartPlayer2 Class Reference
Public Member Functions
smartPlayer2 (string n, char s, PlayerType t)
int evaluate_board (const vector< vector< char > > &b, char ai, char opp, int N=4) const override
bool is_win (const vector< vector< char > > &b, char symbol, int N=4) const override
virtual bool is_draw (const vector< vector< char > > &b, int N=4) const
int minimax (vector< vector< char > > &b, bool maximizingPlayer, char ai, char opp, int alpha, int beta, int depth, int N=4)
pair< int, int > calculateMove ()
Public Member Functions inherited from smartPlayer< char >
smartPlayer (string n, char s, PlayerType t)
virtual ~smartPlayer ()
Public Member Functions inherited from Player< T >
Player (string n, T s, PlayerType t)
Construct a player with name, symbol, and type.
virtual ~Player ()
string get_name () const
Get the player's name.
PlayerType get_type () const
Get player type (e.g., 'H' or 'C').
T get_symbol () const
Get the player's symbol.
Board< T > * get_board_ptr () const
Get a pointer to the game board.
void set_board_ptr (Board< T > *b)
Assign the board pointer for the player.
Additional Inherited Members
Protected Member Functions inherited from smartPlayer< char >
virtual char get_opponent_symbol () const
Protected Attributes inherited from Player< T >
string name
Player name.
PlayerType type
Player type (e.g., HUMAN or COMPUTER)
T symbol
Players symbol on board.
Board< T > * boardPtr
Pointer to the game board.
Detailed Description
Definition at line 7 of file Four-in-a-row.cpp.
Constructor & Destructor Documentation
smartPlayer2()
smartPlayer2::smartPlayer2 (string n, char s, PlayerType t) [inline]
Definition at line 10 of file Four-in-a-row.cpp.
            : smartPlayer<char>(n, s, t) {}
Member Function Documentation
calculateMove()
pair< int, int > smartPlayer2::calculateMove () [inline], [virtual]
Reimplemented from smartPlayer< char >.
Definition at line 63 of file Four-in-a-row.cpp.
                                   {
        Board<char>* board_ptr = this->get_board_ptr();
        if (!board_ptr) throw runtime_error("Board not assigned to player!");
        auto tempBoard = board_ptr->get_board_matrix();
        int rows = tempBoard.size();
        int cols = tempBoard[0].size();
        int bestVal = numeric_limits<int>::min();
        int bestX = -1, bestY = -1;
        char ai = this->get_symbol();
        char opp = get_opponent_symbol();
        int maxDepth = 2; // tweak: higher depth = stronger AI but slower
        for (int j = 0; j < cols; j++)
            for (int i = rows-1; i >= 0; i--)
                if (tempBoard[i][j] == '.') {
                    tempBoard[i][j] = ai;
                    int moveVal = minimax(tempBoard, false, ai, opp,
                                          numeric_limits<int>::min(),
                                          numeric_limits<int>::max(),
                                          maxDepth);
                    tempBoard[i][j] = '.';
                    if (moveVal > bestVal) {
                        bestVal = moveVal;
                        bestX = i;
                        bestY = j;
                    }
                }
        return {bestX, bestY};
    }
References Player< T >::get_board_ptr(), smartPlayer< char >::get_opponent_symbol(), Player< T >::get_symbol(), minimax(), and Player< T >::Player().
evaluate_board()
int smartPlayer2::evaluate_board (const vector< vector< char > > & b, char ai, char opp, int N = 4) const [inline], [override], [virtual]
Reimplemented from smartPlayer< char >.
Definition at line 13 of file Four-in-a-row.cpp.
                                                                                                   {
        return smartPlayer<char>::evaluate_board(b, ai, opp, N);
    }
References smartPlayer< T >::evaluate_board().
Referenced by minimax().
is_draw()
virtual bool smartPlayer2::is_draw (const vector< vector< char > > & b, int N = 4) const [inline], [virtual]
Reimplemented from smartPlayer< char >.
Definition at line 21 of file Four-in-a-row.cpp.
                                                                         {
        return smartPlayer<char>::is_draw(b, N);
    }
References smartPlayer< T >::is_draw().
Referenced by minimax().
is_win()
bool smartPlayer2::is_win (const vector< vector< char > > & b, char symbol, int N = 4) const [inline], [override], [virtual]
Reimplemented from smartPlayer< char >.
Definition at line 17 of file Four-in-a-row.cpp.
                                                                                      {
        return smartPlayer<char>::is_win(b, symbol, N);
    }
References smartPlayer< T >::is_win(), and Player< T >::symbol.
Referenced by minimax().
minimax()
int smartPlayer2::minimax (vector< vector< char > > & b, bool maximizingPlayer, char ai, char opp, int alpha, int beta, int depth, int N = 4) [inline], [virtual]
Reimplemented from smartPlayer< char >.
Definition at line 25 of file Four-in-a-row.cpp.
                                                                                                                              {
        if (is_win(b, ai, N)) return 1000 + depth; // prefer faster win
        if (is_win(b, opp, N)) return -1000 - depth; // prefer slower loss
        if (is_draw(b, N)) return 0;
        if (depth == 0) return evaluate_board(b, ai, opp, N);
        int rows = b.size();
        int cols = b[0].size();
        if (maximizingPlayer) {
            int best = numeric_limits<int>::min();
            for (int j = 0; j < cols; j++)
                for (int i = rows-1; i >= 0; i--)
                    if (b[i][j] == '.') {
                        b[i][j] = ai;
                        int val = minimax(b, false, ai, opp, alpha, beta, depth - 1, N);
                        b[i][j] = '.';
                        best = max(best, val);
                        alpha = max(alpha, best);
                        if (beta <= alpha) return best;
                    }
            return best;
        } else {
            int best = numeric_limits<int>::max();
            for (int j = 0; j < cols; j++)
                for (int i = rows-1; i >= 0; i--)
                    if (b[i][j] == '.') {
                        b[i][j] = opp;
                        int val = minimax(b, true, ai, opp, alpha, beta, depth - 1, N);
                        b[i][j] = '.';
                        best = min(best, val);
                        beta = min(beta, best);
                        if (beta <= alpha) return best;
                    }
            return best;
        }
    }
References evaluate_board(), is_draw(), is_win(), minimax(), and Player< T >::Player().
Referenced by calculateMove(), and minimax().
The documentation for this class was generated from the following file:
src/Four-in-a-row.cpp