Four_Four_XO_Board Class Reference
Represent the 4*4 XO Tic Tac Toe Game.
#include <Four_Four_XO.h>
Public Member Functions
Four_Four_XO_Board ()
virtual bool update_board (Move< char > *move)
Update the board with a new move.
virtual bool is_win (Player< char > *)
Check if a player has won.
virtual bool is_lose (Player< char > *)
Check if a player has lost.
virtual bool is_draw (Player< char > *)
Check if the game ended in a draw.
virtual bool game_is_over (Player< char > *)
Check if the game is over.
virtual ~Four_Four_XO_Board ()
Public Member Functions inherited from Board< char >
Board (int rows, int columns)
Construct a board with given dimensions.
virtual ~Board ()
Virtual destructor. Frees allocated board memory.
vector< vector< char > > get_board_matrix () const
Return a copy of the current board as a 2D vector.
int get_rows () const
Get number of rows.
int get_columns () const
Get number of columns.
int get_n_moves () const
Get number of moves.
char get_cell (int x, int y)
Return content of cell x, y in current board.
Private Attributes
char blank_symbol = '.'
Additional Inherited Members
Protected Attributes inherited from Board< char >
int rows
Number of rows.
int columns
Number of columns.
vector< vector< char > > board
2D vector for the board
int n_moves
Number of moves made.
Detailed Description
Represent the 4*4 XO Tic Tac Toe Game.
Definition at line 13 of file Four_Four_XO.h.
Constructor & Destructor Documentation
Four_Four_XO_Board()
Four_Four_XO_Board::Four_Four_XO_Board ()
Default constructor of 4*4 Board Size
Definition at line 9 of file Four_Four_XO.cpp.
                                      : Board(4, 4) {
    // Initialize all cells with blank_symbol
    for (auto& row : board)
        for (auto& cell : row)
            cell = blank_symbol;
    for (int i = 0;i<4;i+=2) {
        board[0][i] = 'X'; board[0][i+1] = 'O';
        board[3][i] = 'O'; board[3][i+1] = 'X';
    }
}
References blank_symbol, and Board< char >::board.
~Four_Four_XO_Board()
virtual Four_Four_XO_Board::~Four_Four_XO_Board () [inline], [virtual]
Destructor
Definition at line 39 of file Four_Four_XO.h.
{};
Member Function Documentation
game_is_over()
bool Four_Four_XO_Board::game_is_over (Player< char > * player) [virtual]
Check if the game is over.
Implements Board< char >.
Definition at line 68 of file Four_Four_XO.cpp.
                                                          {
    return is_win(player) || is_draw(player);
}
References is_draw(), and is_win().
is_draw()
bool Four_Four_XO_Board::is_draw (Player< char > * player) [virtual]
Check if the game ended in a draw.
Implements Board< char >.
Definition at line 64 of file Four_Four_XO.cpp.
                                                     {
    return (n_moves == 16 && !is_win(player));
}
References is_win(), and Board< char >::n_moves.
Referenced by game_is_over().
is_lose()
virtual bool Four_Four_XO_Board::is_lose (Player< char > *) [inline], [virtual]
Check if a player has lost.
Implements Board< char >.
Definition at line 30 of file Four_Four_XO.h.
{return false;};
is_win()
bool Four_Four_XO_Board::is_win (Player< char > * player) [virtual]
Check if a player has won.
Implements Board< char >.
Definition at line 42 of file Four_Four_XO.cpp.
                                                    {
    const char sym = player->get_symbol();
    auto all_equal = [&](char a, char b, char c) {
        return a == b && b == c && a != blank_symbol;
    };
    // Check rows and columns
    for (int i = 0; i < rows; ++i) {
        if ((all_equal(board[i][0], board[i][1], board[i][2]) && board[i][0] == sym) ||
            (all_equal(board[0][i], board[1][i], board[2][i]) && board[0][i] == sym))
            return true;
    }
    // Check diagonals
    if ((all_equal(board[0][0], board[1][1], board[2][2]) && board[1][1] == sym) ||
        (all_equal(board[0][2], board[1][1], board[2][0]) && board[1][1] == sym))
        return true;
    return false;
}
References blank_symbol, Board< char >::board, Player< T >::get_symbol(), and Board< char >::rows.
Referenced by game_is_over(), and is_draw().
update_board()
bool Four_Four_XO_Board::update_board (Move< char > * move) [virtual]
Update the board with a new move.
Parameters
move The move object containing position and symbol.
Returns
true if the move is valid and applied, false otherwise.
Implements Board< char >.
Definition at line 22 of file Four_Four_XO.cpp.
                                                      {
    dualMove* dmove = dynamic_cast<dualMove*>(move);
    if (!dmove) return false;
    int x = dmove->get_x();
    int y = dmove->get_y();
    int dy = dmove->get_dy();
    int dx = dmove->get_dx();
    char symbol = dmove->get_symbol();
    if (x<0 || x>=rows || y<0 || y>=columns || board[x][y] != symbol || abs(dy+dx)!=1) return false;
    if (x+dx<0 || x+dx>=rows || y+dy<0 || y+dy>=columns || board[x+dx][y+dy] != blank_symbol) return false;
    n_moves++;
    board[x][y] = blank_symbol;
    board[x+dx][y+dy] = symbol;
    return true;
}
References blank_symbol, Board< char >::board, Board< char >::columns, Player< T >::get_symbol(), Board< char >::n_moves, and Board< char >::rows.
Member Data Documentation
blank_symbol
char Four_Four_XO_Board::blank_symbol = '.' [private]
Definition at line 14 of file Four_Four_XO.h.
Referenced by Four_Four_XO_Board(), is_win(), and update_board().
The documentation for this class was generated from the following files:
include/Four_Four_XO.h
src/Four_Four_XO.cpp