SUS_Board Class Reference
#include <SUS_Classes.h>
Public Member Functions
SUS_Board ()
Default constructor that initializes a 3x3 X-O board.
bool update_board (Move< char > *move)
Updates the board with a player's move.
bool is_win (Player< char > *player)
Checks if the given player has won the game.
bool is_lose (Player< char > *)
Checks if the given player has lost the game.
bool is_draw (Player< char > *player)
Checks if the game has ended in a draw.
bool game_is_over (Player< char > *player)
Determines if the game is over (win or draw).
Public Member Functions inherited from Board< char >
Board (int rows, int columns)
Construct a board with given dimensions.
virtual ~Board ()
Virtual destructor. Frees allocated board memory.
vector< vector< char > > get_board_matrix () const
Return a copy of the current board as a 2D vector.
int get_rows () const
Get number of rows.
int get_columns () const
Get number of columns.
int get_n_moves () const
Get number of moves.
char get_cell (int x, int y)
Return content of cell x, y in current board.
Private Attributes
char blank_symbol = '.'
Additional Inherited Members
Protected Attributes inherited from Board< char >
int rows
Number of rows.
int columns
Number of columns.
vector< vector< char > > board
2D vector for the board
int n_moves
Number of moves made.
Detailed Description
Definition at line 28 of file SUS_Classes.h.
Constructor & Destructor Documentation
SUS_Board()
SUS_Board::SUS_Board ()
Default constructor that initializes a 3x3 X-O board.
Definition at line 6 of file SUS_Classes.cpp.
                     : Board(3, 3) {
    // Initialize all cells with blank_symbol
    for (auto& row : board)
        for (auto& cell : row)
            cell = blank_symbol;
}
References blank_symbol, and Board< char >::board.
Member Function Documentation
game_is_over()
bool SUS_Board::game_is_over (Player< char > * player) [virtual]
Determines if the game is over (win or draw).
Parameters
player Pointer to the player to evaluate.
Returns
true if the game has ended, false otherwise.
Implements Board< char >.
Definition at line 70 of file SUS_Classes.cpp.
                                                 {
    return is_win(player) || is_draw(player) ;
}
References is_draw(), and is_win().
is_draw()
bool SUS_Board::is_draw (Player< char > * player) [virtual]
Checks if the game has ended in a draw.
Parameters
player Pointer to the player being checked.
Returns
true if all cells are filled and no player has won, false otherwise.
Implements Board< char >.
Definition at line 66 of file SUS_Classes.cpp.
                                            {
    return (n_moves == 9 && !is_win(player));
}
References is_win(), and Board< char >::n_moves.
Referenced by game_is_over().
is_lose()
bool SUS_Board::is_lose (Player< char > *) [inline], [virtual]
Checks if the given player has lost the game.
Parameters
player Pointer to the player being checked.
Returns
Always returns false (not used in X-O logic).
Implements Board< char >.
Definition at line 58 of file SUS_Classes.h.
{ return false; };
is_win()
bool SUS_Board::is_win (Player< char > * player) [virtual]
Checks if the given player has won the game.
Parameters
player Pointer to the player being checked.
Returns
true if the player has a winning line, false otherwise.
Implements Board< char >.
Definition at line 35 of file SUS_Classes.cpp.
                                           {
    const char sym = player->get_symbol();
    int score = 0;
    auto isSUS = [&](char a, char b, char c) {
        return (a == 'S' && b == 'U' && c == 'S');
    };
    // Check rows
    for (int i = 0; i < 3; i++) {
        if (isSUS(board[i][0], board[i][1], board[i][2])) score++;
    }
    // Check columns
    for (int j = 0; j < 3; j++) {
        if (isSUS(board[0][j], board[1][j], board[2][j])) score++;
    }
    // Check main diagonal
    if (isSUS(board[0][0], board[1][1], board[2][2])) score++;
    // Check anti-diagonal
    if (isSUS(board[0][2], board[1][1], board[2][0])) score++;
    if (score % 2 == 1) return true;
    return false;
}
References Board< char >::board, and Player< T >::get_symbol().
Referenced by game_is_over(), and is_draw().
update_board()
bool SUS_Board::update_board (Move< char > * move) [virtual]
Updates the board with a player's move.
Parameters
move Pointer to a Move<char> object containing move coordinates and symbol.
Returns
true if the move is valid and successfully applied, false otherwise.
Implements Board< char >.
Definition at line 13 of file SUS_Classes.cpp.
                                             {
    int x = move->get_x();
    int y = move->get_y();
    char mark = move->get_symbol();
    // Validate move and apply if valid
    if (!(x < 0 || x >= rows || y < 0 || y >= columns) &&
        (board[x][y] == blank_symbol || mark == 0)) {
        if (mark == 0) { // Undo move
            n_moves--;
            board[x][y] = blank_symbol;
        }
        else { // Apply move
            n_moves++;
            board[x][y] = toupper(mark);
        }
        return true;
        }
    return false;
}
References blank_symbol, Board< char >::board, Board< char >::columns, Player< T >::get_symbol(), Board< char >::n_moves, and Board< char >::rows.
Member Data Documentation
blank_symbol
char SUS_Board::blank_symbol = '.' [private]
Definition at line 30 of file SUS_Classes.h.
Referenced by SUS_Board(), and update_board().
The documentation for this class was generated from the following files:
include/SUS_Classes.h
src/SUS_Classes.cpp