Infinity_X_O_Board Class Reference
Represents the Tic-Tac-Toe game board.
#include <Infinity_XO_Classes.h>
Public Member Functions
Infinity_X_O_Board ()
Default constructor that initializes a 3x3 X-O board.
bool update_board (Move< char > *move)
Updates the board with a player's move.
bool is_win (Player< char > *player)
Checks if the given player has won the game.
bool is_lose (Player< char > *)
Checks if the given player has lost the game.
bool is_draw (Player< char > *player)
Checks if the game has ended in a draw.
bool game_is_over (Player< char > *player)
Determines if the game is over (win or draw).
Public Member Functions inherited from Board< char >
Board (int rows, int columns)
Construct a board with given dimensions.
virtual ~Board ()
Virtual destructor. Frees allocated board memory.
vector< vector< char > > get_board_matrix () const
Return a copy of the current board as a 2D vector.
int get_rows () const
Get number of rows.
int get_columns () const
Get number of columns.
int get_n_moves () const
Get number of moves.
char get_cell (int x, int y)
Return content of cell x, y in current board.
Private Attributes
char blank_symbol = '.'
Character used to represent an empty cell on the board.
int counter
queue< pair< int, int > > last_moves
Additional Inherited Members
Protected Attributes inherited from Board< char >
int rows
Number of rows.
int columns
Number of columns.
vector< vector< char > > board
2D vector for the board
int n_moves
Number of moves made.
Detailed Description
Represents the Tic-Tac-Toe game board.
This class inherits from the generic Board<char> class and implements the specific logic required for the Tic-Tac-Toe (X-O) game, including move updates, win/draw detection, and display functions.
See also
Board
Definition at line 27 of file Infinity_XO_Classes.h.
Constructor & Destructor Documentation
Infinity_X_O_Board()
Infinity_X_O_Board::Infinity_X_O_Board ()
Default constructor that initializes a 3x3 X-O board.
Definition at line 12 of file Infinity_XO_Classes.cpp.
                                       : Board(3, 3), counter(0) {
    // Initialize all cells with blank_symbol
    for (auto& row : board)
        for (auto& cell : row)
            cell = blank_symbol;
}
References blank_symbol, and Board< char >::board.
Member Function Documentation
game_is_over()
bool Infinity_X_O_Board::game_is_over (Player< char > * player) [virtual]
Determines if the game is over (win or draw).
Parameters
player Pointer to the player to evaluate.
Returns
true if the game has ended, false otherwise.
Implements Board< char >.
Definition at line 75 of file Infinity_XO_Classes.cpp.
                                                          {
    return is_win(player) || is_draw(player);
}
References is_draw(), and is_win().
is_draw()
bool Infinity_X_O_Board::is_draw (Player< char > * player) [virtual]
Checks if the game has ended in a draw.
Parameters
player Pointer to the player being checked.
Returns
true if all cells are filled and no player has won, false otherwise.
Implements Board< char >.
Definition at line 71 of file Infinity_XO_Classes.cpp.
                                                     {
    return (n_moves == 9 && !is_win(player));
}
References is_win(), and Board< char >::n_moves.
Referenced by game_is_over().
is_lose()
bool Infinity_X_O_Board::is_lose (Player< char > *) [inline], [virtual]
Checks if the given player has lost the game.
Parameters
player Pointer to the player being checked.
Returns
Always returns false (not used in X-O logic).
Implements Board< char >.
Definition at line 58 of file Infinity_XO_Classes.h.
{ return false; };
is_win()
bool Infinity_X_O_Board::is_win (Player< char > * player) [virtual]
Checks if the given player has won the game.
Parameters
player Pointer to the player being checked.
Returns
true if the player has a winning line, false otherwise.
Implements Board< char >.
Definition at line 49 of file Infinity_XO_Classes.cpp.
                                                    {
    const char sym = player->get_symbol();
    auto all_equal = [&](char a, char b, char c) {
        return a == b && b == c && a != blank_symbol;
        };
    // Check rows and columns
    for (int i = 0; i < rows; ++i) {
        if ((all_equal(board[i][0], board[i][1], board[i][2]) && board[i][0] == sym) ||
            (all_equal(board[0][i], board[1][i], board[2][i]) && board[0][i] == sym))
            return true;
    }
    // Check diagonals
    if ((all_equal(board[0][0], board[1][1], board[2][2]) && board[1][1] == sym) ||
        (all_equal(board[0][2], board[1][1], board[2][0]) && board[1][1] == sym))
        return true;
    return false;
}
References blank_symbol, Board< char >::board, Player< T >::get_symbol(), and Board< char >::rows.
Referenced by game_is_over(), and is_draw().
update_board()
bool Infinity_X_O_Board::update_board (Move< char > * move) [virtual]
Updates the board with a player's move.
Parameters
move Pointer to a Move<char> object containing move coordinates and symbol.
Returns
true if the move is valid and successfully applied, false otherwise.
Implements Board< char >.
Definition at line 19 of file Infinity_XO_Classes.cpp.
                                                      {
    int x = move->get_x();
    int y = move->get_y();
    char mark = move->get_symbol();
    // Validate move and apply if valid
    if (!(x < 0 || x >= rows || y < 0 || y >= columns) &&
        (board[x][y] == blank_symbol || mark == 0)) {
        if (mark == 0) { // Undo move
            n_moves--;
            board[x][y] = blank_symbol;
        }
        else { // Apply move
            n_moves++;
            board[x][y] = toupper(mark);
        }
        counter++;
        last_moves.push({x,y});
        if (counter==3) {
            auto [xl,yl] = last_moves.front();
            last_moves.pop();
            board[xl][yl] = blank_symbol;
            counter = 0;
        }
        return true;
    }
    return false;
}
References blank_symbol, Board< char >::board, Board< char >::columns, counter, Player< T >::get_symbol(), last_moves, Board< char >::n_moves, and Board< char >::rows.
Member Data Documentation
blank_symbol
char Infinity_X_O_Board::blank_symbol = '.' [private]
Character used to represent an empty cell on the board.
Definition at line 29 of file Infinity_XO_Classes.h.
Referenced by Infinity_X_O_Board(), is_win(), and update_board().
counter
int Infinity_X_O_Board::counter [private]
Definition at line 30 of file Infinity_XO_Classes.h.
Referenced by update_board().
last_moves
queue<pair<int, int> > Infinity_X_O_Board::last_moves [private]
Definition at line 31 of file Infinity_XO_Classes.h.
Referenced by update_board().
The documentation for this class was generated from the following files:
include/Infinity_XO_Classes.h
src/Infinity_XO_Classes.cpp