MisereSmartPlayer Class Reference
#include <Misere_Tic_Tac_Toe.h>
Public Member Functions
MisereSmartPlayer (string n, char s, PlayerType t)
virtual pair< int, int > calculateMove () override
virtual char get_opponent_symbol () const override
bool check_3_in_row (const vector< vector< char > > &b, char symbol) const
int minimax_misere (vector< vector< char > > &b, bool isMaximizing, int depth=0)
Public Member Functions inherited from smartPlayer< char >
smartPlayer (string n, char s, PlayerType t)
virtual ~smartPlayer ()
Public Member Functions inherited from Player< T >
Player (string n, T s, PlayerType t)
Construct a player with name, symbol, and type.
virtual ~Player ()
string get_name () const
Get the player's name.
PlayerType get_type () const
Get player type (e.g., 'H' or 'C').
T get_symbol () const
Get the player's symbol.
Board< T > * get_board_ptr () const
Get a pointer to the game board.
void set_board_ptr (Board< T > *b)
Assign the board pointer for the player.
Additional Inherited Members
Protected Member Functions inherited from smartPlayer< char >
virtual int evaluate_board (const vector< vector< char > > &b, char ai, char opp, int N=3) const
virtual bool is_win (const vector< vector< char > > &b, char symbol, int N=3) const
virtual bool is_draw (const vector< vector< char > > &b, int N=3) const
virtual int minimax (vector< vector< char > > &b, bool maximizingPlayer, char ai, char opp, int alpha, int beta, int depth, int N=3)
Protected Attributes inherited from Player< T >
string name
Player name.
PlayerType type
Player type (e.g., HUMAN or COMPUTER)
T symbol
Players symbol on board.
Board< T > * boardPtr
Pointer to the game board.
Detailed Description
Definition at line 128 of file Misere_Tic_Tac_Toe.h.
Constructor & Destructor Documentation
MisereSmartPlayer()
MisereSmartPlayer::MisereSmartPlayer (string n, char s, PlayerType t) [inline]
Definition at line 130 of file Misere_Tic_Tac_Toe.h.
: smartPlayer(n, s, t) {}
Member Function Documentation
calculateMove()
pair< int, int > MisereSmartPlayer::calculateMove () [override], [virtual]
Reimplemented from smartPlayer< char >.
Definition at line 127 of file Misere_Tic_Tac_Toe.cpp.
                                                {
    Board<char>* board_ptr = this->get_board_ptr();
    auto tempBoard = board_ptr->get_board_matrix();
    int bestVal = -1000;
    int bestX = -1, bestY = -1;
    for (int i = 0; i < 3; i++) {
        for (int j = 0; j < 3; j++) {
            if (tempBoard[i][j] == '.') {
                tempBoard[i][j] = symbol;
                int moveVal = minimax_misere(tempBoard, false, 0);
                tempBoard[i][j] = '.';
                if (moveVal > bestVal) {
                    bestVal = moveVal;
                    bestX = i;
                    bestY = j;
                }
            }
        }
    }
    return {bestX, bestY};
}
References Player< T >::get_board_ptr(), minimax_misere(), and Player< T >::symbol.
check_3_in_row()
bool MisereSmartPlayer::check_3_in_row (const vector< vector< char > > & b, char symbol) const
Definition at line 76 of file Misere_Tic_Tac_Toe.cpp.
                                                                                       {
    for (int i = 0; i < 3; i++) {
        if (b[i][0] == symbol && b[i][1] == symbol && b[i][2] == symbol) return true;
        if (b[0][i] == symbol && b[1][i] == symbol && b[2][i] == symbol) return true;
    }
    if (b[0][0] == symbol && b[1][1] == symbol && b[2][2] == symbol) return true;
    if (b[0][2] == symbol && b[1][1] == symbol && b[2][0] == symbol) return true;
    return false;
}
References Player< T >::symbol.
Referenced by minimax_misere().
get_opponent_symbol()
char MisereSmartPlayer::get_opponent_symbol () const [override], [virtual]
Reimplemented from smartPlayer< char >.
Definition at line 72 of file Misere_Tic_Tac_Toe.cpp.
                                                  {
    return (this->symbol == 'X') ? 'O' : 'X';
}
References Player< T >::symbol.
Referenced by minimax_misere().
minimax_misere()
int MisereSmartPlayer::minimax_misere (vector< vector< char > > & b, bool isMaximizing, int depth = 0)
Definition at line 86 of file Misere_Tic_Tac_Toe.cpp.
                                                                                           {
    char ai = this->symbol;
    char opp = get_opponent_symbol();
    if (check_3_in_row(b, ai)) return -10 + depth;
    if (check_3_in_row(b, opp)) return 10 - depth;
    bool full = true;
    for(auto& r : b) for(auto c : r) if(c == '.') full = false;
    if(full) return 0;
    // 2. Recursion
    if (isMaximizing) {
        int best = -1000;
        for (int i = 0; i < 3; i++) {
            for (int j = 0; j < 3; j++) {
                if (b[i][j] == '.') {
                    b[i][j] = ai;
                    best = max(best, minimax_misere(b, false, depth + 1));
                    b[i][j] = '.';
                }
            }
        }
        return best;
    } else {
        int best = 1000;
        for (int i = 0; i < 3; i++) {
            for (int j = 0; j < 3; j++) {
                if (b[i][j] == '.') {
                    b[i][j] = opp;
                    best = min(best, minimax_misere(b, true, depth + 1));
                    b[i][j] = '.';
                }
            }
        }
        return best;
    }
}
References check_3_in_row(), get_opponent_symbol(), minimax_misere(), and Player< T >::symbol.
Referenced by calculateMove(), and minimax_misere().
The documentation for this class was generated from the following files:
include/Misere_Tic_Tac_Toe.h
src/Misere_Tic_Tac_Toe.cpp