Infinit_XO_UI Class Reference
User Interface class for the X-O (Tic-Tac-Toe) game.
#include <Infinity_XO_Classes.h>
Public Member Functions
Infinit_XO_UI ()
Constructs an XO_UI object.
~Infinit_XO_UI ()
Destructor for XO_UI.
Player< char > * create_player (string &name, char symbol, PlayerType type)
Creates a player of the specified type.
virtual Move< char > * get_move (Player< char > *player)
Retrieves the next move from a player.
Public Member Functions inherited from UI< char >
UI (int cell_display_width=3)
Construct the UI and display a welcome message.
UI (string message, int cell_display_width)
Construct the UI and display a welcome message.
virtual ~UI ()
virtual void display_message (string message)
Display any message to the user.
virtual Player< char > ** setup_players ()
Set up players for the game.
virtual Player< char > * create_player (string &name, char symbol, PlayerType type)
Create a player object based on input name, symbol, and type.
virtual void display_board_matrix (const vector< vector< char > > &matrix) const
Display the current board matrix in formatted form.
Additional Inherited Members
Protected Member Functions inherited from UI< char >
virtual string get_player_name (string player_label)
Ask the user for the player's name.
virtual PlayerType get_player_type_choice (string player_label, const vector< string > &options)
Ask the user to choose the player type from a list.
Protected Attributes inherited from UI< char >
int cell_width
Width of each displayed board cell.
Detailed Description
User Interface class for the X-O (Tic-Tac-Toe) game.
Inherits from the generic UI<char> base class and provides X-Ospecific functionality for player setup and move input.
See also
UI
Definition at line 85 of file Infinity_XO_Classes.h.
Constructor & Destructor Documentation
Infinit_XO_UI()
Infinit_XO_UI::Infinit_XO_UI ()
Constructs an XO_UI object.
Initializes the base UI<char> class with the welcome message "FCAI X-O".
Definition at line 81 of file Infinity_XO_Classes.cpp.
: UI<char>("Weclome to FCAI X-O Game", 3) {}
~Infinit_XO_UI()
Infinit_XO_UI::~Infinit_XO_UI () [inline]
Destructor for XO_UI.
Definition at line 97 of file Infinity_XO_Classes.h.
{};
Member Function Documentation
create_player()
Player< char > * Infinit_XO_UI::create_player (string & name, char symbol, PlayerType type)
Creates a player of the specified type.
Parameters
name Name of the player.
symbol Character symbol ('X' or 'O') assigned to the player.
type The type of the player (Human or Computer).
Returns
Pointer to the newly created Player<char> instance.
Definition at line 83 of file Infinity_XO_Classes.cpp.
                                                                                     {
    // Create player based on type
    cout << "Creating " << (type == PlayerType::HUMAN ? "human" : "computer")
        << " player: " << name << " (" << symbol << ")\n";
    return new Player<char>(name, symbol, type);
}
References HUMAN.
get_move()
Move< char > * Infinit_XO_UI::get_move (Player< char > * player) [virtual]
Retrieves the next move from a player.
Parameters
player Pointer to the player whose move is being requested.
Returns
A pointer to a new Move<char> object representing the player's action.
Implements UI< char >.
Definition at line 91 of file Infinity_XO_Classes.cpp.
                                                        {
    int x, y;
    
    if (player->get_type() == PlayerType::HUMAN) {
        cout << "\nPlease enter your move x and y (0 to 2): ";
        cin >> x >> y;
    }
    else if (player->get_type() == PlayerType::COMPUTER) {
        x = rand() % player->get_board_ptr()->get_rows();
        y = rand() % player->get_board_ptr()->get_columns();
    }
    return new Move<char>(x, y, player->get_symbol());
}
References COMPUTER, Player< T >::get_board_ptr(), Player< T >::get_symbol(), Player< T >::get_type(), and HUMAN.
The documentation for this class was generated from the following files:
include/Infinity_XO_Classes.h
src/Infinity_XO_Classes.cpp