SUS_UI Class Reference
#include <SUS_Classes.h>
Public Member Functions
SUS_UI ()
Constructs an XO_UI object.
Player< char > * create_player (string &name, char symbol, PlayerType type)
Destructor for XO_UI.
virtual Move< char > * get_move (Player< char > *player)
Retrieves the next move from a player.
~SUS_UI ()
Public Member Functions inherited from UI< char >
UI (int cell_display_width=3)
Construct the UI and display a welcome message.
UI (string message, int cell_display_width)
Construct the UI and display a welcome message.
virtual ~UI ()
virtual void display_message (string message)
Display any message to the user.
virtual Player< char > ** setup_players ()
Set up players for the game.
virtual Player< char > * create_player (string &name, char symbol, PlayerType type)
Create a player object based on input name, symbol, and type.
virtual void display_board_matrix (const vector< vector< char > > &matrix) const
Display the current board matrix in formatted form.
Additional Inherited Members
Protected Member Functions inherited from UI< char >
virtual string get_player_name (string player_label)
Ask the user for the player's name.
virtual PlayerType get_player_type_choice (string player_label, const vector< string > &options)
Ask the user to choose the player type from a list.
Protected Attributes inherited from UI< char >
int cell_width
Width of each displayed board cell.
Detailed Description
Definition at line 86 of file SUS_Classes.h.
Constructor & Destructor Documentation
SUS_UI()
SUS_UI::SUS_UI ()
Constructs an XO_UI object.
Initializes the base UI<char> class with the welcome message "FCAI X-O".
Definition at line 322 of file SUS_Classes.cpp.
: UI<char>("Welcome to FCAI S-U-S Game by Adham", 3) {}
~SUS_UI()
SUS_UI::~SUS_UI () [inline]
Definition at line 116 of file SUS_Classes.h.
{};
Member Function Documentation
create_player()
Player< char > * SUS_UI::create_player (string & name, char symbol, PlayerType type)
Destructor for XO_UI.
Creates a player of the specified type.
Parameters
name Name of the player.
symbol Character symbol ('X' or 'O') assigned to the player.
type The type of the player (Human or Computer).
Returns
Pointer to the newly created Player<char> instance.
Definition at line 325 of file SUS_Classes.cpp.
                                                                              {
    cout << "Creating " << (type == PlayerType::HUMAN ? "human" : "computer")
        << " player: " << name << " (" << symbol << ")\n";
    if (type == PlayerType::HUMAN) {
        return new Player<char>(name, symbol, type);
    } else {
        // Construct a wordSmartPlayer and pass the dictionary file path
        // Make sure "dic.txt" path is correct relative to your working dir
        return new SUS_SmartPlayer(name, symbol, type, "dic.txt");
    }
}
References HUMAN.
get_move()
Move< char > * SUS_UI::get_move (Player< char > * player) [virtual]
Retrieves the next move from a player.
Parameters
player Pointer to the player whose move is being requested.
Returns
A pointer to a new Move<char> object representing the player's action.
Implements UI< char >.
Definition at line 339 of file SUS_Classes.cpp.
                                                 {
    int x, y;
    char c;
    if (player->get_type() == PlayerType::HUMAN) {
        cout << "\nPlease enter your move x and y (0 to 2): and 'S' or 'U':";
        cin >> x >> y >> c;
        while (c != 'S' && c != 'U') {
            cout << "Enter 'S' or 'U': ";
            cin >> c;
        }
    }
    else if (player->get_type() == PlayerType::COMPUTER) {
        auto smart_player = dynamic_cast<SUS_SmartPlayer*>(player);
        if (!smart_player) {
            // fallback: the player is not a SUS_SmartPlayer (shouldn't happen if create_player fixed)
            // cerr << "Warning: computer player is not SUS_SmartPlayer — using default move.\n";
            // produce a simple default move (first empty cell with 'A') to avoid crash
            Board<char>* board_ptr = player->get_board_ptr();
            if (!board_ptr) throw runtime_error("Board not assigned to computer player!");
            auto tmp = board_ptr->get_board_matrix();
            bool found = false;
            for (int i = 0; i < (int)tmp.size() && !found; ++i)
                for (int j = 0; j < (int)tmp[i].size() && !found; ++j)
                    if (tmp[i][j] == '.') { x = i; y = j; c = 'A'; found = true; }
            if (!found) throw runtime_error("No valid moves available for computer.");
        } else {
            auto move = smart_player->calculateMove2();
            x = move.first.first;
            y = move.first.second;
            c = static_cast<char>(move.second);
        }
    }
    return new ne_Move(x, y, player->get_symbol() , c);
}
References COMPUTER, Player< T >::get_board_ptr(), Player< T >::get_symbol(), Player< T >::get_type(), and HUMAN.
The documentation for this class was generated from the following files:
include/SUS_Classes.h
src/SUS_Classes.cpp