X_O_5x5_Board Class Reference
#include <X_O_5x5.h>
Public Member Functions
X_O_5x5_Board ()
bool update_board (Move< char > *move)
Update the board with a new move.
bool is_win (Player< char > *player)
Check if a player has won.
bool is_lose (Player< char > *player)
Check if a player has lost.
bool is_draw (Player< char > *player)
Check if the game ended in a draw.
bool game_is_over (Player< char > *player)
Check if the game is over.
Public Member Functions inherited from Board< char >
Board (int rows, int columns)
Construct a board with given dimensions.
virtual ~Board ()
Virtual destructor. Frees allocated board memory.
vector< vector< char > > get_board_matrix () const
Return a copy of the current board as a 2D vector.
int get_rows () const
Get number of rows.
int get_columns () const
Get number of columns.
int get_n_moves () const
Get number of moves.
char get_cell (int x, int y)
Return content of cell x, y in current board.
Private Attributes
char blank_symbol = '.'
int counter
Additional Inherited Members
Protected Attributes inherited from Board< char >
int rows
Number of rows.
int columns
Number of columns.
vector< vector< char > > board
2D vector for the board
int n_moves
Number of moves made.
Detailed Description
Definition at line 9 of file X_O_5x5.h.
Constructor & Destructor Documentation
X_O_5x5_Board()
X_O_5x5_Board::X_O_5x5_Board ()
Definition at line 7 of file X_O_5x5.cpp.
                             : Board(5, 5) , counter(0){
    for (auto& row : board)
        for (auto& cell : row)
            cell = blank_symbol;
}
References blank_symbol, and Board< char >::board.
Member Function Documentation
game_is_over()
bool X_O_5x5_Board::game_is_over (Player< char > *) [virtual]
Check if the game is over.
Implements Board< char >.
Definition at line 127 of file X_O_5x5.cpp.
                                                     {
    return is_win(player) || is_draw(player);
}
References is_draw(), and is_win().
is_draw()
bool X_O_5x5_Board::is_draw (Player< char > *) [virtual]
Check if the game ended in a draw.
Implements Board< char >.
Definition at line 123 of file X_O_5x5.cpp.
                                                {
    return (n_moves == 24);
}
References Board< char >::n_moves.
Referenced by game_is_over().
is_lose()
bool X_O_5x5_Board::is_lose (Player< char > *) [virtual]
Check if a player has lost.
Implements Board< char >.
Definition at line 119 of file X_O_5x5.cpp.
                                                {
    return (n_moves == 24 && !is_win(player));
}
References is_win(), and Board< char >::n_moves.
is_win()
bool X_O_5x5_Board::is_win (Player< char > *) [virtual]
Check if a player has won.
0
Implements Board< char >.
Definition at line 36 of file X_O_5x5.cpp.
                                               {
    if (n_moves != 24) return false;
    const char sym = (*player).get_symbol();
    const char opponent = (player->get_symbol() == 'X') ? 'O' : 'X';
    int cnt = 0,cnt2 = 0;
    auto all_equal = [&](char a, char b, char c) {
        return a == b && b == c && a == sym;
    };
    // Rows
    for (int i = 0; i < rows; i++) {
        for (int j = 0; j < columns - 2; j++) {
            if (all_equal(board[i][j], board[i][j+1], board[i][j+2]))
                cnt++;
        }
    }
    // Columns
    for (int j = 0; j < columns; j++) {
        for (int i = 0; i < rows - 2; i++) {
            if (all_equal(board[i][j], board[i+1][j], board[i+2][j]))
                cnt++;
        }
    }
    // Diagonal
    for (int i = 0; i < rows - 2; i++) {
        for (int j = 0; j < columns - 2; j++) {
            if (all_equal(board[i][j], board[i+1][j+1], board[i+2][j+2]))
                cnt++;
        }
    }
    // Diagonal
    for (int i = 0; i < rows - 2; i++) {
        for (int j = 2; j < columns; j++) {
            if (all_equal(board[i][j], board[i+1][j-1], board[i+2][j-2]))
                cnt++;
        }
    }
    // for opponent --------------------------------------------
    auto all_equal2 = [&](char a, char b, char c) {
        return a == b && b == c && a == opponent;
    };
    // Rows
    for (int i = 0; i < rows; i++) {
        for (int j = 0; j < columns - 2; j++) {
            if (all_equal2(board[i][j], board[i][j+1], board[i][j+2]))
                cnt2++;
        }
    }
    // Columns
    for (int j = 0; j < columns; j++) {
        for (int i = 0; i < rows - 2; i++) {
            if (all_equal2(board[i][j], board[i+1][j], board[i+2][j]))
                cnt2++;
        }
    }
    // Diagonal
    for (int i = 0; i < rows - 2; i++) {
        for (int j = 0; j < columns - 2; j++) {
            if (all_equal2(board[i][j], board[i+1][j+1], board[i+2][j+2]))
                cnt2++;
        }
    }
    // Diagonal
    for (int i = 0; i < rows - 2; i++) {
        for (int j = 2; j < columns; j++) {
            if (all_equal2(board[i][j], board[i+1][j-1], board[i+2][j-2]))
                cnt2++;
        }
    }
    if (cnt > cnt2) return 1;
    else return 0;
}
References Board< char >::board, Board< char >::columns, Player< T >::get_symbol(), Board< char >::n_moves, and Board< char >::rows.
Referenced by game_is_over(), and is_lose().
update_board()
bool X_O_5x5_Board::update_board (Move< char > * move) [virtual]
Update the board with a new move.
Parameters
move The move object containing position and symbol.
Returns
true if the move is valid and applied, false otherwise.
Implements Board< char >.
Definition at line 13 of file X_O_5x5.cpp.
                                                 {
    int x = (*move).get_x();
    int y = (*move).get_y();
    int sym = (*move).get_symbol();
    if (!(x < 0 || x >= rows || y < 0 || y >= columns) &&
        (board[x][y] == blank_symbol || sym == 0)) {
        if (sym == 0) { // Undo move
            n_moves--;
            board[x][y] = blank_symbol;
        }
        else { // Apply move
            n_moves++;
            board[x][y] = toupper(sym);
        }
        counter++;
        return true;
        }
    return false;
}
References blank_symbol, Board< char >::board, Board< char >::columns, counter, Player< T >::get_symbol(), Board< char >::n_moves, and Board< char >::rows.
Member Data Documentation
blank_symbol
char X_O_5x5_Board::blank_symbol = '.' [private]
Definition at line 11 of file X_O_5x5.h.
Referenced by update_board(), and X_O_5x5_Board().
counter
int X_O_5x5_Board::counter [private]
Definition at line 12 of file X_O_5x5.h.
Referenced by update_board().
The documentation for this class was generated from the following files:
include/X_O_5x5.h
src/X_O_5x5.cpp