mainBoard Class Reference
#include <Ultimate_Tic_Tac_Toe.h>
Public Member Functions
mainBoard ()
Default constructor that initializes a 3*3 main Board;.
bool update_board (Move< char > *move)
Updates the board with a player's move.
bool is_win (Player< char > *player)
Checks if the given player has won the game.
bool is_lose (Player< char > *)
Checks if the given player has lost the game.
bool is_draw (Player< char > *player)
Checks if the game has ended in a draw.
bool game_is_over (Player< char > *player)
Determines if the game is over (win or draw).
virtual ~mainBoard ()
Public Member Functions inherited from Board< char >
Board (int rows, int columns)
Construct a board with given dimensions.
virtual ~Board ()
Virtual destructor. Frees allocated board memory.
vector< vector< char > > get_board_matrix () const
Return a copy of the current board as a 2D vector.
int get_rows () const
Get number of rows.
int get_columns () const
Get number of columns.
int get_n_moves () const
Get number of moves.
char get_cell (int x, int y)
Return content of cell x, y in current board.
Private Attributes
char blank_symbol = '.'
Additional Inherited Members
Protected Attributes inherited from Board< char >
int rows
Number of rows.
int columns
Number of columns.
vector< vector< char > > board
2D vector for the board
int n_moves
Number of moves made.
Detailed Description
Definition at line 10 of file Ultimate_Tic_Tac_Toe.h.
Constructor & Destructor Documentation
mainBoard()
mainBoard::mainBoard ()
Default constructor that initializes a 3*3 main Board;.
Definition at line 8 of file Ultimate_Tic_Tac_Toe.cpp.
                     :Board<char>(3,3) {
    // Initialize all cells with blank_symbol
    for (auto& row : board)
        for (auto& cell : row)
            cell = blank_symbol;
}
References blank_symbol, and Board< char >::board.
~mainBoard()
virtual mainBoard::~mainBoard () [inline], [virtual]
Definition at line 54 of file Ultimate_Tic_Tac_Toe.h.
{};
Member Function Documentation
game_is_over()
bool mainBoard::game_is_over (Player< char > * player) [virtual]
Determines if the game is over (win or draw).
Parameters
player Pointer to the player to evaluate.
Returns
true if the game has ended, false otherwise.
Implements Board< char >.
Definition at line 56 of file Ultimate_Tic_Tac_Toe.cpp.
                                                 {
    return is_win(player) || is_draw(player);
}
References is_draw(), and is_win().
is_draw()
bool mainBoard::is_draw (Player< char > * player) [virtual]
Checks if the game has ended in a draw.
Parameters
player Pointer to the player being checked.
Returns
true if all cells are filled and no player has won, false otherwise.
Implements Board< char >.
Definition at line 52 of file Ultimate_Tic_Tac_Toe.cpp.
                                            {
    return (n_moves == 9 && !is_win(player));
}
References is_win(), and Board< char >::n_moves.
Referenced by game_is_over().
is_lose()
bool mainBoard::is_lose (Player< char > *) [inline], [virtual]
Checks if the given player has lost the game.
Parameters
player Pointer to the player being checked.
Returns
Always returns false (not used in X-O logic).
Implements Board< char >.
Definition at line 38 of file Ultimate_Tic_Tac_Toe.h.
{ return false; };
is_win()
bool mainBoard::is_win (Player< char > * player) [virtual]
Checks if the given player has won the game.
Parameters
player Pointer to the player being checked.
Returns
true if the player has a winning line, false otherwise.
Implements Board< char >.
Definition at line 30 of file Ultimate_Tic_Tac_Toe.cpp.
                                           {
    const char sym = player->get_symbol();
    auto all_equal = [&](char a, char b, char c) {
        return a == b && b == c && a != blank_symbol;
    };
    // Check rows and columns
    for (int i = 0; i < rows; ++i) {
        if ((all_equal(board[i][0], board[i][1], board[i][2]) && board[i][0] == sym) ||
            (all_equal(board[0][i], board[1][i], board[2][i]) && board[0][i] == sym))
            return true;
    }
    // Check diagonals
    if ((all_equal(board[0][0], board[1][1], board[2][2]) && board[1][1] == sym) ||
        (all_equal(board[0][2], board[1][1], board[2][0]) && board[1][1] == sym))
        return true;
    return false;
}
References blank_symbol, Board< char >::board, Player< T >::get_symbol(), and Board< char >::rows.
Referenced by game_is_over(), and is_draw().
update_board()
bool mainBoard::update_board (Move< char > * move) [virtual]
Updates the board with a player's move.
Parameters
move Pointer to a Move<char> object containing move coordinates and symbol.
Returns
true if the move is valid and successfully applied, false otherwise.
Implements Board< char >.
Definition at line 16 of file Ultimate_Tic_Tac_Toe.cpp.
                                             {
    int x = move->get_x()/3;
    int y = move->get_y()/3;
    char mark = move->get_symbol();
    // Validate move and apply if valid
    if (!(x < 0 || x >= rows || y < 0 || y >= columns) && (board[x][y] == blank_symbol)) {
        board[x][y] = toupper(mark);
        n_moves++;
        return true;
    }
    return false;
}
References blank_symbol, Board< char >::board, Board< char >::columns, Player< T >::get_symbol(), Board< char >::n_moves, and Board< char >::rows.
Member Data Documentation
blank_symbol
char mainBoard::blank_symbol = '.' [private]
Definition at line 12 of file Ultimate_Tic_Tac_Toe.h.
Referenced by is_win(), mainBoard(), and update_board().
The documentation for this class was generated from the following files:
include/Ultimate_Tic_Tac_Toe.h
src/Ultimate_Tic_Tac_Toe.cpp