Player< T > Class Template Reference
Base template for all players (human or AI).
#include <BoardGame_Classes.h>
Public Member Functions
Player (string n, T s, PlayerType t)
Construct a player with name, symbol, and type.
virtual ~Player ()
string get_name () const
Get the player's name.
PlayerType get_type () const
Get player type (e.g., 'H' or 'C').
T get_symbol () const
Get the player's symbol.
Board< T > * get_board_ptr () const
Get a pointer to the game board.
void set_board_ptr (Board< T > *b)
Assign the board pointer for the player.
Protected Attributes
string name
Player name.
PlayerType type
Player type (e.g., HUMAN or COMPUTER)
T symbol
Players symbol on board.
Board< T > * boardPtr
Pointer to the game board.
Detailed Description
template<typename T>
class Player< T >
Base template for all players (human or AI).
Template Parameters
T Type of symbol used by the player.
Definition at line 141 of file BoardGame_Classes.h.
Constructor & Destructor Documentation
Player()
template<typename T >
Player< T >::Player (string n, T s, PlayerType t) [inline]
Construct a player with name, symbol, and type.
Definition at line 152 of file BoardGame_Classes.h.
        : name(n), symbol(s), type(t), boardPtr(nullptr) {}
Referenced by AIPlayer< T >::calculateMove(), smartPlayer< T >::calculateMove(), smartPlayer2::calculateMove(), DiamondSmartPlayer::calculateMove(), FourFourAIPlayer::calculateMove(), SUS_SmartPlayer::calculateMove2(), wordSmartPlayer::calculateMove2(), FourFourAIPlayer::minimax(), AIPlayer< T >::minimax(), SUS_SmartPlayer::minimax(), wordSmartPlayer::minimax(), smartPlayer2::minimax(), and smartPlayer< T >::minimax().
~Player()
template<typename T >
virtual Player< T >::~Player () [inline], [virtual]
Definition at line 155 of file BoardGame_Classes.h.
{}
Member Function Documentation
get_board_ptr()
template<typename T >
Board< T > * Player< T >::get_board_ptr () const [inline]
Get a pointer to the game board.
Definition at line 167 of file BoardGame_Classes.h.
{ return boardPtr; }
References Player< T >::boardPtr.
Referenced by AIPlayer< T >::calculateMove(), smartPlayer< T >::calculateMove(), smartPlayer2::calculateMove(), DiamondSmartPlayer::calculateMove(), FourFourAIPlayer::calculateMove(), MisereSmartPlayer::calculateMove(), SUS_SmartPlayer::calculateMove2(), wordSmartPlayer::calculateMove2(), AIPlayer< T >::condition(), FourFourAIPlayer::condition(), FourFourAIPlayer::condition_for_symbol(), Infinit_XO_UI::get_move(), Numerical_XO_UI::get_move(), Obstacles_XO_UI::get_move(), SUS_UI::get_move(), Ultimate_XO_UI::get_move(), and Word_XO_UI::get_move().
get_name()
template<typename T >
string Player< T >::get_name () const [inline]
Get the player's name.
Definition at line 158 of file BoardGame_Classes.h.
{ return name; }
References Player< T >::name.
Referenced by Menu::print_menu(), and GameManager< T >::run().
get_symbol()
template<typename T >
T Player< T >::get_symbol () const [inline]
Get the player's symbol.
Definition at line 164 of file BoardGame_Classes.h.
{ return symbol; }
References Player< T >::symbol.
Referenced by AIPlayer< T >::calculateMove(), smartPlayer< T >::calculateMove(), smartPlayer2::calculateMove(), DiamondSmartPlayer::calculateMove(), FourFourAIPlayer::calculateMove(), SUS_SmartPlayer::calculateMove2(), wordSmartPlayer::calculateMove2(), FourFourAIPlayer::condition(), FourFourAIPlayer::createMove(), FourFourAIPlayer::createUndoMove(), AIPlayer< T >::generate_move_values(), Diamond_Tic_Tac_Toe_UI::get_move(), Four_in_a_row_UI::get_move(), Four_Four_XO_UI::get_move(), Infinit_XO_UI::get_move(), MEMORY_TIC_TAC_TOE_UI::get_move(), Misere_Tic_Tac_Toe_UI::get_move(), Numerical_XO_UI::get_move(), Obstacles_XO_UI::get_move(), Pyramid_XO_UI::get_move(), SUS_UI::get_move(), Ultimate_XO_UI::get_move(), Word_XO_UI::get_move(), X_O_5x5_UI::get_move(), AIPlayer< T >::get_opponent_symbol(), smartPlayer< T >::get_opponent_symbol(), smartPlayer< T >::is_draw(), Misere_Tic_Tac_Toe_board::is_lose(), Four_Four_XO_Board::is_win(), Diamond_Tic_Tac_Toe_Board::is_win(), Four_in_a_row_Board::is_win(), Infinity_X_O_Board::is_win(), MEMORY_TIC_TAC_TOE_Board::is_win(), Numerical_X_O_Board::is_win(), Obstacles_XO_Board::is_win(), Pyramid_XO_Board::is_win(), SUS_Board::is_win(), mainBoard::is_win(), Word_XO_Board::is_win(), X_O_5x5_Board::is_win(), Diamond_Tic_Tac_Toe_Board::update_board(), Four_in_a_row_Board::update_board(), Four_Four_XO_Board::update_board(), Infinity_X_O_Board::update_board(), MEMORY_TIC_TAC_TOE_Board::update_board(), Misere_Tic_Tac_Toe_board::update_board(), Numerical_X_O_Board::update_board(), Obstacles_XO_Board::update_board(), Pyramid_XO_Board::update_board(), SUS_Board::update_board(), mainBoard::update_board(), Ultimate_XO_Board::update_board(), Word_XO_Board::update_board(), and X_O_5x5_Board::update_board().
get_type()
template<typename T >
PlayerType Player< T >::get_type () const [inline]
Get player type (e.g., 'H' or 'C').
Definition at line 161 of file BoardGame_Classes.h.
{ return type; }
References Player< T >::type.
Referenced by Diamond_Tic_Tac_Toe_UI::get_move(), Four_in_a_row_UI::get_move(), Infinit_XO_UI::get_move(), MEMORY_TIC_TAC_TOE_UI::get_move(), Misere_Tic_Tac_Toe_UI::get_move(), Numerical_XO_UI::get_move(), Obstacles_XO_UI::get_move(), Pyramid_XO_UI::get_move(), SUS_UI::get_move(), Ultimate_XO_UI::get_move(), Word_XO_UI::get_move(), and X_O_5x5_UI::get_move().
set_board_ptr()
template<typename T >
void Player< T >::set_board_ptr (Board< T > * b) [inline]
Assign the board pointer for the player.
Definition at line 170 of file BoardGame_Classes.h.
{ boardPtr = b; }
References Player< T >::boardPtr.
Referenced by FourFourAIPlayer::evaluate_board(), GameManager< T >::GameManager(), FourFourAIPlayer::minimax(), and AIPlayer< T >::minimax().
Member Data Documentation
boardPtr
template<typename T >
Board<T>* Player< T >::boardPtr [protected]
Pointer to the game board.
Definition at line 146 of file BoardGame_Classes.h.
Referenced by FourFourAIPlayer::evaluate_board(), AIPlayer< T >::evaluate_board(), Player< T >::get_board_ptr(), FourFourAIPlayer::minimax(), AIPlayer< T >::minimax(), and Player< T >::set_board_ptr().
name
template<typename T >
string Player< T >::name [protected]
Player name.
Definition at line 143 of file BoardGame_Classes.h.
Referenced by UI< T >::create_player(), and Player< T >::get_name().
symbol
template<typename T >
T Player< T >::symbol [protected]
Players symbol on board.
Definition at line 145 of file BoardGame_Classes.h.
Referenced by MisereSmartPlayer::calculateMove(), MisereSmartPlayer::check_3_in_row(), FourFourAIPlayer::condition_for_symbol(), UI< T >::create_player(), FourFourAIPlayer::createUndoMoveForSymbol(), DiamondSmartPlayer::evaluate_board(), smartPlayer< T >::evaluate_board(), DiamondSmartPlayer::get_opponent_symbol(), MisereSmartPlayer::get_opponent_symbol(), Player< T >::get_symbol(), DiamondSmartPlayer::is_win(), smartPlayer2::is_win(), smartPlayer< T >::is_win(), and MisereSmartPlayer::minimax_misere().
type
template<typename T >
PlayerType Player< T >::type [protected]
Player type (e.g., HUMAN or COMPUTER)
Definition at line 144 of file BoardGame_Classes.h.
Referenced by UI< T >::create_player(), and Player< T >::get_type().
The documentation for this class was generated from the following file:
include/BoardGame_Classes.h