DiamondSmartPlayer Class Reference
#include <Diamond_Tic_Tac_Toe.h>
Public Member Functions
virtual pair< int, int > calculateMove () override
Calculate the best move through Minmax algorithms.
virtual char get_opponent_symbol () const override
virtual int evaluate_board (const vector< vector< char > > &b, char ai, char opp, int N=3) const override
virtual bool is_win (const vector< vector< char > > &b, char symbol, int N=3) const override
Public Member Functions inherited from smartPlayer< char >
smartPlayer (string n, char s, PlayerType t)
virtual ~smartPlayer ()
Public Member Functions inherited from Player< T >
Player (string n, T s, PlayerType t)
Construct a player with name, symbol, and type.
virtual ~Player ()
string get_name () const
Get the player's name.
PlayerType get_type () const
Get player type (e.g., 'H' or 'C').
T get_symbol () const
Get the player's symbol.
Board< T > * get_board_ptr () const
Get a pointer to the game board.
void set_board_ptr (Board< T > *b)
Assign the board pointer for the player.
Additional Inherited Members
Protected Member Functions inherited from smartPlayer< char >
virtual bool is_draw (const vector< vector< char > > &b, int N=3) const
virtual int minimax (vector< vector< char > > &b, bool maximizingPlayer, char ai, char opp, int alpha, int beta, int depth, int N=3)
Protected Attributes inherited from Player< T >
string name
Player name.
PlayerType type
Player type (e.g., HUMAN or COMPUTER)
T symbol
Players symbol on board.
Board< T > * boardPtr
Pointer to the game board.
Detailed Description
Definition at line 108 of file Diamond_Tic_Tac_Toe.h.
Member Function Documentation
calculateMove()
pair< int, int > DiamondSmartPlayer::calculateMove () [override], [virtual]
Calculate the best move through Minmax algorithms.
Returns
the best (x,y) coordinates for computer Move
Reimplemented from smartPlayer< char >.
Definition at line 272 of file Diamond_Tic_Tac_Toe.cpp.
                                                 {
    Board<char>* board_ptr = this->get_board_ptr();
    auto tempBoard = board_ptr->get_board_matrix();
    char ai = this->get_symbol();
    char opp = get_opponent_symbol();
    int bestVal = numeric_limits<int>::min();
    int bestX = -1, bestY = -1;
    int maxDepth = 3;
    for (int i = 0; i < 7; i++) {
        for (int j = 0; j < 7; j++) {
            if (tempBoard[i][j] == '.' && abs(i - 3) + abs(j - 3) <= 3) {
                tempBoard[i][j] = ai;
                int moveVal = minimax(tempBoard, false, ai, opp,
                                      numeric_limits<int>::min(),
                                      numeric_limits<int>::max(),
                                      maxDepth);
                tempBoard[i][j] = '.';
                if (moveVal > bestVal) {
                    bestVal = moveVal;
                    bestX = i;
                    bestY = j;
                }
            }
        }
    }
    return {bestX, bestY};
}
References Player< T >::get_board_ptr(), get_opponent_symbol(), Player< T >::get_symbol(), smartPlayer< char >::minimax(), and Player< T >::Player().
evaluate_board()
int DiamondSmartPlayer::evaluate_board (const vector< vector< char > > & b, char ai, char opp, int N = 3) const [override], [virtual]
Reimplemented from smartPlayer< char >.
Definition at line 188 of file Diamond_Tic_Tac_Toe.cpp.
                                                                                                    {
    int position_weights[7][7] = {
        {0, 0, 0, 1, 0, 0, 0},
        {0, 0, 2, 3, 2, 0, 0},
        {0, 2, 4, 5, 4, 2, 0},
        {1, 3, 5, 8, 5, 3, 1},
        {0, 2, 4, 5, 4, 2, 0},
        {0, 0, 2, 3, 2, 0, 0},
        {0, 0, 0, 1, 0, 0, 0}
    };
    int score = 0;
    int rows = b.size();
    int cols = b[0].size();
    for(int i=0; i<rows; i++) {
        for(int j=0; j<cols; j++) {
            if (b[i][j] == ai) score += position_weights[i][j];
            else if (b[i][j] == opp) score -= position_weights[i][j];
        }
    }
    auto analyze_player = [&](char symbol) -> int {
        int max_h = 0, max_v = 0, max_d1 = 0, max_d2 = 0;
        for(int i=0; i<rows; i++) {
            for(int j=0; j<cols; j++) {
                if(b[i][j] != symbol) continue;
                // Horizontal
                int cnt = 0;
                for(int k=0; k<7; k++) { if(j+k<cols && b[i][j+k]==symbol) cnt++; else break; }
                max_h = max(max_h, cnt);
                // Vertical
                cnt = 0;
                for(int k=0; k<7; k++) { if(i+k<rows && b[i+k][j]==symbol) cnt++; else break; }
                max_v = max(max_v, cnt);
                // Diag 1
                cnt = 0;
                for(int k=0; k<7; k++) { if(i+k<rows && j+k<cols && b[i+k][j+k]==symbol) cnt++; else break; }
                max_d1 = max(max_d1, cnt);
                // Diag 2
                cnt = 0;
                for(int k=0; k<7; k++) { if(i+k<rows && j-k>=0 && b[i+k][j-k]==symbol) cnt++; else break; }
                max_d2 = max(max_d2, cnt);
            }
        }
        int p_score = 0;
        vector<int> lines = {max_h, max_v, max_d1, max_d2};
        sort(lines.rbegin(), lines.rend());
        int best = lines[0];
        int second_best = lines[1];
        if (best >= 4 && second_best >= 3) return 100000;
        if (best >= 4) p_score += 2000 + (second_best * 100);
        if (best == 3) p_score += 500 + (second_best * 50);
        if (best == 2) p_score += 50;
        return p_score;
    };
    score += analyze_player(ai);
    score -= (analyze_player(opp) * 1.5);
    return score;
}
References Player< T >::symbol.
get_opponent_symbol()
char DiamondSmartPlayer::get_opponent_symbol () const [override], [virtual]
Returns
the opponent_symbol depending on game
Reimplemented from smartPlayer< char >.
Definition at line 127 of file Diamond_Tic_Tac_Toe.cpp.
                                                   {
    return (this->symbol == 'X') ? 'O' : 'X';
}
References Player< T >::symbol.
Referenced by calculateMove().
is_win()
bool DiamondSmartPlayer::is_win (const vector< vector< char > > & b, char symbol, int N = 3) const [override], [virtual]
Reimplemented from smartPlayer< char >.
Definition at line 132 of file Diamond_Tic_Tac_Toe.cpp.
                                                                                       {
    int rows = b.size();
    int cols = b[0].size();
    int max_row = 0; // Horizontal
    int max_col = 0; // Vertical
    int max_diag1 = 0; // Main Diagonal
    int max_diag2 = 0; // Anti-Diagonal
    for (int i = 0; i < rows; i++) {
        for (int j = 0; j < cols; j++) {
            if (b[i][j] != symbol) continue;
            // 1. Horizontal
            int current = 0;
            for (int k = 0; k < 7; k++) {
                if (j + k < cols && b[i][j + k] == symbol) current++;
                else break;
            }
            max_row = max(max_row, current);
            // 2. Vertical
            current = 0;
            for (int k = 0; k < 7; k++) {
                if (i + k < rows && b[i + k][j] == symbol) current++;
                else break;
            }
            max_col = max(max_col, current);
            // 3. Diagonal 1
            current = 0;
            for (int k = 0; k < 7; k++) {
                if (i + k < rows && j + k < cols && b[i + k][j + k] == symbol) current++;
                else break;
            }
            max_diag1 = max(max_diag1, current);
            // 4. Diagonal 2
            current = 0;
            for (int k = 0; k < 7; k++) {
                if (i + k < rows && j - k >= 0 && b[i + k][j - k] == symbol) current++;
                else break;
            }
            max_diag2 = max(max_diag2, current);
        }
    }
    if (max_row >= 4 && (max_col >= 3 || max_diag1 >= 3 || max_diag2 >= 3)) return true;
    if (max_col >= 4 && (max_row >= 3 || max_diag1 >= 3 || max_diag2 >= 3)) return true;
    if (max_diag1 >= 4 && (max_row >= 3 || max_col >= 3 || max_diag2 >= 3)) return true;
    if (max_diag2 >= 4 && (max_row >= 3 || max_col >= 3 || max_diag1 >= 3)) return true;
    return false;
}
References Player< T >::symbol.
The documentation for this class was generated from the following files:
include/Diamond_Tic_Tac_Toe.h
src/Diamond_Tic_Tac_Toe.cpp