Ultimate_XO_Board Class Reference
#include <Ultimate_Tic_Tac_Toe.h>
Public Member Functions
Ultimate_XO_Board ()
Default constructor that initializes a 9*9 Board;.
bool update_board (Move< char > *move)
Updates the board with a player's move.
bool is_win (Player< char > *player)
Checks if the given player has won the game.
bool is_lose (Player< char > *)
Checks if the given player has lost the game.
bool is_draw (Player< char > *player)
Checks if the game has ended in a draw.
bool game_is_over (Player< char > *player)
Determines if the game is over (win or draw).
virtual ~Ultimate_XO_Board ()
Public Member Functions inherited from Board< char >
Board (int rows, int columns)
Construct a board with given dimensions.
virtual ~Board ()
Virtual destructor. Frees allocated board memory.
vector< vector< char > > get_board_matrix () const
Return a copy of the current board as a 2D vector.
int get_rows () const
Get number of rows.
int get_columns () const
Get number of columns.
int get_n_moves () const
Get number of moves.
char get_cell (int x, int y)
Return content of cell x, y in current board.
Private Attributes
char blank_symbol = '.'
Board< char > * mainBoardPtr = new mainBoard()
Additional Inherited Members
Protected Attributes inherited from Board< char >
int rows
Number of rows.
int columns
Number of columns.
vector< vector< char > > board
2D vector for the board
int n_moves
Number of moves made.
Detailed Description
Definition at line 57 of file Ultimate_Tic_Tac_Toe.h.
Constructor & Destructor Documentation
Ultimate_XO_Board()
Ultimate_XO_Board::Ultimate_XO_Board ()
Default constructor that initializes a 9*9 Board;.
Definition at line 62 of file Ultimate_Tic_Tac_Toe.cpp.
                                     : Board<char> (9,9) {
    // Initialize all cells with blank_symbol
    for (auto& row : board)
        for (auto& cell : row)
            cell = blank_symbol;
}
References blank_symbol, and Board< char >::board.
~Ultimate_XO_Board()
virtual Ultimate_XO_Board::~Ultimate_XO_Board () [inline], [virtual]
Definition at line 102 of file Ultimate_Tic_Tac_Toe.h.
                                 {
        delete mainBoardPtr;
    };
References mainBoardPtr.
Member Function Documentation
game_is_over()
bool Ultimate_XO_Board::game_is_over (Player< char > * player) [virtual]
Determines if the game is over (win or draw).
Parameters
player Pointer to the player to evaluate.
Returns
true if the game has ended, false otherwise.
Implements Board< char >.
Definition at line 117 of file Ultimate_Tic_Tac_Toe.cpp.
                                                         {
    return is_win(player) || is_draw(player);
}
References is_draw(), and is_win().
is_draw()
bool Ultimate_XO_Board::is_draw (Player< char > * player) [virtual]
Checks if the game has ended in a draw.
Parameters
player Pointer to the player being checked.
Returns
true if all cells are filled and no player has won, false otherwise.
Implements Board< char >.
Definition at line 113 of file Ultimate_Tic_Tac_Toe.cpp.
                                                    {
    return (n_moves == 81 && mainBoardPtr->is_draw(player));
}
References Board< T >::is_draw(), mainBoardPtr, and Board< char >::n_moves.
Referenced by game_is_over().
is_lose()
bool Ultimate_XO_Board::is_lose (Player< char > *) [inline], [virtual]
Checks if the given player has lost the game.
Parameters
player Pointer to the player being checked.
Returns
Always returns false (not used in X-O logic).
Implements Board< char >.
Definition at line 86 of file Ultimate_Tic_Tac_Toe.h.
{ return false; };
is_win()
bool Ultimate_XO_Board::is_win (Player< char > * player) [virtual]
Checks if the given player has won the game.
Parameters
player Pointer to the player being checked.
Returns
true if the player has a winning line, false otherwise.
Implements Board< char >.
Definition at line 106 of file Ultimate_Tic_Tac_Toe.cpp.
                                                   {
    if (mainBoardPtr->is_win(player)) return true;
    return false;
}
References Board< T >::is_win(), and mainBoardPtr.
Referenced by game_is_over().
update_board()
bool Ultimate_XO_Board::update_board (Move< char > * move) [virtual]
Updates the board with a player's move.
Parameters
move Pointer to a Move<char> object containing move coordinates and symbol.
Returns
true if the move is valid and successfully applied, false otherwise.
Implements Board< char >.
Definition at line 69 of file Ultimate_Tic_Tac_Toe.cpp.
                                                     {
    int x = move->get_x();
    int y = move->get_y();
    char mark = move->get_symbol();
    auto checkboard = [&](int dx, int dy) {
        const char sym = move->get_symbol();
        auto all_equal = [&](char a, char b, char c) {
            return a == b && b == c && a != blank_symbol;
        };
        // Check rows and columns
        for (int i = 0; i < 3; ++i) {
            if ((all_equal(board[i+dx][0+dy], board[i+dx][1+dy], board[i+dx][2+dy]) && board[i+dx][0+dy] == sym) ||
                (all_equal(board[0+dx][i+dy], board[1+dx][i+dy], board[2+dx][i+dy]) && board[0+dx][i+dy] == sym))
                return true;
        }
        // Check diagonals
        if ((all_equal(board[dx+0][dy+0], board[dx+1][dy+1], board[dx+2][dy+2]) && board[dx+1][dy+1] == sym) ||
            (all_equal(board[dx+0][dy+2], board[dx+1][dy+1], board[dx+2][dy+0]) && board[dx+1][dy+1] == sym))
            return true;
        return false;
    };
    // Validate move and apply if valid
    if (!(x < 0 || x >= rows || y < 0 || y >= columns) && (board[x][y] == blank_symbol)) {
        board[x][y] = toupper(mark);
        n_moves++;
        if (checkboard((x/3) * 3,(y/3) * 3)) mainBoardPtr->update_board(move);
        return true;
    }
    return false;
}
References blank_symbol, Board< char >::board, Board< char >::columns, Player< T >::get_symbol(), mainBoardPtr, Board< char >::n_moves, Board< char >::rows, and Board< T >::update_board().
Member Data Documentation
blank_symbol
char Ultimate_XO_Board::blank_symbol = '.' [private]
Definition at line 59 of file Ultimate_Tic_Tac_Toe.h.
Referenced by Ultimate_XO_Board(), and update_board().
mainBoardPtr
Board<char>* Ultimate_XO_Board::mainBoardPtr = new mainBoard() [private]
Definition at line 60 of file Ultimate_Tic_Tac_Toe.h.
Referenced by is_draw(), is_win(), update_board(), and ~Ultimate_XO_Board().
The documentation for this class was generated from the following files:
include/Ultimate_Tic_Tac_Toe.h
src/Ultimate_Tic_Tac_Toe.cpp