Numerical_XO_UI Class Reference
#include <Numerical_X_O.h>
Public Member Functions
Numerical_XO_UI ()
Player< char > * create_player (string &name, char symbol, PlayerType type)
virtual Move< char > * get_move (Player< char > *player)
Ask the user (or AI) to make a move.
virtual ~Numerical_XO_UI ()
Public Member Functions inherited from UI< char >
UI (int cell_display_width=3)
Construct the UI and display a welcome message.
UI (string message, int cell_display_width)
Construct the UI and display a welcome message.
virtual ~UI ()
virtual void display_message (string message)
Display any message to the user.
virtual Player< char > ** setup_players ()
Set up players for the game.
virtual Player< char > * create_player (string &name, char symbol, PlayerType type)
Create a player object based on input name, symbol, and type.
virtual void display_board_matrix (const vector< vector< char > > &matrix) const
Display the current board matrix in formatted form.
Additional Inherited Members
Protected Member Functions inherited from UI< char >
virtual string get_player_name (string player_label)
Ask the user for the player's name.
virtual PlayerType get_player_type_choice (string player_label, const vector< string > &options)
Ask the user to choose the player type from a list.
Protected Attributes inherited from UI< char >
int cell_width
Width of each displayed board cell.
Detailed Description
Definition at line 33 of file Numerical_X_O.h.
Constructor & Destructor Documentation
Numerical_XO_UI()
Numerical_XO_UI::Numerical_XO_UI ()
Definition at line 84 of file Numerical_X_O.cpp.
: UI<char>("Weclome to FCAI X-O Game", 3) {}
~Numerical_XO_UI()
virtual Numerical_XO_UI::~Numerical_XO_UI () [inline], [virtual]
Definition at line 42 of file Numerical_X_O.h.
{}
Member Function Documentation
create_player()
Player< char > * Numerical_XO_UI::create_player (string & name, char symbol, PlayerType type)
Definition at line 86 of file Numerical_X_O.cpp.
                                                                                       {
    // Create player based on type
    cout << "Creating " << (type == PlayerType::HUMAN ? "human" : "computer")
        << " player: " << name << " (" << symbol << ")\n";
    return new Player<char>(name, symbol, type);
}
References HUMAN.
get_move()
Move< char > * Numerical_XO_UI::get_move (Player< char > *) [virtual]
Ask the user (or AI) to make a move.
Returns
nmove a derived class from move
Implements UI< char >.
Definition at line 95 of file Numerical_X_O.cpp.
                                                          {
    int x, y;
    char val;
    if (player->get_type() == PlayerType::HUMAN) {
        cout << "\nPlease enter your move x and y (0 to 2) and value: ";
        cin >> x >> y >> val;
    }
    else if (player->get_type() == PlayerType::COMPUTER) {
        x = rand() % player->get_board_ptr()->get_rows();
        y = rand() % player->get_board_ptr()->get_columns();
        random_device rd;
        mt19937 gen(rd());
        int L = 1, R = 9;
        if(player->get_symbol() == 'X') {
            uniform_int_distribution<int> odd_dist(L/2, (R-1)/2);
            int num = odd_dist(gen) * 2 + 1;
            val = (num+'0');
        }
        else {
            uniform_int_distribution<int> even_dist((L+1)/2, R/2);
            int num = even_dist(gen) * 2;
            val = (num+'0');
        }
    }
    return new nMove(x, y, player->get_symbol(), val);
}
References COMPUTER, Player< T >::get_board_ptr(), Player< T >::get_symbol(), Player< T >::get_type(), and HUMAN.
The documentation for this class was generated from the following files:
include/Numerical_X_O.h
src/Numerical_X_O.cpp