Pyramid_XO_Board Class Reference
#include <Pyramid_XO.h>
Public Member Functions
Pyramid_XO_Board ()
Default constructor that initializes a 3x5 X-O board.
bool update_board (Move< char > *move)
Updates the board with a player's move.
bool is_win (Player< char > *player)
Checks if the given player has won the game.
bool is_lose (Player< char > *)
Checks if the given player has lost the game.
bool is_draw (Player< char > *player)
Checks if the game has ended in a draw.
bool game_is_over (Player< char > *player)
Determines if the game is over (win or draw).
virtual ~Pyramid_XO_Board ()
Public Member Functions inherited from Board< char >
Board (int rows, int columns)
Construct a board with given dimensions.
virtual ~Board ()
Virtual destructor. Frees allocated board memory.
vector< vector< char > > get_board_matrix () const
Return a copy of the current board as a 2D vector.
int get_rows () const
Get number of rows.
int get_columns () const
Get number of columns.
int get_n_moves () const
Get number of moves.
char get_cell (int x, int y)
Return content of cell x, y in current board.
Private Attributes
char blank_symbol = '.'
Character used to represent an empty cell on the board.
Additional Inherited Members
Protected Attributes inherited from Board< char >
int rows
Number of rows.
int columns
Number of columns.
vector< vector< char > > board
2D vector for the board
int n_moves
Number of moves made.
Detailed Description
Definition at line 11 of file Pyramid_XO.h.
Constructor & Destructor Documentation
Pyramid_XO_Board()
Pyramid_XO_Board::Pyramid_XO_Board ()
Default constructor that initializes a 3x5 X-O board.
Definition at line 13 of file Pyramid_XO.cpp.
                                   : Board<char>(3,5) {
    int distant[3] = {0,1,2}; // range for each row to build pyramid shape
    for (int i = 0; i<rows; i++) {
        for (int j = 0; j<columns; j++) {
            if (abs(j-2)<=distant[i]) board[i][j] = blank_symbol;
            else board[i][j] = '#';
        }
    }
}
References blank_symbol, Board< char >::board, Board< char >::columns, and Board< char >::rows.
~Pyramid_XO_Board()
virtual Pyramid_XO_Board::~Pyramid_XO_Board () [inline], [virtual]
Definition at line 56 of file Pyramid_XO.h.
{};
Member Function Documentation
game_is_over()
bool Pyramid_XO_Board::game_is_over (Player< char > * player) [virtual]
Determines if the game is over (win or draw).
Parameters
player Pointer to the player to evaluate.
Returns
true if the game has ended, false otherwise.
Implements Board< char >.
Definition at line 72 of file Pyramid_XO.cpp.
                                                        {
    return is_win(player) || is_draw(player);
}
References is_draw(), and is_win().
is_draw()
bool Pyramid_XO_Board::is_draw (Player< char > * player) [virtual]
Checks if the game has ended in a draw.
Parameters
player Pointer to the player being checked.
Returns
true if all cells are filled and no player has won, false otherwise.
Implements Board< char >.
Definition at line 68 of file Pyramid_XO.cpp.
                                                   {
    return (n_moves == 9 && !is_win(player));
}
References is_win(), and Board< char >::n_moves.
Referenced by game_is_over().
is_lose()
bool Pyramid_XO_Board::is_lose (Player< char > *) [inline], [virtual]
Checks if the given player has lost the game.
Parameters
player Pointer to the player being checked.
Returns
Always returns false (not used in X-O logic).
Implements Board< char >.
Definition at line 40 of file Pyramid_XO.h.
{ return false; };
is_win()
bool Pyramid_XO_Board::is_win (Player< char > * player) [virtual]
Checks if the given player has won the game.
Parameters
player Pointer to the player being checked.
Returns
true if the player has a winning line, false otherwise.
Implements Board< char >.
Definition at line 40 of file Pyramid_XO.cpp.
                                                  {
    const char sym = player->get_symbol();
    auto all_equal = [&](char a, char b, char c) {
        return a == b && b == c && a != blank_symbol;
    };
    // Check Column (3*5 pyramid has only one column possible column of size 3)
    if (all_equal(board[0][2],board[1][2],board[2][2]) && board[0][2]==sym) return true;
    // Check 2nd row
    if (all_equal(board[1][1],board[1][2],board[1][3]) && board[1][1]==sym) return true;
    // Check 3rd row
    if (all_equal(board[2][0],board[2][1],board[2][2]) && board[2][2]==sym) return true;
    if (all_equal(board[2][1],board[2][2],board[2][3]) && board[2][2]==sym) return true;
    if (all_equal(board[2][2],board[2][3],board[2][4]) && board[2][2]==sym) return true;
    // Check diagonals of pyramid (has only two diagonals)
    if ((all_equal(board[0][2], board[1][1], board[2][0]) && board[0][2] == sym) ||
        (all_equal(board[0][2], board[1][3], board[2][4]) && board[0][2] == sym))
        return true;
    return false;
}
References blank_symbol, Board< char >::board, and Player< T >::get_symbol().
Referenced by game_is_over(), and is_draw().
update_board()
bool Pyramid_XO_Board::update_board (Move< char > * move) [virtual]
Updates the board with a player's move.
Parameters
move Pointer to a Move<char> object containing move coordinates and symbol.
Returns
true if the move is valid and successfully applied, false otherwise.
Implements Board< char >.
Definition at line 24 of file Pyramid_XO.cpp.
                                                    {
    int x = move->get_x();
    int y = move->get_y();
    char mark = move->get_symbol();
    // Validate move and apply if valid
    if (!(x < 0 || x >= rows || y < 0 || y >= columns) &&
    (board[x][y] == blank_symbol)) {
        n_moves++;
        board[x][y] = mark;
        return true;
    }
    return false;
}
References blank_symbol, Board< char >::board, Board< char >::columns, Player< T >::get_symbol(), Board< char >::n_moves, and Board< char >::rows.
Member Data Documentation
blank_symbol
char Pyramid_XO_Board::blank_symbol = '.' [private]
Character used to represent an empty cell on the board.
Definition at line 13 of file Pyramid_XO.h.
Referenced by is_win(), Pyramid_XO_Board(), and update_board().
The documentation for this class was generated from the following files:
include/Pyramid_XO.h
src/Pyramid_XO.cpp