Four_Four_XO_UI Class Reference
User Interface class for 4*4 XO Tic Tac Toe Game.
#include <Four_Four_XO.h>
Public Member Functions
Four_Four_XO_UI ()
virtual Player< char > ** setup_players () override
Set up players (Human or Computer).
virtual Player< char > * create_player (string &name, char symbol, PlayerType type) override
Create a player based on name, symbol, and type.
virtual Move< char > * get_move (Player< char > *player)
Retrieves the next move from a player.
virtual ~Four_Four_XO_UI ()
Public Member Functions inherited from UI< char >
UI (int cell_display_width=3)
Construct the UI and display a welcome message.
UI (string message, int cell_display_width)
Construct the UI and display a welcome message.
virtual ~UI ()
virtual void display_message (string message)
Display any message to the user.
virtual Player< char > * create_player (string &name, char symbol, PlayerType type)
Create a player object based on input name, symbol, and type.
virtual void display_board_matrix (const vector< vector< char > > &matrix) const
Display the current board matrix in formatted form.
Additional Inherited Members
Protected Member Functions inherited from UI< char >
virtual string get_player_name (string player_label)
Ask the user for the player's name.
virtual PlayerType get_player_type_choice (string player_label, const vector< string > &options)
Ask the user to choose the player type from a list.
Protected Attributes inherited from UI< char >
int cell_width
Width of each displayed board cell.
Detailed Description
User Interface class for 4*4 XO Tic Tac Toe Game.
Inherits from the generic UI<char> base class and provides X-Ospecific functionality for player setup and move input.
See also
UI
Definition at line 424 of file Four_Four_XO.h.
Constructor & Destructor Documentation
Four_Four_XO_UI()
Four_Four_XO_UI::Four_Four_XO_UI () [inline]
Definition at line 427 of file Four_Four_XO.h.
: UI<char>("Welcome to Four-Four Tic Tac Toe Game",3) {}
~Four_Four_XO_UI()
virtual Four_Four_XO_UI::~Four_Four_XO_UI () [inline], [virtual]
Definition at line 446 of file Four_Four_XO.h.
{};
Member Function Documentation
create_player()
Player< char > * Four_Four_XO_UI::create_player (string & name, char symbol, PlayerType type) [override], [virtual]
Create a player based on name, symbol, and type.
Definition at line 90 of file Four_Four_XO.cpp.
                                                                                       {
    cout << "Creating " << (type == PlayerType::HUMAN ? "human" : "computer")
         << " player: " << name << " (" << symbol << ")\n";
    if (type == PlayerType::COMPUTER) {
        // Use AI player with COMPUTER type - it will use calculateMove() instead of random
        return new FourFourAIPlayer(name, symbol, type);
    } else {
        return new Player<char>(name, symbol, type);
    }
}
References COMPUTER, and HUMAN.
Referenced by setup_players().
get_move()
Move< char > * Four_Four_XO_UI::get_move (Player< char > * player) [virtual]
Retrieves the next move from a player.
Parameters
player Pointer to the player whose move is being requested.
Returns
A pointer to a new Move<char> object representing the player's action.
Implements UI< char >.
Definition at line 102 of file Four_Four_XO.cpp.
                                                          {
    // Check if player is an AI player (Computer uses FourFourAIPlayer)
    FourFourAIPlayer* aiPlayer = dynamic_cast<FourFourAIPlayer*>(player);
    if (aiPlayer) {
        // Use AI's calculateMove instead of random
        return aiPlayer->calculateMove();
    }
    
    // Human player
    int x,y,dx,dy;
    int dir;
    vector<pair<int,int>> dirs = {{1,0}, {0,1}, {-1,0}, {0,-1}}; // Up, Right, Down , Left
    cout << "Please enter the coordinates of a one of your pieces to move (0 to 3): ";
    cin >> x >> y;
    cout << "Which direction you want to move your piece? (1 -> 'U', 2 -> 'R', 3 -> 'D', 4 -> 'L'): ";
    cin >> dir;
    dir--;
    while (dir<0||dir>3) {
        cout << "Enter Valid direction: (1 -> 'U', 2 -> 'R', 3 -> 'D', 4 -> 'L'): ";
        cin >> dir;
        dir--;
    }
    dx = dirs[dir].first;
    dy = dirs[dir].second;
    return new dualMove(x,y,player->get_symbol(),dy,dx);
}
References Player< T >::get_symbol().
setup_players()
Player< char > ** Four_Four_XO_UI::setup_players () [override], [virtual]
Set up players (Human or Computer).
Reimplemented from UI< char >.
Definition at line 75 of file Four_Four_XO.cpp.
                                              {
    Player<char>** players = new Player<char>*[2];
    vector<string> type_options = { "Human", "Computer" };
    string nameX = get_player_name("Player X");
    PlayerType typeX = get_player_type_choice("Player X", type_options);
    players[0] = create_player(nameX, 'X', typeX);
    string nameO = get_player_name("Player O");
    PlayerType typeO = get_player_type_choice("Player O", type_options);
    players[1] = create_player(nameO, 'O', typeO);
    return players;
}
References create_player(), UI< char >::get_player_name(), and UI< char >::get_player_type_choice().
The documentation for this class was generated from the following files:
include/Four_Four_XO.h
src/Four_Four_XO.cpp