Numerical_X_O_Board Class Reference
#include <Numerical_X_O.h>
Public Member Functions
Numerical_X_O_Board ()
bool update_board (Move< char > *move)
Update the board with a new move.
bool is_win (Player< char > *player)
Check if a player has won.
bool is_lose (Player< char > *)
Check if a player has lost.
bool is_draw (Player< char > *player)
Check if the game ended in a draw.
bool game_is_over (Player< char > *player)
Check if the game is over.
virtual ~Numerical_X_O_Board ()
Public Member Functions inherited from Board< char >
Board (int rows, int columns)
Construct a board with given dimensions.
virtual ~Board ()
Virtual destructor. Frees allocated board memory.
vector< vector< char > > get_board_matrix () const
Return a copy of the current board as a 2D vector.
int get_rows () const
Get number of rows.
int get_columns () const
Get number of columns.
int get_n_moves () const
Get number of moves.
char get_cell (int x, int y)
Return content of cell x, y in current board.
Private Attributes
char blank_symbol = '0'
int counter
Additional Inherited Members
Protected Attributes inherited from Board< char >
int rows
Number of rows.
int columns
Number of columns.
vector< vector< char > > board
2D vector for the board
int n_moves
Number of moves made.
Detailed Description
Definition at line 8 of file Numerical_X_O.h.
Constructor & Destructor Documentation
Numerical_X_O_Board()
Numerical_X_O_Board::Numerical_X_O_Board ()
Definition at line 11 of file Numerical_X_O.cpp.
                                         : Board(3, 3), counter(0) {
    // Initialize all cells with blank_symbol
    for (auto& row : board)
        for (auto& cell : row)
            cell = blank_symbol;
    for (int i = 1; i<10;i+=2) X[(i+'0')] = 1;
    for (int i = 2;i<10;i+=2) O[(i+'0')] = 1;
}
References blank_symbol, Board< char >::board, O, and X.
~Numerical_X_O_Board()
virtual Numerical_X_O_Board::~Numerical_X_O_Board () [inline], [virtual]
Definition at line 30 of file Numerical_X_O.h.
{}
Member Function Documentation
game_is_over()
bool Numerical_X_O_Board::game_is_over (Player< char > *) [virtual]
Check if the game is over.
Implements Board< char >.
Definition at line 78 of file Numerical_X_O.cpp.
                                                           {
    return is_win(player) || is_draw(player);
}
References is_draw(), and is_win().
is_draw()
bool Numerical_X_O_Board::is_draw (Player< char > *) [virtual]
Check if the game ended in a draw.
Implements Board< char >.
Definition at line 74 of file Numerical_X_O.cpp.
                                                      {
    return (n_moves == 9 && !is_win(player));
}
References is_win(), and Board< char >::n_moves.
Referenced by game_is_over().
is_lose()
bool Numerical_X_O_Board::is_lose (Player< char > *) [inline], [virtual]
Check if a player has lost.
Implements Board< char >.
Definition at line 22 of file Numerical_X_O.h.
{ return false; };
is_win()
bool Numerical_X_O_Board::is_win (Player< char > *) [virtual]
Check if a player has won.
Implements Board< char >.
Definition at line 52 of file Numerical_X_O.cpp.
                                                     {
    const char sym = player->get_symbol();
    auto all_equal = [&](char a, char b, char c) {
        return (a-'0')+(b-'0')+(c-'0') == 15;
        };
    // Check rows and columns
    for (int i = 0; i < rows; ++i) {
        if ((all_equal(board[i][0], board[i][1], board[i][2])) ||
            (all_equal(board[0][i], board[1][i], board[2][i])))
            return true;
    }
    // Check diagonals
    if ((all_equal(board[0][0], board[1][1], board[2][2])) ||
        (all_equal(board[0][2], board[1][1], board[2][0])))
        return true;
    return false;
}
References Board< char >::board, Player< T >::get_symbol(), and Board< char >::rows.
Referenced by game_is_over(), and is_draw().
update_board()
bool Numerical_X_O_Board::update_board (Move< char > * move) [virtual]
Update the board with a new move.
Parameters
move The move object containing position and symbol.
Returns
true if the move is valid and applied, false otherwise.
Implements Board< char >.
Definition at line 22 of file Numerical_X_O.cpp.
                                                       {
    // Convert Move<char>* → nMove*
    nMove* nm = dynamic_cast<nMove*>(move);
    if (!nm) return false;
    int x = nm->get_x();
    int y = nm->get_y();
    char val = nm->get_value();
    char mark = move->get_symbol();
    if (!(x < 0 || x >= rows || y < 0 || y >= columns) && (board[x][y] == blank_symbol)) {
        if(mark == 'X' && X[val] == 1) {
            X[val] = 2;
        }
        else if(mark == 'O' && O[val] == 1) {
            O[val] = 2;
        }
        else return false;
        n_moves++;
        board[x][y] = val;
        counter++;
        return true;
    }
    return false;
}
References blank_symbol, Board< char >::board, Board< char >::columns, counter, Player< T >::get_symbol(), Board< char >::n_moves, O, Board< char >::rows, and X.
Member Data Documentation
blank_symbol
char Numerical_X_O_Board::blank_symbol = '0' [private]
Definition at line 10 of file Numerical_X_O.h.
Referenced by Numerical_X_O_Board(), and update_board().
counter
int Numerical_X_O_Board::counter [private]
Definition at line 11 of file Numerical_X_O.h.
Referenced by update_board().
The documentation for this class was generated from the following files:
include/Numerical_X_O.h
src/Numerical_X_O.cpp