src/Words_XO.cpp File Reference
#include <iostream>
#include <unordered_set>
#include <iomanip>
#include <cctype>
#include <random>
#include <fstream>
#include "../include/Words_XO.h"
#include "../include/Smart_Player.h"
Classes
class wordSmartPlayer
Functions
void load_global_dictionary (const string &path="../dic.txt")
bool Check_word (const string &W)
Variables
const vector< char > LETTERS
static unordered_set< string > GLOBAL_DICT
static bool GLOBAL_DICT_LOADED = false
Function Documentation
Check_word()
bool Check_word (const string & W)
Definition at line 287 of file Words_XO.cpp.
                                 {
    if (!GLOBAL_DICT_LOADED) load_global_dictionary("../dic.txt");
    string t = W;
    for (char &c : t) c = toupper(static_cast<unsigned char>(c));
    return GLOBAL_DICT.count(t) > 0;
}
References GLOBAL_DICT, GLOBAL_DICT_LOADED, and load_global_dictionary().
Referenced by Word_XO_Board::is_win().
load_global_dictionary()
void load_global_dictionary (const string & path = "../dic.txt")
Definition at line 265 of file Words_XO.cpp.
                                                               {
    if (GLOBAL_DICT_LOADED) return;
    ifstream f(path);
    if (!f.is_open()) {
        cerr << "Warning: cannot open " << path << "\n";
        GLOBAL_DICT_LOADED = true; // prevent repeated warnings
        return;
    }
    string line;
    while (getline(f, line)) {
        // trim
        size_t s = 0, e = line.size();
        while (s < e && isspace((unsigned char)line[s])) ++s;
        while (e > s && isspace((unsigned char)line[e-1])) --e;
        if (e - s == 0) continue;
        string w = line.substr(s, e - s);
        for (char &c : w) c = toupper(static_cast<unsigned char>(c));
        GLOBAL_DICT.insert(w);
    }
    GLOBAL_DICT_LOADED = true;
}
References GLOBAL_DICT, and GLOBAL_DICT_LOADED.
Referenced by Check_word().
Variable Documentation
GLOBAL_DICT
unordered_set<string> GLOBAL_DICT [static]
Definition at line 262 of file Words_XO.cpp.
Referenced by Check_word(), and load_global_dictionary().
GLOBAL_DICT_LOADED
bool GLOBAL_DICT_LOADED = false [static]
Definition at line 263 of file Words_XO.cpp.
Referenced by Check_word(), and load_global_dictionary().
LETTERS
const vector<char> LETTERS
Initial value:
= {
    'A','B','C','D','E','F','G','H','I','J',
    'K','L','M','N','O','P','Q','R','S','T',
    'U','V','W','X','Y','Z'
}
Definition at line 13 of file Words_XO.cpp.
                             {
    'A','B','C','D','E','F','G','H','I','J',
    'K','L','M','N','O','P','Q','R','S','T',
    'U','V','W','X','Y','Z'
};
Referenced by wordSmartPlayer::calculateMove2(), and wordSmartPlayer::loadDictionary().